/* ─────────────────────────────────────────────────────────────
 * 임상검사 술기 — SOAP의 O(Objective)를 "어떻게 파악하는가"
 *
 * SOAP 템플릿의 O에는 관찰·계측 결과만 적고, 그 값을 만드는 방법은 여기에 둔다.
 * 각 항목 구성
 *   목적 — 무엇을 알아내려는 검사인가, 언제 시행하는가
 *   술기 — 준비와 단계. 힘·시간·각도 등 값을 좌우하는 조건
 *   기준 — 정상치·판정 기준
 *   해석 — 결과가 의미하는 것, 감별
 *   함정 — 값을 틀리게 만드는 흔한 오류
 * ───────────────────────────────────────────────────────────── */

const EXAM_CATS = ["전신 평가", "소아·성장", "구강내과", "치주", "치아·치수", "교합", "악관절·근육", "보철 적합", "무치악 평가", "임플란트", "계측·기록"];
const EXAM_SEED_VERSION = 5;

const EXAM_SEED = [
  // ═══════════ 전신 평가 ═══════════
  {
    title: "활력징후 측정 및 ASA 판정",
    category: "전신 평가", order: 1,
    source: "Malamed, Medical Emergencies in the Dental Office / ASA Physical Status Classification",
    purpose: "- 시술 전 **전신 위험도**를 객관적으로 판정\n- 국소마취·침습 처치의 안전 범위와 예약 조정(시간대·처치량) 결정\n- 초진, 침습 시술 전, 고위험군 매 내원 시",
    technique: "**혈압**\n1. 5분 안정 후, 등받이에 기대 앉히고 팔을 심장 높이로\n2. 커프는 상완 둘레의 약 80%를 감싸는 크기 — **작으면 높게, 크면 낮게** 측정된다\n3. 한 번 높으면 **2–3분 뒤 재측정**, 필요 시 반대팔 비교\n\n**맥박**\n- 요골동맥에서 **30초 측정 × 2** (불규칙하면 60초 전체)\n- 수·리듬·강도를 함께 — 불규칙하면 심방세동 등을 시사\n\n**호흡수·SpO₂**(필요 시), 혈당(당뇨 환자에서 증상 있을 때)\n\n**ASA 판정**\n- 병력·조절 상태·일상 활동 제한을 종합해 등급을 매기고, **등급 근거를 함께** 기재",
    criteria: "- 측정값은 **수치 그대로** 기록(“정상”이라 쓰지 않는다)\n- **ASA I** 건강 / **II** 경도 전신질환, 조절됨 / **III** 중등도–중증, 활동 제한 / **IV** 지속적 생명 위협\n- 재측정 시 **시각과 조건**을 함께 적는다",
    interpretation: "- **혈압이 높게 나왔다고 그날 곧바로 진단하지 않는다** — 치과 환경의 긴장 반응이 흔하다. 재측정·기록·의뢰 판단으로 잇는다\n- **불규칙 맥박**은 항응고 여부·출혈 위험 평가와 연결\n- ASA III 이상이면 **처치량·시간·마취 용량**을 조정하고 협진 필요성을 기재",
    pitfalls: "<div class=\"warning\"><b>⚠️ 측정 조건이 값을 만든다</b>커프 크기 불일치, 팔 높이, 대화 중 측정, 안정 없이 바로 측정 — 모두 수십 mmHg를 움직입니다. <u>조건을 기록하지 않은 수치는 비교 근거가 되지 않습니다.</u></div>",
  },

  // ═══════════ 구강내과 ═══════════
  {
    title: "구강암 선별 검사",
    category: "구강내과", order: 1,
    source: "Burket's Oral Medicine / Neville, Oral and Maxillofacial Pathology",
    purpose: "- 악성·전암 병변을 **증상이 생기기 전에** 발견\n- 모든 초진과 정기 검진의 필수 절차 — 무치악 고령 환자에서도 생략하지 않는다",
    technique: "**순서를 고정해 빠짐을 막는다 (약 2분)**\n1. **구외**: 안면 대칭, 피부, 구순 홍순부\n2. **경부 림프절** 촉진 (아래 별도 항목)\n3. **구순·협점막**: 뒤집어 전정까지, 좌우\n4. **치은·치조점막**: 협측·설측 전체\n5. **혀**: 배면 → **설측연을 거즈로 잡아 당겨 좌우** → 설복\n6. **구강저**: 혀를 들어 올리고 **양손 촉진(bimanual)**\n7. **경구개·연구개·구협·구인두**: 설압자와 “아” 발음\n\n- **거즈로 혀를 잡아 당기지 않으면 설측연 후방을 볼 수 없다** — 호발 부위를 놓치는 지점\n- 의치는 반드시 제거하고 검사",
    criteria: "- 병소 발견 시 **위치·크기(mm)·색·표면·경계·경도·가동성**을 모두 기술\n- 정상이면 “oral cancer screening unremarkable”처럼 **시행 사실을 남긴다**",
    interpretation: "**경고 소견 — 하나라도 있으면 의뢰**\n- **2주 이상 낫지 않는 궤양**\n- **경결(induration)**, 융기·외번된 변연\n- 원인 없는 출혈, 지속되는 백색·홍색 병변\n- 고정된 단단한 림프절, 감각 이상, 개구 제한\n- **무통성이 흔하다** — 통증이 없다는 것이 안심 근거가 되지 않는다",
    pitfalls: "<div class=\"danger\"><b>🚫 놓치는 지점이 정해져 있다</b>설측연 후방, 구강저, 구협 — 세 곳이 호발 부위이면서 동시에 <u>대충 보면 안 보이는 곳</u>입니다. 거즈로 혀를 당기고, 혀를 들어 구강저를 양손 촉진하고, 설압자로 구협을 여는 세 동작을 절차로 고정하세요.</div>",
  },
  {
    title: "경부 림프절 촉진",
    category: "구강내과", order: 2,
    source: "Burket's Oral Medicine / Scully, Oral and Maxillofacial Medicine",
    purpose: "- 감염·염증의 파급 범위 확인\n- **악성 전이의 조기 신호** 포착",
    technique: "1. 환자를 앉히고 **술자는 뒤 또는 옆**에서 양손으로\n2. 목을 검사 측으로 **약간 기울여 근육을 이완**시킨다\n3. 손가락 끝으로 원을 그리며 순서대로 —\n   **submental → submandibular → jugulodigastric → 경정맥 사슬 → 후경부 → 쇄골상와**\n4. 좌우를 **같은 순서로 비교**\n\n- 쇄골상와는 반드시 포함한다",
    criteria: "기술 항목 4가지를 모두 —\n- **크기**(mm 또는 cm)\n- **경도**: soft / firm / rubbery / hard\n- **압통**: tender / non-tender\n- **가동성**: mobile / fixed",
    interpretation: "- **압통 있고 잘 움직이며 부드러움** = 반응성 염증 경향 — 원인 감염을 찾는다\n- **무통성·단단·고정** = 악성 전이 우려 → **즉시 의뢰**\n- **rubbery·다발성**은 림프증식성 질환에서 기술된다\n- 급성 감염 후 림프절은 **수주간 남을 수 있다** — 크기 변화 추적이 판단 기준",
    pitfalls: "<div class=\"warning\"><b>⚠️ 네 항목을 다 적지 않으면 판독 불가</b>“림프절 촉지됨”만 적으면 다음 방문에서 좋아졌는지 나빠졌는지 알 수 없습니다. <u>크기·경도·압통·가동성</u>을 반드시 함께 기록하세요.</div>",
  },
  {
    title: "점막 병소 기술 및 촉진",
    category: "구강내과", order: 3,
    source: "Neville, Oral and Maxillofacial Pathology / Burket's Oral Medicine",
    purpose: "- 병소를 **다음 사람이 재현할 수 있게** 기록\n- 감별 진단과 경과 비교의 기초 자료 확보",
    technique: "**시진 — 여섯 항목을 순서대로**\n1. **위치**(해부 명칭으로), 2. **크기**(mm, 장경×단경), 3. **개수**(단발/다발)\n4. **색**(홍반성·백색·색소성·청색), 5. **표면**(매끈·과립상·사마귀양·유두상·궤양)\n6. **경계**(명확/불명확, 융기·외번 여부)\n\n**촉진**\n- **경도**: soft / firm / rubbery / **indurated** / fluctuant\n- **기저**: 유경성 / 무경성\n- **가동성**: 하부 조직에 대해 움직이는지\n- **압통** 유무\n\n**보조 검사**\n- 거즈로 **문질러 벗겨지는지**(칸디다 감별)\n- 유리 슬라이드로 눌러 **색이 빠지는지**(혈관성 감별)\n- **사진 촬영** — 자·프로브를 함께 넣어 크기 기준을 남긴다",
    criteria: "- 여섯 항목 + 촉진 소견이 모두 기재되면 재현 가능한 기록\n- 사진에 **크기 기준**이 없으면 경과 비교가 어렵다",
    interpretation: "- **경결 + 융기 변연 + 2주 이상 지속** = 악성 우려 조합\n- **양측 대칭** = 면역매개·전신 / **편측·정중선 정지** = 신경 분포(대상포진)\n- **의치·수복물 접촉부와 일치** = 접촉성·외상성",
    pitfalls: "<div class=\"warning\"><b>⚠️ “구내염 소견”으로 끝내지 마세요</b>병소 기록의 목적은 <u>2주 뒤 같은 병소인지 판단</u>하는 것입니다. 크기와 사진 없이 기술만 남기면 그 판단이 불가능합니다.</div>",
  },
  {
    title: "타액 분비율 측정",
    category: "구강내과", order: 4,
    source: "Burket's Oral Medicine / Sjögren 진단 관련 문헌",
    purpose: "- 구강건조 **호소를 객관화**\n- 우식 위험도 판정, 의치 유지 예후, 쇼그렌 의심 시 근거 확보",
    technique: "**비자극 전타액(unstimulated whole saliva)**\n1. 최소 **1시간 금식·금연·양치 금지**, 오전 중 일정한 시간대에\n2. 앉아서 고개를 약간 숙이고 **삼키지 않고** 눈금 용기에 흘려 모은다\n3. **5분간** 수집 → 부피 ÷ 5 = mL/min\n\n**자극 전타액(stimulated)**\n- 무가향 파라핀·껌을 일정 속도로 저작하며 **5분** 수집\n\n- **측정 조건(시간대·금식·복약)을 반드시 함께 기록**",
    criteria: "- **비자극 전타액(UWS) ≤0.1 mL/min**, **자극 전타액(SWS) ≤0.7 mL/min** 을 저하 기준으로 쓰는 것이 통례\n- 참고 정상치: UWS 약 0.3–0.4, SWS 약 1.5–2.0 mL/min\n- 단 UWS 0.1 기준의 민감도가 높지 않다는 보고가 있어, **수치 하나로 단정하지 말고 증상·구강 소견과 함께** 해석한다\n- 절대값보다 **같은 조건의 재측정 추세**가 유용",
    interpretation: "- 저하가 확인되면 **우식 위험을 최고 등급**으로 잡고 불소·식이·리콜 간격을 조정\n- **호소는 있으나 분비량 정상**이면 감각 이상·점막 질환·심리 요인을 고려\n- 약물 목록과 대조해 **원인 약제**를 특정하고 협진 자료로 남긴다",
    pitfalls: "<div class=\"warning\"><b>⚠️ 조건이 다르면 비교할 수 없습니다</b>시간대·금식·복약·긴장도에 따라 값이 크게 변합니다. <u>측정 조건을 적지 않은 수치는 다음 측정과 비교되지 않습니다.</u></div>",
  },
  {
    title: "칸디다 감별 — 도찰 검사",
    category: "구강내과", order: 5,
    source: "Burket's Oral Medicine / Neville",
    purpose: "- 백색 병변이 칸디다인지 각화성 병변인지 **즉석에서** 가르기\n- 홍반형 칸디다의 확인",
    technique: "1. 거즈나 설압자로 병변을 **부드럽게 문지른다**\n2. 벗겨지는지, 벗긴 자리가 **붉고 출혈하는지** 관찰\n3. 필요 시 도말 표본·배양 의뢰\n4. **의치 조직면도 함께** 검사 — 의치가 저장소가 된다",
    criteria: "- **벗겨지고 아래가 붉음** = 위막성 칸디다 시사\n- **벗겨지지 않음** = 각화성 병변(leukoplakia·태선·마찰성 각화)\n- 홍반형은 벗길 것이 없으므로 **분포와 의치 범위 일치**로 판단",
    interpretation: "- 칸디다가 확인되면 **왜 생겼는지**를 함께 기재: 야간 착용, 위생, 부적합, 구강건조, 스테로이드 흡입기, 항생제, 당뇨, 면역\n- **원인 없이 반복**되면 전신 평가로 의뢰\n- 벗겨지지 않는 백색 병변은 **leukoplakia로 다루고 추적**한다",
    pitfalls: "<div class=\"warning\"><b>⚠️ 증식형 칸디다는 벗겨지지 않습니다</b>“안 벗겨지니 칸디다가 아니다”로 단정할 수 없습니다. 위험 인자가 뚜렷하면 <u>치료적 진단(항진균 반응)</u>이나 생검을 고려하세요.</div>",
  },

  // ═══════════ 치주 ═══════════
  {
    title: "치주 탐침 — PD · CAL · BOP",
    category: "치주", order: 1,
    source: "Newman & Carranza's Clinical Periodontology / Lindhe, Clinical Periodontology and Implant Dentistry",
    purpose: "- 치주 지지 조직의 **현재 상태와 소실량**을 정량화\n- 보철에서는 **지대치 선정·예후 판정·변연 위치 결정**의 근거\n- 초진, 재평가, 보철 전, 정기 리콜마다 시행",
    technique: "**준비**\n- 눈금 프로브(예: UNC-15, Williams). 임플란트에는 **플라스틱/전용 프로브**\n- 힘은 <mark style=\"background:#fef08a\">약 0.20–0.25 N</mark> — 손톱 밑에 대고 눌러 통증 직전 정도로 감각을 교정해 둘 것\n\n**단계**\n1. 프로브를 **치아 장축과 평행**하게 삽입 (인접부는 접촉점 하방으로 약간 경사)\n2. **Walking stroke** — 1 mm 간격으로 위아래로 움직이며 열구 바닥을 따라 이동\n3. **치아당 6점** 기록: **MB / B / DB / ML / L / DL**\n4. **PD**(치은연–열구저)와 **GR**(CEJ–치은연)을 각각 기록 → **CAL = PD + GR**\n5. 탐침 후 **10–30초** 관찰하여 **BOP** 판정 (탐침 직후가 아님)\n\n**기록 순서**를 고정하면 누락이 줄어든다 — 우측 상악 후방 → 좌측 → 하악 좌측 → 우측",
    criteria: "- **PD**: 건강 시 1–3 mm. 4 mm 이상은 주의, **≥5–6 mm는 유지관리 어려움**\n- **BOP**: 부위별 (+/−), **전악 BOP % 산출**(예: BOP 12%)\n- **CAL**: 실제 부착 소실량. **PD가 같아도 GR이 다르면 소실량이 다르다**\n- **KT width**: 치은연–MGJ 거리(mm)",
    interpretation: "- **PD ↑ + CAL ↑** = 진행된 부착 소실\n- **PD ↑ + CAL 정상** = 가성 낭(치은 비대) — 염증 조절 후 재평가\n- **PD 정상 + CAL ↑** = 퇴축 동반, 지지는 이미 소실\n- **BOP(−)** 는 안정의 **음성 예측**에 유용 — 없으면 대체로 안정. BOP(+) 하나만으로 진행을 단정하지는 못함\n- 보철 판단: 변연을 치은연하로 둘 때 **열구 깊이 + supracrestal attachment**를 함께 고려",
    pitfalls: "<div class=\"warning\"><b>⚠️ 값을 틀리게 만드는 요인</b>① <b>힘이 세면</b> 염증 조직에서 프로브가 결합조직까지 통과해 PD가 과대평가됩니다. ② <b>보철물 변연·치석에 걸려</b> 실제보다 얕게 나옵니다. ③ 프로브를 <b>경사지게</b> 넣으면 인접부가 과대평가됩니다. ④ BOP를 <b>탐침 직후 즉시</b> 보면 놓칩니다 — 10–30초 뒤에 판정하세요.</div>\n\n- 염증이 심한 상태의 계측은 **치료 후 재평가**로 확정할 것 — 초진 수치만으로 발치·지대치 결정을 하지 않는다",
  },
  {
    title: "동요도 · 근분지부 검사 (Mobility · Furcation)",
    category: "치주", order: 2,
    source: "Newman & Carranza's Clinical Periodontology / Lindhe, Clinical Periodontology and Implant Dentistry",
    purpose: "- 지지 소실의 **기능적 결과**를 평가\n- 지대치 적합성, 고정(splinting) 필요성, 예후 판정",
    technique: "**동요도 (Mobility)**\n1. **금속 기구 손잡이 2개** 사이에 치아를 두고 협설로 밀어 본다(손가락은 감각이 둔해 과소평가)\n2. 수직 동요는 기구로 교합면을 눌러 확인\n3. 인접치를 기준으로 상대 비교\n\n**근분지부 (Furcation)**\n1. **Nabers probe**(만곡형) 사용\n2. 상악 대구치는 **협측 1 · 근심구개 1 · 원심구개 1** 총 3곳, 하악 대구치는 **협측·설측** 2곳\n3. 근분지 입구를 따라 수평으로 탐침",
    criteria: "**Mobility (Miller)**\n<dl><dt>Class I</dt><dd>수평 동요 <b>&lt;1 mm</b></dd><dt>Class II</dt><dd>수평 동요 <b>&gt;1 mm</b></dd><dt>Class III</dt><dd>수평 동요 + <b>수직 함몰·회전</b></dd></dl>\n\n**Furcation (Glickman)**\n<dl><dt>Grade I</dt><dd>입구 촉지, 수평 침투 없음</dd><dt>Grade II</dt><dd>부분 침투(관통 안 됨)</dd><dt>Grade III</dt><dd><b>관통</b>되나 치은으로 덮임</dd><dt>Grade IV</dt><dd>관통 + 육안 노출</dd></dl>",
    interpretation: "- 동요는 **원인 감별이 먼저**: 부착 소실 / 교합 외상 / 급성 염증 / 근관 병소 / 최근 교정력\n- **교합 외상 단독**의 동요는 원인 제거 시 **회복 가능** — 발치 결정 전에 반드시 구분\n- **Grade III–IV 근분지부**는 위생 접근이 어려워 장기 예후가 나쁘다 → 지대치로 쓸 때 신중\n- 진행성 동요 증가는 **보철 설계 변경(고정·설계 단순화)** 의 신호",
    pitfalls: "<div class=\"warning\"><b>⚠️ 주의</b>손가락으로 흔들면 동요를 <u>과소평가</u>합니다. 반드시 기구 손잡이 두 개를 쓰세요. 또 동요도만 보고 예후를 단정하지 마세요 — 급성 염증·교합 외상에 의한 동요는 가역적입니다.</div>",
  },
  {
    title: "Bone sounding (골 탐침)",
    category: "치주", order: 3,
    source: "Newman & Carranza's Clinical Periodontology / Lindhe, Clinical Periodontology and Implant Dentistry",
    purpose: "- **치조골정의 실제 위치**를 실측\n- 치은연하 변연 설계, **치관연장술 필요량 산정**, 심미 부위 위험 예측\n- 평균값(생물학적 폭경 2.04 mm)은 개인차가 커 **반드시 실측**해야 한다",
    technique: "1. **국소마취 하** 시행(마취 없이는 정확한 값을 얻기 어렵고 통증 유발)\n2. 프로브를 열구에 넣고 **저항이 단단해질 때까지**(골정에 닿을 때까지) 수직으로 진입\n3. **예정 수복 변연 위치 → 골정** 거리를 계측\n4. **면별로 기록**: B / L / M / D\n5. 인접치의 **CEJ–골정** 거리도 함께 계측(papilla 예측)",
    criteria: "- 목표: **수복 변연 → 골정 ≥3 mm** (supracrestal attachment 약 2 mm + 열구 약 1 mm)\n- 필요 노출량 = **3 mm − 현재 계측값**\n- 인접부 **접촉점 → 골정 ≤5 mm**면 papilla가 채워질 가능성이 높다(Tarnow)",
    interpretation: "- **&lt;3 mm** → supracrestal attachment 침범 → **치관연장술 또는 교정적 정출** 적응\n- 얇은 biotype에서는 침범이 염증이 아니라 **퇴축**으로 나타난다 → 심미 부위에서 특히 위험\n- 술후 **C:R 악화**를 함께 계산할 것 — 노출량이 클수록 지지가 줄어든다",
    pitfalls: "<div class=\"danger\"><b>🚫 흔한 오류</b>마취 없이 대충 찔러 얕게 읽는 것. 그 값으로 변연을 치은연하에 두면 <u>만성 염증과 예측 불가한 퇴축</u>이 뒤따릅니다. 또 한 면만 재고 전체를 판단하지 마세요 — 대개 한 면만 부족합니다.</div>",
  },
  {
    title: "치태·치석 검사 (Plaque control record)",
    category: "치주", order: 4,
    source: "Newman & Carranza's Clinical Periodontology / O'Leary plaque control record",
    purpose: "- 위생 상태를 **수치로** 만들어 교육 효과를 추적\n- 치주·임플란트·보철 예후 판정의 기초 인자",
    technique: "1. **착색제(disclosing agent)** 를 전 치면에 도포하고 헹군다\n2. 치아당 **4면**(협·설·근심·원심)에서 변연부 치태 유무를 기록\n3. **치태 지수(%) = 착색면 수 ÷ 전체 면 수 × 100**\n4. **환자에게 거울로 직접 보여주고**, 남은 부위를 스스로 닦게 한 뒤 재확인\n\n**치석**\n- 치은연상: 건조 후 시진\n- 치은연하: 탐침 감촉 + 공기 분사 + 방사선(인접면)",
    criteria: "- 치태 지수를 **%로 기록** — “위생 불량”이라 쓰지 않는다\n- 치석은 **연상/연하**를 구분하고 부위를 특정",
    interpretation: "- **지수 자체보다 변화**가 정보다 — 교육 전후, 방문 간 비교\n- 특정 부위에 집중되면 **접근성 문제**(총생·보철 형태·손 사용) — 도구를 바꿔야 한다\n- 치태 지수가 높으면 **임플란트·복잡 보철 설계를 재고**할 근거가 된다",
    pitfalls: "<div class=\"tip\"><b>💡 착색은 교육 도구입니다</b>지수를 적는 것보다 <u>환자가 자기 입에서 남는 자리를 직접 보는 것</u>이 행동을 바꿉니다. 착색 → 자가 재칫솔질 → 재확인까지가 한 세트입니다.</div>",
  },
  {
    title: "치은 표현형 및 각화치은 폭 평가",
    category: "치주", order: 5,
    source: "2017 World Workshop / Lindhe, Clinical Periodontology and Implant Dentistry",
    purpose: "- 퇴축·회색 비침 위험을 **미리** 예측\n- 심미부 보철·임플란트 설계, 연조직 증대 필요성 판단",
    technique: "**표현형(두께)**\n- **프로브 투과법**: 치은 열구에 프로브를 넣고 **비쳐 보이면 얇은 표현형**\n- 또는 프로브·초음파로 두께 직접 계측\n\n**각화치은 폭(KT)**\n1. **MGJ 확인**: 점막을 근단측으로 밀어 올려 **움직이는 경계**를 찾는다(또는 요오드 염색)\n2. 치은연에서 MGJ까지 **mm로 계측**\n\n**부착치은 폭 = KT − 열구 깊이(PD)** — 계산해서 함께 적는다",
    criteria: "- **thin / thick** 표현형\n- **KT 폭(mm)**, **부착치은 폭(mm)**\n- 임플란트 주위는 **KT 2 mm 미만**이면 위생·염증 위험이 높다는 보고가 축적되어 있다",
    interpretation: "- **얇은 표현형** — 자극에 **퇴축**으로 반응. 심미부에서 회색 비침·변연 후퇴 위험\n- **두꺼운 표현형** — **낭 형성**으로 반응, 퇴축은 적음\n- 표현형에 따라 변연 위치·abutment 재료·연조직 증대 여부가 달라진다",
    pitfalls: "<div class=\"warning\"><b>⚠️ KT와 부착치은을 혼동하지 마세요</b>KT가 4 mm여도 낭이 3 mm면 부착치은은 1 mm뿐입니다. <u>계산해서 적지 않으면 실제 완충대를 과대평가</u>하게 됩니다.</div>",
  },

  // ═══════════ 치아·치수 ═══════════
  {
    title: "치수 생활력 검사 (Cold · EPT)",
    category: "치아·치수", order: 1,
    source: "Cohen's Pathways of the Pulp / Sturdevant's Art and Science of Operative Dentistry",
    purpose: "- 치수의 **생활력 유무**와 염증 상태(가역 vs 비가역) 판단\n- 보철 전 **근관치료 필요성**을 가르는 검사",
    technique: "**공통 원칙**\n- **반드시 대조치(control)를 먼저** 검사한다 — 반대측 동명치 또는 인접 건전치\n- 환자에게 “느낌이 오면 손을 드세요”라고 미리 설명\n- 치아를 격리·건조\n\n**한랭 검사 (Cold)**\n1. 냉매(Endo-Ice 등)를 적신 면구를 **치경부 1/3 순면**에 접촉\n2. 반응이 오면 **즉시 제거**\n3. **반응 강도**와 **자극 제거 후 지속 시간**을 함께 기록 ← 지속 시간이 핵심\n\n**전기치수검사 (EPT)**\n1. 치면 건조, 전극에 매개체(치약 등) 도포\n2. **법랑질(치경부 1/3)** 에 접촉, 금속 수복물·치은 접촉 회피\n3. 반응 수치를 대조치와 비교\n\n**보조**: 온열 검사, 선택적 마취, 와동 형성(최후 수단)",
    criteria: "- **WNL**: 자극에 반응하고 **제거 후 즉시 소실(&lt;10초)**\n- **Lingering**: 제거 후 **10초 이상 지속** → 비가역성 치수염 시사\n- **No response**: 무반응 → 괴사 가능(단독으로 확정 불가)\n- **Exaggerated**: 과민 반응",
    interpretation: "<dl><dt>가역성 치수염</dt><dd>유발 시에만 통증, 즉시 소실 → 원인 제거 후 보철 진행 가능</dd><dt>비가역성 치수염</dt><dd>지속통·자발통·야간통 → <b>보철 전 근관치료</b></dd><dt>괴사</dt><dd>무반응 + 타진통·PA 병소 동반 가능</dd></dl>\n\n- **EPT는 “생활력의 유무”만** 시사하며 염증 정도를 말해주지 않는다\n- 결과는 **항상 대조치와 함께** 해석",
    pitfalls: "<div class=\"warning\"><b>⚠️ 위음성·위양성</b>① <b>다근치</b>는 일부 치수만 괴사해도 반응이 남습니다. ② <b>완전 도재관·금속관</b>에서는 EPT가 부정확합니다. ③ <b>석회화·외상 기왕치·미성숙 치근</b>은 무반응이 정상일 수 있습니다. ④ 금속 수복물에 전극이 닿으면 인접치로 전류가 새어 <b>위양성</b>이 납니다.</div>\n\n- 무반응 하나로 근관치료를 결정하지 말고 **타진·촉진·방사선·병력**과 함께 종합할 것",
  },
  {
    title: "타진 · 촉진 (Percussion · Palpation)",
    category: "치아·치수", order: 2,
    source: "Cohen's Pathways of the Pulp / Sturdevant's Art and Science of Operative Dentistry",
    purpose: "- **치주인대·치근단 조직의 염증** 유무 확인\n- 치수 검사와 조합해 치근단 병소를 감별",
    technique: "**타진 (Percussion)**\n1. **손가락으로 먼저** 가볍게 두드려 본다(민감한 환자에서 과반응 방지)\n2. 이어서 **기구 손잡이 끝**으로 교합면과 협면을 가볍게 타진\n3. **대조치를 먼저** 두드려 기준을 만든 뒤 의심치를 검사\n4. 수직·수평 타진을 구분 — 수평 타진통은 **치주 기원**을 시사\n\n**촉진 (Palpation)**\n1. 검지 끝으로 **치근단 대응 부위 점막**을 눌러 본다\n2. 협측·설측 모두, 좌우 대칭 비교\n3. 부종·파동감·경결 유무 확인",
    criteria: "- **Perc (+/−)**, 정도(mild / moderate / severe)\n- **Palp (+/−)**, 부종·파동감 유무\n- 반드시 **대조치와 비교**하여 기록",
    interpretation: "- **Perc(+)** = 치주인대 염증 — 치근단 병소 / 교합 외상 / 최근 처치 / 치주 농양 / 균열\n- **Palp(+)** = 염증이 **피질골을 넘어 연조직까지** 확장\n- **Perc(+) + Cold 무반응** → 치수 괴사 + 치근단 염증 가능성\n- **Perc(+) + Cold 정상** → 교합 외상 또는 균열을 먼저 의심",
    pitfalls: "<div class=\"warning\"><b>⚠️ 주의</b>세게 두드리면 건전치도 아픕니다. 반드시 <u>대조치부터, 약하게</u> 시작하세요. 또 최근 교합 조정·보철 장착 직후에는 일과성 타진통이 흔하므로 병력과 함께 해석해야 합니다.</div>",
  },
  {
    title: "균열치 · 수직치근파절 검사 (Crack · VRF)",
    category: "치아·치수", order: 3,
    source: "Cohen's Pathways of the Pulp / Sturdevant's Art and Science of Operative Dentistry",
    purpose: "- **보철 예후를 통째로 뒤집는** 병소를 조기에 배제\n- 지각과민·설명되지 않는 저작통의 감별\n- **수복 가능 여부(VRF = 발치)** 판정",
    technique: "**균열치 (Cracked tooth)**\n1. **Bite test** — Tooth Slooth / FracFinder 등을 **교두별로 하나씩** 물게 한다\n   - 무는 순간보다 **이완하는 순간의 통증(rebound)** 이 특징적\n2. **투조(transillumination)** — 광섬유 광원을 협측에 대고 균열선에서 빛이 끊기는지 관찰\n3. **염색(methylene blue 등)** — 기존 수복물 제거 후 적용\n4. 수복물·우식 제거 후 **와동 내부를 확대 하 직접 관찰**\n\n**수직치근파절 (VRF)**\n1. **치주 탐침** — 고립성·좁고 깊은 낭(narrow isolated deep pocket)\n2. **방사선** — J형/후광(halo) 투과상, 파절선\n3. **Sinus tract 위치** — 치은변연 가까이 열리면 VRF 시사\n4. 필요 시 **CBCT**, 판막 거상 후 직접 관찰",
    criteria: "- **Bite test (+)**: 특정 교두에서 재현되는 예리한 통증\n- **고립성 좁고 깊은 포켓**: 주위는 정상인데 한 지점만 깊음\n- **J-shaped radiolucency**: 치근 측면을 따라 치근단까지 이어지는 투과상",
    interpretation: "<dl><dt>Craze line</dt><dd>법랑질 내, 무증상 → 경과 관찰</dd><dt>Cracked tooth</dt><dd>상아질까지, 저작 시 증상 → 교두 피개 수복(onlay·crown)으로 예후 개선 가능</dd><dt>Split tooth</dt><dd>완전 분리 → 분리편 제거 또는 발치</dd><dt>VRF</dt><dd><b>수복 불가 — 발치</b>(또는 치근 절제)</dd></dl>",
    pitfalls: "<div class=\"danger\"><b>🚫 놓치면 가장 손해가 큰 검사</b>균열을 모른 채 크라운을 만들면, 몇 달 뒤 <u>수복물은 멀쩡한데 치아가 갈라져</u> 발치로 끝납니다. 그때는 임플란트 예후(골 소실)까지 나빠져 있습니다. “설명되지 않는 저작통”이 있으면 보철을 시작하기 전에 반드시 배제하세요.</div>\n\n- 투조·염색은 **위음성**이 흔하다 — 음성이어도 임상 증상이 전형적이면 재평가",
  },
  {
    title: "우식 검사",
    category: "치아·치수", order: 4,
    source: "Sturdevant's Art and Science of Operative Dentistry / ICDAS",
    purpose: "- 우식의 **유무·범위·활동성**을 판정\n- 수복 여부와 시급성 결정",
    technique: "1. **치면 청결·건조** — 젖은 상태에서는 초기 병소가 보이지 않는다\n2. **시진**: 색·투명도·표면 파괴 여부. 확대 하에\n3. **탐침**: 날카로운 탐침으로 **찔러 넣지 않는다** — 초기 병소를 파괴한다. 둥근 탐침으로 **표면 질감**을 본다\n4. **투조**: 전치 인접면\n5. **방사선(bitewing)**: 구치 인접면 — 임상으로 보이지 않는 병소\n6. **활동성 판정**: 표면 질감·색·광택·치태 정체 여부",
    criteria: "- 부위·면·깊이를 기록(ICDAS 또는 D1–D3)\n- **활동성**: 무르고 밝은 갈색·습윤·치태 정체 = 활성 / **단단하고 검고 광택** = 정지\n- 방사선 병소는 **실제보다 작게 보인다**는 점을 감안",
    interpretation: "- **정지성 병소는 삭제하지 않는다** — 관찰·재광화가 원칙\n- 신규 병소 수와 위치는 **우식 위험도 판정**의 핵심 입력값\n- 다발·비전형 부위(치경부·절단연)면 **타액·식이·약물**을 평가",
    pitfalls: "<div class=\"danger\"><b>🚫 탐침으로 찌르지 마세요</b>초기 탈회 병소는 재광화될 수 있는데, 날카로운 탐침으로 찌르면 <u>표면을 무너뜨려 되돌릴 수 없는 와동</u>을 만듭니다. “걸리는지” 확인하려는 습관이 병소를 만듭니다.</div>",
  },
  {
    title: "지각과민 부위 특정",
    category: "치아·치수", order: 5,
    source: "Burket's Oral Medicine / 상아질 지각과민 임상 문헌",
    purpose: "- 환자가 모호하게 호소하는 시림의 **원인 치아·부위를 특정**\n- 치수 병변·균열과 감별",
    technique: "1. **격리**: 인접치를 코튼롤로 막아 자극이 번지지 않게\n2. **에어 시험**: 3-way 시린지로 **1초, 치면에서 약 1 cm** 거리에서 치경부를 따라 이동하며 반응 부위를 찾는다\n3. **한랭 시험**으로 재현하고 **지속 시간**을 잰다\n4. 반응 부위의 **노출 상아질·결손·퇴축**을 확인\n5. **교합 검사** 병행 — 편심 간섭이 치경부 응력에 기여할 수 있다",
    criteria: "- 부위가 **재현 가능하게** 특정되어야 한다\n- 자극 제거 후 **즉시 소실(&lt;10초)** 이면 지각과민 범주\n- 대조 부위와 비교",
    interpretation: "- **수 초 이상 지속** → 비가역성 치수염 배제 필요\n- **저작 시 예리한 통증 + 이완통** → 균열치 배제 필요\n- 부위가 특정되지 않고 광범위하면 **치수 기원·비치성 통증**을 고려",
    pitfalls: "<div class=\"warning\"><b>⚠️ 격리하지 않으면 부위를 못 찾습니다</b>에어가 인접치까지 닿아 환자가 “이쯤”이라고만 답하게 됩니다. <u>한 치아씩 격리해서 재현</u>해야 원인 치아가 확정됩니다.</div>",
  },

  // ═══════════ 교합 ═══════════
  {
    title: "중심위 유도 및 CR–MIP 편위 계측",
    category: "교합", order: 1,
    source: "Dawson, Functional Occlusion / Okeson, Management of TMD and Occlusion",
    purpose: "- **재현 가능한 기준 악위(CR)** 를 확보\n- 전악 수복·VDO 변경·MIP 불안정 시 **모든 기록의 출발점**\n- CR과 MIP의 **차이(slide)** 를 정량화",
    technique: "**유도 전 — 근육 이완(deprogramming)**\n- 면봉·leaf gauge·전방 deprogrammer를 **5–10분 이상** 물려 습관성 폐구로를 지운다\n- 근육 증상이 심하면 스플린트로 **수일–수주** 이완 후 재시도\n\n**Bimanual manipulation (Dawson)**\n1. 환자를 앙와위로, 술자는 머리 위쪽에 위치\n2. 네 손가락은 하악 하연, **양 엄지는 이부(chin)** 에 위치\n3. 하악을 **가볍게** 상방·전방으로 유도하며 호(arc)를 그리게 한다 — **힘을 주지 않는 것이 핵심**\n4. 저항 없이 반복 재현되는 위치에서 **아주 얇게** 접촉시킨다\n\n**Gothic arch tracing** — 가장 객관적\n1. 상하 record base에 tracing plate와 stylus 장착\n2. 전방·측방 운동을 시켜 화살촉(arrow point) 형태를 그리게 한다\n3. **apex**가 CR — 재현성을 눈으로 확인할 수 있다\n\n**기록**: 왁스 / ZOE / PVS bite registration — 경화 중 **base가 들리지 않게** 확인",
    criteria: "- **재현성**: 서로 다른 시점에 **3회 반복해 일치**해야 채택\n- **CR–MIP slide**: 방향(전방·측방)과 양(mm)을 기록\n- 편위가 **없거나 매우 작으면** CR ≈ MIP",
    interpretation: "- **안정된 MIP + 국소 수복** → MIP 기록으로 충분\n- **전악 수복 / VDO 변경 / 후방 지지 상실 / MIP 불안정** → CR 기록 필수\n- 큰 slide는 교합 재구성 시 **수복 공간과 전방유도 설계**에 직접 영향",
    pitfalls: "<div class=\"warning\"><b>⚠️ 이 단계의 오차는 복구되지 않습니다</b>① <b>힘을 주어 밀면</b> 하악이 후방으로 밀린 위치가 기록됩니다. ② <b>근육 이완 없이</b> 유도하면 습관성 위치가 CR로 둔갑합니다. ③ record base가 불안정하면 <b>이후 모든 기록이 무효</b>입니다. 재현되지 않으면 그날은 기록하지 말고 원인을 해결하세요.</div>",
  },
  {
    title: "교합 접촉 검사 (교합지 · shimstock)",
    category: "교합", order: 2,
    source: "Dawson, Functional Occlusion / Okeson, Management of TMD and Occlusion",
    purpose: "- 접촉의 **위치·강도·동시성**을 확인\n- 보철물 장착·조정, 정기 리콜에서 **과부하 부위**를 특정",
    technique: "**준비**\n- 치면을 **건조**시킨다(젖으면 마킹이 번져 위양성)\n- 교합지는 **얇을수록 정확**(12–40 μm). 두꺼운 종이는 접촉을 과대 표시\n\n**단계**\n1. **색을 구분**해 사용 — 예: 흑/청 = **CO(중심교합)**, 적 = **편심운동**\n2. CO: 가볍게 두드리게(tapping) 한 뒤 마킹 확인 → 이어서 강하게\n3. 편심: 측방·전방으로 활주시켜 다른 색으로 마킹\n4. **Shimstock (8 μm)** — 접촉 강도의 정량 확인\n   - 물었을 때 **잡히면 접촉(+)**, 빠지면 무접촉\n   - 인접 자연치와 **동시에 잡히는지** 비교\n\n**임플란트**: 경교합에서 shimstock이 **빠지고**, 강교합에서 **잡히도록** 조정",
    criteria: "- **CO**: 양측 **동시·균등** 접촉, 자연치와 함께 잡힘\n- **편심**: 선택한 유도양식대로. 비작업측(balancing) 간섭은 원칙적으로 제거\n- **High spot**: 유독 진하게·크게 찍히는 부위",
    interpretation: "- 새 보철물이 **혼자 먼저 닿으면** 과부하 → 통증·파절·나사 풀림·변연골 소실\n- **자연치는 마모·이동하지만 임플란트는 그대로** → 리콜마다 상대적 고접촉이 새로 생긴다\n- 조정은 **접착 전에 대부분 완료**하고, 접착 후에는 미세 조정만",
    pitfalls: "<div class=\"warning\"><b>⚠️ 마킹을 믿기 전에</b>① 치면이 <b>젖어 있으면</b> 번져서 없는 접촉이 찍힙니다. ② 교합지가 <b>두꺼우면</b> 과대 표시됩니다. ③ 마취 상태에서는 환자의 “높다” 감각이 신뢰할 수 없으므로 <b>마킹과 shimstock에 의존</b>하세요. ④ 조정 후 <b>반드시 재연마</b> — 거친 면은 대합치를 마모시킵니다.</div>",
  },
  {
    title: "수직고경 계측 (VDO · VDR · FWS)",
    category: "교합", order: 3,
    source: "Dawson, Functional Occlusion / Okeson, Management of TMD and Occlusion",
    purpose: "- 교합 높이의 **적절성**을 판정\n- 총의치·국소의치 제작, **교합 재구성 시 VDO 변경량** 결정",
    technique: "**기준점 표시**\n- 비저(subnasale)와 이부(soft tissue menton) 등 **재현 가능한 두 점**에 표식을 찍는다\n\n**VDR (안정위, rest)**\n1. 환자를 **직립·이완** 상태로 앉힌다\n2. 반복 연하 후 힘을 빼게 하고, “m” 음을 발음시킨 뒤 자연스럽게 멈추게 한다\n3. 두 점 간 거리를 계측 (캘리퍼·자)\n\n**VDO (교합위)**\n- 교합 상태(또는 occlusion rim 접촉)에서 같은 두 점을 계측\n\n**FWS = VDR − VDO**\n\n**보조 판정**\n- **발음**: “S” 발음 시 상하 절치 최근접 거리(**closest speaking space** 약 1–2 mm)\n- **연하**, 안모 비율, 구순 폐쇄의 편안함\n- 기존 의치·발치 전 사진·모형과 비교",
    criteria: "- **FWS 2–4 mm**가 통상 목표\n- 안모 비율 조화, 구각 처짐 없음, 입술이 편안히 다물어짐\n- “S” 발음 시 접촉·휘슬음 없음",
    interpretation: "- **VDO 과대**(FWS 소실): 저작통·구각 긴장·clicking·**치조제 흡수 가속**\n- **VDO 과소**: 안모 함몰·구각염·저작 효율 저하\n- **핵심 감별** — 치아가 마모되어도 **치조 보상성 정출(dentoalveolar compensation)** 로 VDO가 유지되는 경우가 많다. 따라서 **마모량 ≠ VDO 감소량**. 마모량만큼 올리면 과대 VDO가 된다",
    pitfalls: "<div class=\"danger\"><b>🚫 가장 흔한 계산 착오</b>“닳은 만큼 올리면 된다”. 대부분의 마모 증례에서 VDO는 이미 보상되어 유지되고 있습니다. <u>FWS·발음·안모</u>로 검증하고, 공간이 부족하면 VDO만이 아니라 <b>교정·치관연장술·Dahl 개념</b>을 함께 저울질하세요. 그리고 VDO 변경은 반드시 <b>가역적 장치로 4–8주 검증</b> 후 최종에 옮깁니다.</div>\n\n- 안정위는 자세·긴장·시간대에 따라 변동한다 → **여러 번 반복 계측**",
  },
  {
    title: "편심 운동 검사 (Excursive movements)",
    category: "교합", order: 4,
    source: "Dawson, Functional Occlusion / Okeson, Management of TMD and Occlusion",
    purpose: "- **유도양식**을 파악하고 **간섭**을 특정\n- 보철물 파절·나사 풀림·근육 증상의 기계적 원인 규명",
    technique: "1. **측방 운동** — 환자에게 이를 맞댄 채 좌·우로 천천히 활주하게 한다\n   - **작업측(working)**: 이동 방향 쪽\n   - **비작업측(non-working / balancing)**: 반대쪽\n2. **전방 운동** — 절단연이 맞닿을 때까지 앞으로 활주\n3. 각 운동에서 **어느 치아가 닿는지** 교합지(편심용 색)로 마킹\n4. 필요 시 **활주 거리**(측방 R/L, 전방 mm) 계측",
    criteria: "<dl><dt>Canine guidance</dt><dd>측방 시 <b>견치만</b> 접촉, 구치 즉시 이개</dd><dt>Group function</dt><dd>작업측 <b>여러 치아</b>가 함께 유도</dd><dt>Balancing interference</dt><dd>비작업측 접촉 — <b>원칙적으로 제거</b></dd><dt>Protrusive interference</dt><dd>전방 운동 시 구치 접촉</dd></dl>\n\n- 총의치의 **균형교합**은 예외 — 비작업측 접촉이 오히려 안정에 기여",
    interpretation: "- **비작업측 간섭**은 지렛대 응력을 만들어 보철물·임플란트에 특히 불리\n- 전방유도가 없으면 구치가 편심에서 계속 부딪혀 마모·파절이 누적\n- 임플란트 보철은 **편심에서 접촉하지 않도록** 하는 것이 통례(합의 수준)",
    pitfalls: "<div class=\"warning\"><b>⚠️ 검사 조건</b>환자가 <u>빠르게 갈면</u> 마킹이 번져 간섭을 특정할 수 없습니다. 천천히, 이를 맞댄 채 활주시키세요. 또 <b>마취 하에서는</b> 고유수용 감각이 둔해 정확한 편심 운동이 어렵습니다 — 최종 편심 조정은 마취가 풀린 뒤가 낫습니다.</div>",
  },
  {
    title: "Fremitus 검사",
    category: "교합", order: 5,
    source: "Newman & Carranza's Clinical Periodontology / Dawson, Functional Occlusion",
    purpose: "- 기능 시 **실제로 과부하를 받는 치아**를 특정\n- 교합 조정 대상 선정, 교합 외상 판정",
    technique: "1. 검지 지문면을 치아 **순·협면 치경부**에 가볍게 댄다\n2. 환자에게 **가볍게 두드리게(tapping)** 한 뒤 이어서 **강하게** 물게 한다\n3. 이어서 **측방·전방 활주**를 시키며 진동을 느낀다\n4. 치아별로 좌우 비교해 기록\n\n- 눌러서 흔드는 것이 아니라 **환자 스스로 씹을 때** 느껴지는 진동을 본다",
    criteria: "- 진동 감지 여부를 치아별로 (+/−)\n- 강도가 다르면 정도를 함께 기술",
    interpretation: "- **fremitus(+) = 그 치아에 기능적 과부하**가 실제로 걸리고 있다는 직접 증거\n- 교합지 마킹은 “닿는다”만 알려주지만, fremitus는 **힘이 걸리는지**를 알려준다\n- 동요·치주인대강 확대와 함께 있으면 **교합 외상** 판정의 근거",
    pitfalls: "<div class=\"tip\"><b>💡 교합지보다 정직한 소견</b>진하게 찍혔다고 힘이 큰 것은 아닙니다(습기·종이 두께로 번집니다). <u>전치부 과부하 판정에는 fremitus가 특히 유용</u>합니다.</div>",
  },
  {
    title: "마모면 평가 및 활성도 판정",
    category: "교합", order: 6,
    source: "Dawson, Functional Occlusion / Tooth wear 평가 문헌",
    purpose: "- 마모의 **원인과 진행 여부**를 판정\n- 교합 재구성 필요성·시기 결정",
    technique: "1. **분포 기록**: 치아별·면별, 상하악 대응 관계\n2. **대합 일치 확인** — 마모면끼리 맞물리는지 폐구시켜 본다\n3. **표면 관찰**: 광택 유무, 질감\n4. **양상 감별**: 평탄 facet(교모) / cupping·구개면 함몰(침식) / 치경부 쐐기(마모)\n5. **수복물 높이 비교** — 주위 치질보다 솟아 보이는지\n6. **기록 보존**: 규격 사진 + **진단 모형 보관**(추적의 기준)",
    criteria: "- 정도: 법랑질 내 / 상아질 노출 / 치수 근접 / 치관 높이 감소(mm)\n- **활성도**: 광택 없고 부드러움 = 활성 / 착색·광택 = 정지 경향\n- 이전 모형·사진과 비교했는지 명시",
    interpretation: "- **수복물이 솟아 보이면 침식**이 강하게 시사된다(레진·아말감은 산에 녹지 않는다)\n- **활성이면 원인 조절이 먼저** — 조절 없이 수복하면 같은 자리에서 반복 실패\n- **마모량 ≠ VDO 감소량** — 치조 보상성 정출로 VDO가 유지된 경우가 많다",
    pitfalls: "<div class=\"danger\"><b>🚫 활성도 판정 없이 재구성하지 마세요</b>진행 중인 침식·이갈이를 놔둔 채 전악을 수복하면 몇 년 안에 같은 양상으로 무너집니다. <u>원인 조절 → 활성도 재평가 → 재구성</u> 순서를 지키세요.</div>",
  },

  // ═══════════ 악관절·근육 ═══════════
  {
    title: "개구량 · 하악 운동 계측",
    category: "악관절·근육", order: 1,
    source: "Okeson, Management of TMD and Occlusion / DC/TMD (Schiffman)",
    purpose: "- 하악 기능의 **정량 지표** 확보\n- TMD 진단·경과 추적, 치료 전후 비교",
    technique: "1. **최대 무통 개구(pain-free opening)** — 아프지 않은 범위까지 벌리게 하여 계측\n2. **최대 개구(maximum opening)** — 통증을 감수하고 최대로. 상하 중절치 **절단연 간 거리**를 자로 계측\n3. **Overbite를 더할지** 여부를 정해 일관되게 기록(더하면 실제 하악 회전량에 가깝다)\n4. **측방 운동** — 상하 정중선을 기준으로 좌·우 이동량\n5. **전방 운동** — 절치 전방 이동량\n6. **개구로 관찰** — 정면에서 정중선의 궤적을 본다",
    criteria: "- **최대 개구 40–55 mm**가 통상 범위, **&lt;40 mm는 제한(restricted)**\n- **측방 각 8 mm 이상**, **전방 8 mm 이상**이 통상 기준\n- **Deviation**: 개구 중 편위했다가 **정중선으로 복귀**\n- **Deflection**: 편위한 채 **복귀하지 않음**",
    interpretation: "- **Deviation** → 대개 **디스크 변위(정복성)** — 개구 중 정복되며 돌아온다\n- **Deflection** → **비정복성 디스크 변위·유착·강직** 쪽을 시사(편향된 쪽에 제한)\n- 급성 개구 제한 + deflection = **closed lock** 가능성\n- 수치는 **치료 경과 추적의 기준** — 매 방문 동일 방법으로 계측",
    pitfalls: "<div class=\"warning\"><b>⚠️ 기록의 일관성</b>overbite 포함 여부, 무통/최대 구분을 정해 두지 않으면 <u>다음 방문의 수치와 비교할 수 없습니다</u>. 측정 방법을 차트에 명시하세요.</div>",
  },
  {
    title: "관절음 · 관절 촉진",
    category: "악관절·근육", order: 2,
    source: "Okeson, Management of TMD and Occlusion / DC/TMD (Schiffman)",
    purpose: "- 관절 내 장애(디스크 변위·퇴행성 변화)의 **임상 징후** 확인",
    technique: "**촉진**\n1. 검지를 **이주(tragus) 전방**의 외측극(lateral pole)에 두고 개폐구시킨다\n2. 새끼손가락을 외이도에 넣어 **후방(posterior)** 을 촉진하는 방법도 병용\n3. **압통(tenderness)** 을 좌우 비교\n\n**관절음**\n1. 손가락 촉진 또는 청진기로 확인\n2. **어느 시점**에 나는지 기록 — 개구 초기/중기/말기, 폐구 시\n3. **상호성(reciprocal) click** 여부 — 개구·폐구 양쪽에서 발생\n4. **Crepitus**(자갈 갈리는 소리)와 구분",
    criteria: "- **Click**: 짧고 뚜렷한 소리 — 디스크 변위 시사\n- **Reciprocal click**: 개구 시 + 폐구 시 → **정복성 디스크 변위** 전형\n- **Crepitus**: 거친 마찰음 → **퇴행성 관절 변화** 시사\n- 압통 (+/−), 좌/우 기재",
    interpretation: "- **무증상 click은 흔하며 그 자체로 치료 대상이 아니다** — 통증·기능 제한 동반 여부가 판단 기준\n- Crepitus는 골 변화를 시사하므로 경과 관찰·필요 시 영상\n- **보철 전 확인 의미**: 관절이 불안정하면 **CR 기록의 재현성이 떨어지고**, 재구성 후 증상이 악화될 수 있다 → 안정화 후 진행",
    pitfalls: "<div class=\"warning\"><b>⚠️ 과잉 해석 주의</b>관절음만으로 진단명을 붙이지 마세요. 통증·개구 제한·기능 장애가 없다면 <u>경과 관찰</u>이 원칙이며, 소리를 없애기 위한 비가역적 교합 치료는 정당화되지 않습니다.</div>",
  },
  {
    title: "저작근 촉진",
    category: "악관절·근육", order: 3,
    source: "Okeson, Management of TMD and Occlusion / DC/TMD (Schiffman)",
    purpose: "- **근육성 통증(근막통)** 의 부위와 범위를 특정\n- TMD에서 근육 기원과 관절 기원을 감별",
    technique: "1. **일정한 압력**(약 1 kg, 손가락 끝이 하얗게 되는 정도)으로 **2초간** 누른다\n2. **좌우 동시 또는 연속 비교**\n3. 대상 근육을 순서대로 —\n   - **교근(masseter)**: 천부·심부, 이를 악물게 해 위치 확인\n   - **측두근(temporalis)**: 전방·중앙·후방 세 부위로 나누어\n   - **내측익돌근**: 하악각 내면\n   - **외측익돌근 부위**: 접근이 어려워 기능 검사로 대체하는 경우가 많음\n   - **흉쇄유돌근·후경부근**: 연관통 감별\n4. 반응을 물어본다 — “아픈가요” 뿐 아니라 **“다른 곳으로 퍼지나요”**",
    criteria: "- **Tender (+/−)**, 정도(mild / moderate / severe), 좌/우\n- **Referred pain (+/−)** — 압박 부위를 넘어 다른 부위로 퍼지는 통증\n- **NT (non-tender)** = 압통 없음",
    interpretation: "- 여러 근육에 광범위한 압통 → **근막통(myalgia)** 우세\n- **연관통**은 치통으로 오인되기 쉽다 — 특히 측두근·교근의 연관통이 **상·하악 구치 통증**으로 나타난다\n- 근육 증상이 활발한 상태에서는 **CR 유도·교합 기록의 재현성이 낮다** → 이완 후 기록",
    pitfalls: "<div class=\"danger\"><b>🚫 치통으로 오인</b>근육 연관통을 치성 통증으로 진단해 <u>불필요한 근관치료·발치</u>가 이루어지는 일이 드물지 않습니다. 치수 검사가 정상인데 통증이 지속되면 반드시 근육 촉진을 하세요.</div>\n\n- 압력이 사람마다·회차마다 다르면 비교가 무의미 → **일정한 힘**을 의식적으로 유지",
  },
  {
    title: "관절 부하 검사 (Joint loading)",
    category: "악관절·근육", order: 4,
    source: "Dawson, Functional Occlusion / Okeson, Management of TMD",
    purpose: "- 통증의 기원이 **관절 내부**인지 감별\n- 중심위 기록 전에 관절이 부하를 견딜 수 있는지 확인",
    technique: "1. 환자를 앙와위로, **bimanual manipulation** 자세를 잡는다\n2. 하악을 중심위 호(arc)로 유도한 상태에서 **점진적으로 부하**를 가한다\n3. 통증 유발 여부와 **familiar pain 재현** 여부를 확인\n4. 좌우를 나누어 평가",
    criteria: "- 부하 시 **무통** = 관절이 부하를 견딤 → CR 기록 가능\n- 부하 시 **familiar pain 재현** = 관절 내 병태 시사",
    interpretation: "- **부하 검사 양성이면 CR 기록의 재현성이 떨어진다** — 통증 회피로 하악이 다른 위치를 취한다\n- 이 상태에서 채득한 기록으로 교합 재구성을 하면 **관절이 안정된 뒤 교합이 어긋난다**\n- 안정화(스플린트·자가 관리) 후 재평가하는 것이 원칙",
    pitfalls: "<div class=\"warning\"><b>⚠️ 힘을 주어 밀지 마세요</b>부하는 <u>점진적으로, 가볍게</u> 가합니다. 억지로 밀면 정상 관절에서도 통증이 생겨 위양성이 되고, 하악이 후방으로 밀린 위치가 기록됩니다.</div>",
  },

  // ═══════════ 보철 적합 ═══════════
  {
    title: "변연 · 내면 적합 검사",
    category: "보철 적합", order: 1,
    source: "Rosenstiel, Contemporary Fixed Prosthodontics / Shillingburg, Fundamentals of Fixed Prosthodontics",
    purpose: "- 보철물의 **완전 안착**과 변연 밀폐를 확인\n- 시적·장착 단계에서 다음 단계 진행 가부를 결정",
    technique: "**변연 적합**\n1. **Explorer**로 변연을 한 바퀴 추적 — 걸림(catch)·단차 확인\n2. **확대(루페·현미경)** 하에 육안 확인\n3. **방사선(PA)** — 인접면 변연과 안착 여부. 협설 변연은 방사선으로 보이지 않음에 주의\n\n**내면 적합**\n1. **Fit-checker / 실리콘 박막**을 내면에 도포 후 안착\n2. 얇아지거나 뚫린 부위 = **조기접촉점** → **선택적으로만** 삭제\n3. 반복하여 접촉이 고르게 분포할 때까지\n\n**Rocking / tipping**\n- 교대로 눌러 흔들림 확인. 흔들리면 안착되지 않은 것\n\n**미안착 시 감별 순서**: ① **인접 접촉 과다** → ② **변연** → ③ **내면**",
    criteria: "- **Complete seating**: explorer 걸림 없음, rocking 없음, 방사선상 gap 없음\n- 임상 허용 변연 간극은 고전적으로 <mark style=\"background:#fef08a\">&lt;120 μm</mark>(McLean & von Fraunhofer). 현대 CAD/CAM in-vitro 목표는 더 엄격(≤75–100 μm)",
    interpretation: "- 간극이 클수록 **시멘트 용해·미세누출·치태 축적·이차우식** 위험 증가\n- 다수 연결 보철(FPD·임플란트)에서 안착 실패 = **전체 부정합** → 절단 후 재연결이 정답\n- 임플란트는 **육안·촉진만으로 판단하지 말고 반드시 방사선 확인**",
    pitfalls: "<div class=\"danger\"><b>🚫 “시멘트로 채우면 되겠지”는 없습니다</b>완전 안착되지 않은 보철물은 <u>교합·인접 접촉·변연</u>이 동시에 틀어지고 시멘트 층이 두꺼워집니다. 원인을 찾을 때까지 다음 단계로 넘어가지 마세요. 억지로 밀어 넣는 것은 응력만 남깁니다.</div>",
  },
  {
    title: "인접 접촉 검사 (Proximal contact)",
    category: "보철 적합", order: 2,
    source: "Rosenstiel, Contemporary Fixed Prosthodontics / Shillingburg, Fundamentals of Fixed Prosthodontics",
    purpose: "- 접촉의 **유무·강도·위치**를 확인\n- 식편압입·치아 이동·치주 문제 예방",
    technique: "1. **치실(floss)** 통과 — 저항 후 “snap”하며 통과하는지\n   - 저항 없이 쑥 들어감 = **open contact**\n   - 통과 불가·찢어짐 = **과다 접촉**\n2. **Shimstock (8 μm)** — 넣고 빼며 저항 확인\n3. **접촉 위치** 확인 — 교합측 1/3, 협설 중앙이 통상\n4. 조정 후 **재연마** 필수",
    criteria: "- 치실이 **저항 후 통과**\n- 접촉 면적은 점(point)보다 **면(broad)** 이 안정적\n- 인접치 사이 embrasure가 **위생 도구가 통과할 만큼** 열려 있을 것",
    interpretation: "- **Open contact** → 식편압입 → 치주 파괴·우식·불편. 임플란트 보철에서는 **인접 자연치의 근심 이동**으로 시간이 지나 새로 생긴다\n- **과다 접촉** → 완전 안착 방해, 인접치 압박·통증\n- 리콜에서 접촉 상실이 확인되면 **보철물 수정으로 회복**해야 한다",
    pitfalls: "<div class=\"warning\"><b>⚠️ 시간에 따라 변한다</b>임플란트 보철의 인접 접촉 상실은 <u>드물지 않은 현상</u>입니다. 장착 시 정상이었어도 리콜마다 다시 확인하세요. “음식이 낀다”는 호소는 접촉 상실의 가장 이른 신호입니다.</div>",
  },
  {
    title: "의치 적합 검사 (PIP · Disclosing wax)",
    category: "보철 적합", order: 3,
    source: "Rosenstiel, Contemporary Fixed Prosthodontics / Shillingburg, Fundamentals of Fixed Prosthodontics",
    purpose: "- 의치 **조직면의 과압박점**과 **변연 과신장**을 각각 특정\n- 궤양·통증의 원인을 조직면/변연/교합으로 분리",
    technique: "**PIP (pressure indicating paste) — 조직면**\n1. 의치 **조직면을 건조**시키고 PIP를 **한 방향으로 얇게** 도포(줄무늬가 남게)\n2. 장착 후 가볍게 물게 하거나 손가락 압력으로 안착\n3. 제거 후 **paste가 밀려나 바닥이 드러난 부위** = 과압박점\n4. 해당 부위만 **선택 삭제** → 재도포하여 반복\n\n**Disclosing wax — 변연**\n1. 의치 **변연부**에 왁스를 얇게 올린다\n2. 장착 후 **기능 운동**(입술·볼·혀·연하)을 시킨다\n3. 왁스가 **밀려나거나 사라진 부위** = 과신장 → 단축\n4. 왁스가 그대로 두껍게 남으면 **과소 신장** 가능성\n\n**순서**: 조직면(PIP) → 변연(wax) → **교합**",
    criteria: "- 과압박점 소실, 장착 시 **blanching(창백해짐) 없음**\n- 변연이 기능 운동 시 조직을 밀지 않음\n- 완화 부위(**mylohyoid ridge, mental foramen, midpalatine raphe, incisive papilla**)에 압박 없음",
    interpretation: "- **조직면 과압박** → 치조제 정상부 궤양\n- **변연 과신장** → 변연부 **선상 궤양**\n- 그러나 **교합 조기접촉**도 같은 부위에 궤양을 만든다 → 조직면을 깎기 전에 **항상 교합을 먼저 확인**",
    pitfalls: "<div class=\"danger\"><b>🚫 가장 흔한 오진</b>궤양이 보이면 반사적으로 그 부위 조직면을 깎는 것. 원인이 <u>교합</u>이면 아무리 깎아도 재발하고 의치만 얇아집니다. 또 같은 부위를 <b>3회 이상 조정</b>했다면 의치 자체(적합·교합·설계)를 재평가하세요.</div>",
  },
  {
    title: "임시보철 평가",
    category: "보철 적합", order: 4,
    source: "Rosenstiel, Contemporary Fixed Prosthodontics / Shillingburg",
    purpose: "- 임시보철은 **최종 보철의 리허설**이므로, 여기서 통과하지 못한 것은 최종에서도 통과하지 못한다\n- 치은 건강 유지와 정밀인상의 전제 조건 확보",
    technique: "**6요건을 순서대로 확인**\n1. **변연 적합** — explorer로 전 둘레 추적, overhang/underhang\n2. **인접 접촉** — floss snap, open contact 여부\n3. **교합** — CO 균등, 편심 간섭\n4. **축면 형태·emergence** — 과·과소 풍융, 위생 접근성\n5. **표면 활택** — 연마 상태(치태 정체 여부)\n6. **심미·발음** — 전치부에서 shade·길이·F/V·S\n\n- 접착: **비유게놀 임시시멘트**(최종이 레진 접착일 때), 잉여 제거·치실 통과 확인",
    criteria: "- 6요건 모두 acceptable\n- 치은 발적·부종·BOP 없음\n- 장기 임시면 **진단 목적(VDO·유도·예후 관찰)** 을 명시",
    interpretation: "- **치은에 염증이 있으면 인상을 진행하지 않는다** — 압배·인상·접착이 연쇄 실패한다\n- 임시에서 발음·심미가 안 되면 **최종 설계를 바꿔야 한다**는 신호",
    pitfalls: "<div class=\"danger\"><b>🚫 연마를 건너뛰지 마세요</b>거친 표면과 과충전 변연은 며칠 만에 치은염을 만듭니다. 그 상태로 뜬 인상은 <u>변연이 부정확한 최종 보철</u>이 됩니다. 임시보철 연마는 최종 성공의 전제조건입니다.</div>",
  },
  {
    title: "인상체 검수",
    category: "보철 적합", order: 5,
    source: "Rosenstiel, Contemporary Fixed Prosthodontics / Zarb·Boucher",
    purpose: "- **재채득 여부를 그 자리에서** 판정\n- 부정확한 인상이 기공으로 넘어가는 것을 막는다",
    technique: "1. **즉시 세척·소독** 후 밝은 조명과 **확대 하**에서 검사\n2. **변연을 한 바퀴 추적** — 전 둘레가 연속으로 인기되었는지\n3. 결함 유형 확인: **void(기포) / drag(끌림) / pull(당김) / tear(찢김) / tray show-through**\n4. 대합·악간관계 기록도 함께 검수\n5. (의치) 변연 두께·형태, 주지지역·완화부 인기 확인",
    criteria: "- **변연에 걸리는 결함은 무조건 재채득**\n- 변연 밖 결함은 위치에 따라 허용 가능\n- 트레이 노출, 재료 분리, 기포 밀집은 재채득 대상",
    interpretation: "- **drag는 재료가 반경화 상태에서 움직였다**는 뜻 — 조작 시간·트레이 안정을 점검\n- **pull은 언더컷 변형** — 트레이 설계·차단(block-out) 필요\n- 반복되면 **재료가 아니라 술식·조직 관리** 문제를 의심",
    pitfalls: "<div class=\"warning\"><b>⚠️ 확대 없이 “괜찮아 보인다”는 판정이 아닙니다</b>변연 한 곳이 끊기면 기공사는 변연을 창작하게 되고, 그 결과는 시적이 아니라 <u>2년 뒤 이차우식</u>으로 돌아옵니다.</div>",
  },
  {
    title: "의치 유지·안정·지지 평가",
    category: "보철 적합", order: 6,
    source: "Zarb·Boucher, Prosthodontic Treatment for Edentulous Patients / McCracken's",
    purpose: "- 환자의 호소를 **세 축으로 분해**해 원인 구조를 특정\n- 조정·이장·재제작 중 무엇이 필요한지 판단",
    technique: "**유지(retention)**\n- 전방·후방으로 당겨 이탈 저항 확인\n- 개구·혀 운동·연하 시 들리는지\n- (상악) **전치부를 아래·앞으로 당기거나 전방을 눌러 후연이 들리는지** 확인 — post-dam이 부족하면 후연에서 폐쇄가 먼저 깨진다\n\n**안정(stability)**\n- 교합면을 **좌우 교대로 눌러** rocking 확인\n- 전후방 회전 확인\n- 저작 시 이동 관찰\n\n**지지(support)**\n- **PIP**로 조직면 접촉 분포 확인\n- 주지지역이 실제로 지지하고 있는지, 완화부가 눌리는지\n- 점막 압통·궤양 부위와 대조",
    criteria: "- 세 축을 각각 **good / fair / poor** 로 기록\n- 부족한 축의 **원인 구조**를 함께 특정",
    interpretation: "<dl><dt>“빠진다·들린다”</dt><dd>유지 → 변연 폐쇄·변연 길이·post-dam</dd><dt>“움직인다·돌아간다”</dt><dd>안정 → 교합·연마면 형태·neutral zone·인공치 위치</dd><dt>“아프다·눌린다”</dt><dd>지지 → 지지영역·과압박·완화부</dd></dl>\n\n- 세 축을 나누어 적으면 다음 방문에서 **어느 축이 나빠졌는지** 추적된다",
    pitfalls: "<div class=\"warning\"><b>⚠️ 조직면부터 깎지 마세요</b>궤양이 있어도 원인이 <u>교합 조기접촉</u>이면 아무리 깎아도 재발하고 의치만 얇아집니다. 지지 축을 평가하기 전에 교합을 먼저 확인하세요.</div>",
  },

  // ═══════════ 무치악 평가 ═══════════
  {
    title: "무치악 치조제 형태·흡수도 평가",
    category: "무치악 평가", order: 1,
    source: "Zarb·Boucher, Prosthodontic Treatment for Edentulous Patients / Cawood & Howell (1988) / Atwood (1971)",
    purpose: "- 총의치의 **지지·안정 예후를 결정하는 1차 인자**를 정량화\n- 이장·재제작 시기 예측, 임플란트 오버덴처 상담의 근거\n- 초진, 재제작 전, 정기 검진마다 (변화 추적)",
    technique: "1. **시진**: 치조제를 정면·측방·교합면 방향에서 관찰\n2. **촉진**: 검지로 치조정을 따라 훑어 **폭·예리함·언더컷**을 확인\n   - 정상 조직 위에서 손가락을 좌우로 굴려 **아래 골의 형태**를 읽는다\n3. **상하악을 따로** 기록 — 흡수 속도가 다르다\n4. **방사선(파노라마)**: 하악 최소 수직 골 높이를 mm로 계측\n5. **변화 추적**: 이전 모형·사진과 비교. 기준이 없으면 이번에 진단모형을 보관",
    criteria: "**형태 기술 — Cawood & Howell 분류**\n<dl><dt>Class III</dt><dd><b>잘 둥근(well-rounded)</b> 형태, 높이·폭 모두 충분 — 예후 양호</dd><dt>Class IV</dt><dd><b>knife-edge</b>, 높이는 있으나 폭 부족</dd><dt>Class V</dt><dd>평탄, 높이·폭 모두 부족</dd><dt>Class VI</dt><dd>함몰, <b>기저골까지 소실</b></dd></dl>\n\n**Atwood 흡수 단계**(Order I–VI)도 같은 개념을 순차 기술한다 — III 높고 둥근 형태 → IV knife-edge → V 낮고 둥근 형태 → VI 함몰.\n\n**ACP PDI(완전무치악) 하악 골 높이** — 파노라마상 최소 수직 높이 기준(McGarry, *J Prosthodont* 1999)\n- **Class I ≥21 mm / II 16–20 mm / III 11–15 mm / IV ≤10 mm**\n\n간이 기술(**ridge form**): **well-formed / knife-edge / flat / resorbed**\n\n**언더컷(undercut)**: 위치·깊이, 착탈로 방해 여부\n**융기(tori / exostoses)**: 구개융기·하악융기의 크기와 언더컷",
    interpretation: "- **Class III(well-formed)** — 통상 총의치로 양호한 지지 기대\n- **Class IV(knife-edge)** — 예리한 골정이 통증원. 완화 또는 골정 정형 검토\n- **Cawood & Howell Class V–VI, ACP PDI Class III–IV** — 통상 총의치의 유지·안정 한계가 명확 → **임플란트 오버덴처를 조기에 상담**해야 하는 근거\n- 흡수는 **첫 해에 급격하고 이후 평생 지속**되며 하악이 상악보다 빠르다(Tallgren) → 이장·재제작을 처음부터 예고",
    pitfalls: "<div class=\"warning\"><b>⚠️ 상하악을 뭉뚱그리지 마세요</b>“치조제 흡수 심함”이라고만 적으면 어느 쪽이 문제인지, 얼마나 진행했는지 알 수 없습니다. <u>상악·하악을 나누고, 분류명 또는 mm</u>로 적어야 다음 방문과 비교됩니다.</div>\n\n- 촉진 없이 시진만 하면 **점막 두께에 가려 골 형태를 오판**한다 — 반드시 만져서 확인",
  },
  {
    title: "지지영역·완화부 확인 (무치악)",
    category: "무치악 평가", order: 2,
    source: "Zarb·Boucher, Prosthodontic Treatment for Edentulous Patients / Cawood & Howell (1988) / Atwood (1971)",
    purpose: "- 인상과 의치가 **어디를 눌러야 하고 어디를 피해야 하는지** 결정\n- 통증·궤양의 예방과 원인 규명",
    technique: "**촉진으로 구조를 하나씩 확인하고 조직 피압축성을 비교한다**\n\n**상악**\n- 주지지역: **수평 경구개 후방 · 치조제 정상**\n- 완화부: **절치유두(incisive papilla)**(비구개신경 통로) · **정중구개봉합(midpalatine raphe)**(피압축성 낮음) · **torus palatinus**\n\n**하악**\n- 주지지역: **buccal shelf**(넓고 치밀한 피질골, 저작압 방향과 수직에 가까움)\n- 보조: 치조제 정상 · retromolar pad\n- 완화부: **mylohyoid ridge**(예리) · **이공(mental foramen)**(치조정 근접 시) · genial tubercle · **torus mandibularis**\n- 후방 설측: **retromylohyoid fossa** 까지 연장 가능한지 확인\n\n**방법**: 손가락으로 눌러 **점막이 얼마나 들어가는지(피압축성)** 를 부위별로 비교하고, 예리한 골연은 통증 유발 여부를 확인",
    criteria: "- 각 구조의 **존재·크기·예리함·언더컷**을 기록\n- **이공이 치조정에 근접**하면 완화 필요로 표기\n- 피압축성이 크게 다른 부위(flabby 등)는 별도 기재",
    interpretation: "- **하악의 주지지역은 치조제가 아니라 buccal shelf** — 흡수된 치조정은 지지 능력이 낮다. 이 점을 놓치면 하악 의치가 계속 아프다\n- **완화부를 지지시키면 통증**, **지지역을 이격시키면 유지 상실** — 방향이 반대인 두 실수\n- 압박 궤양의 위치를 이 지도와 대조하면 원인이 바로 나온다",
    pitfalls: "<div class=\"danger\"><b>🚫 궤양이 보인다고 그 자리를 깎지 마세요</b>완화부(mylohyoid ridge·이공)의 궤양은 완화가 맞지만, <u>주지지역의 궤양은 대개 교합 조기접촉이 원인</u>입니다. 조직면을 깎기 전에 교합을 먼저 확인하세요.</div>",
  },
  {
    title: "가동 치조제(flabby ridge) 평가",
    category: "무치악 평가", order: 3,
    source: "Zarb·Boucher, Prosthodontic Treatment for Edentulous Patients / Cawood & Howell (1988) / Atwood (1971)",
    purpose: "- 인상 방식(무압 window technique)의 적용 여부와 **범위**를 결정\n- 완성 의치의 튀어오름·통증 예방",
    technique: "1. **손가락 또는 기구 손잡이로 치조정을 눌러** 조직이 움직이는지 확인\n2. 움직이는 **범위를 앞뒤로 훑어 경계를 찾고 mm로 계측**\n3. **양손 촉진**으로 가동 조직 아래 골의 실제 위치를 확인\n4. 진단모형에 범위를 표시하고 사진 기록",
    criteria: "- **정상 치조제는 눌러도 움직이지 않는다** — 움직이면 flabby\n- 범위(mm)와 부위(상악 전방이 흔함)를 기록\n- 가동 정도(경도·중등도·고도)를 함께 기술",
    interpretation: "- 상악 전방 flabby는 **잔존 하악 전치와의 조합**(combination syndrome)에서 흔하다 — 하악 상태를 함께 확인\n- **일반 인상을 그대로 뜨면 조직이 눌린 채 기록**되어, 완성 의치가 그 부위에서 튀어오르거나 통증을 만든다\n- 범위가 넓으면 **외과적 제거 vs 무압인상** 중 선택을 상담",
    pitfalls: "<div class=\"warning\"><b>⚠️ 범위를 mm로 적지 않으면 인상 설계가 안 됩니다</b>“flabby ridge 있음”만으로는 트레이에 창(window)을 어디에 낼지 정할 수 없습니다. <u>전후 경계를 계측해 모형에 표시</u>하세요.</div>",
  },
  {
    title: "구개 형태 및 후방 봉쇄 영역 평가",
    category: "무치악 평가", order: 4,
    source: "Zarb·Boucher, Prosthodontic Treatment for Edentulous Patients / Cawood & Howell (1988) / Atwood (1971) / House classification of palatal (throat) form",
    purpose: "- 상악 의치의 **유지력(변연 폐쇄)** 예후를 예측\n- post-dam 위치·깊이·폭 설계의 근거",
    technique: "**구개 형태(palatal vault form)**\n- 정면에서 관찰: **U자형 / V자형 / 평탄형(U-shaped / V-shaped / flat)**\n\n**진동선(vibrating line)**\n1. 환자에게 **“아”를 짧게 반복** 발음시킨다(길게 하면 경계가 흐려진다)\n2. 연구개가 움직이기 시작하는 경계를 관찰하고 **구내에 표시**\n3. 좌우로 이어 **hamular notch까지 연결** — 촉진으로 절흔을 확인\n\n**연구개 각도(throat form)**\n- 연구개가 경구개에서 꺾이는 각도와 가동 조직 폭을 관찰",
    criteria: "**구개 형태**\n- **U자형** — 폐쇄·유지에 가장 유리\n- **V자형** — 변연 폐쇄가 어렵고 측방 안정 불리\n- **평탄형** — 측방 안정 불리\n\n**연구개 각도 (House 분류 개념)**\n- **Class I** 완만하게 내려가며 가동 조직 폭이 넓음 — **폐쇄에 가장 유리**\n- **Class II** 중간\n- **Class III** 급격히 꺾이고 폭이 좁음 — **폐쇄 폭이 좁아 불리**\n(가동 조직 폭의 구체적 수치는 문헌마다 차이가 있어 형태 기술을 우선한다)\n\n**post-dam**: 나비형, 깊이 **1–1.5 mm**를 조직 피압축성에 맞춰 조절",
    interpretation: "- **V자형 + Class III**는 유지가 어려울 것을 미리 예고하고 상담에 반영\n- 유지 불량을 호소하는 기존 의치에서는 **post-dam 마모·소실**을 먼저 확인\n- 진동선은 **해부학적 경계와 반드시 일치하지 않는다** — 기능적으로 확인해야 한다",
    pitfalls: "<div class=\"warning\"><b>⚠️ 깊이를 조직에 맞추지 않으면 양쪽으로 실패합니다</b>과하면 통증·구역, 부족하면 유지 상실입니다. <u>피압축성을 눌러 확인하고</u> 깊이를 정하세요.</div>",
  },
  {
    title: "전정 깊이·소대 부착 평가",
    category: "무치악 평가", order: 5,
    source: "Zarb·Boucher, Prosthodontic Treatment for Edentulous Patients / Cawood & Howell (1988) / Atwood (1971)",
    purpose: "- 의치 변연의 **가능한 신장 범위**를 결정\n- 소대에 의한 탈락·궤양 예방, 전정성형술 필요성 판단",
    technique: "1. **입술·볼을 당기고 밀어** 점막이 움직이는 경계(전정저, **vestibular depth**)를 확인\n2. 치조정에서 전정저까지 **깊이를 mm로** 계측(프로브 사용)\n3. **소대 부착(frenum attachment)** 위치와 높이를 확인 — labial · buccal · lingual frenum\n   - 입술을 당기면서 소대가 **치조정에 얼마나 가까이 붙는지** 관찰\n4. 혀를 좌우·전방으로 움직이게 해 **설측 전정 · 설소대 · retromylohyoid fossa** 를 확인",
    criteria: "- 전정 깊이(mm)를 부위별로\n- 소대 부착: **치조정에서 떨어짐(양호) / 치조정에 근접 / 치조정에 부착(불리)**\n- 소대 수와 위치를 기록",
    interpretation: "- **전정이 얕으면 변연 길이가 짧아져 유지가 떨어진다** → 전정성형술 또는 임플란트 대안 검토\n- **소대가 치조정에 부착**되어 있으면 변연에 깊은 절흔이 필요해 그 부위 폐쇄가 끊긴다 → 소대절제술 검토\n- 기능 시 소대가 의치를 밀어내면 **반복 탈락·선상 궤양**의 원인",
    pitfalls: "<div class=\"tip\"><b>💡 정지 상태로만 보면 놓칩니다</b>소대는 <u>입술·볼·혀를 실제로 움직여야</u> 제 위치가 드러납니다. border molding에서 하는 기능 운동을 검사 단계에서 미리 해보세요.</div>",
  },
  {
    title: "혀 크기·위치 평가",
    category: "무치악 평가", order: 6,
    source: "Zarb·Boucher, Prosthodontic Treatment for Edentulous Patients / Cawood & Howell (1988) / Atwood (1971) / Wright classification of tongue position",
    purpose: "- **하악 의치의 안정** 예후를 예측\n- 인공치 배열 위치(neutral zone)와 설측 변연 설계에 반영",
    technique: "1. 환자를 이완시키고 **의치를 뺀 상태**에서 혀의 안정 위치를 관찰 (**tongue size & position**)\n2. 입을 벌린 채 **혀를 움직이지 말라고 하고** 위치를 본다 — 지시하면 위치가 바뀐다\n3. 혀의 **크기**(치조제를 넘어 퍼지는지)와 **치흔** 유무 확인\n4. 하악 무치악 기간이 길수록 혀가 커지는 경향을 감안",
    criteria: "**Wright 분류 개념**\n- **Class I** 혀가 구강저에 있고 **혀끝이 앞쪽 치조제에 닿음** — 유리\n- **Class II** 혀가 넓고 평평해졌으나 혀끝 위치는 정상\n- **Class III** 혀가 **후방으로 당겨지고 아래로 눌림**, 혀끝이 말림 — **불리**\n\n- 크기: normal / enlarged(치조제를 덮음)",
    interpretation: "- **Class III(retracted)** — 혀가 의치 설측 변연을 덮어 폐쇄를 만들지 못하고, 저작 시 의치를 들어올린다 → **하악 유지 예후 불량**\n- 혀가 크면 **인공치를 설측으로 배열할 공간이 없다** → neutral zone 기법 검토\n- 신경근 조절 저하(파킨슨·뇌졸중)와 겹치면 예후를 더 낮춰 상담한다",
    pitfalls: "<div class=\"warning\"><b>⚠️ “혀 내미세요”라고 하면 안 됩니다</b>지시하는 순간 평소 위치가 아닙니다. <u>이완 상태에서 관찰</u>해야 실제 안정 위치를 알 수 있습니다.</div>",
  },
  {
    title: "구역반사 평가",
    category: "무치악 평가", order: 7,
    source: "Dickinson & Fiske, Gagging Severity Index / Zarb·Boucher",
    purpose: "- 인상·의치 후연 설계·치료 진행 방식을 미리 조정\n- 실패 위험이 높은 환자를 **처치 전에** 식별",
    technique: "1. **병력 문진이 먼저** — 칫솔질·인상·엑스레이 촬영·의치 착용 시 구역질(**gag reflex**) 경험, 유발 상황, 회피 행동\n2. **자극 검사는 최소한으로**: 설압자로 설배 후방·연구개를 가볍게 접촉해 반응 관찰\n3. 반응의 **정도와 유발 부위**(촉각성 / 심인성)를 기록\n4. 반복 자극하지 않는다 — 신뢰를 잃으면 이후 처치가 더 어려워진다",
    criteria: "**Gagging Severity Index 개념 (Grade I–V)**\n- **I** 매우 경미, 가끔 발생하며 환자가 스스로 조절\n- **II** 경미, 진료진의 도움으로 조절 가능\n- **III** 중등도, 일관되게 나타나 처치가 제한됨\n- **IV** 중증, 모든 치과 처치에 영향, 불안 조절 필요\n- **V** 매우 중증, 보조 요법 없이는 처치가 사실상 불가\n(등급 정의는 문헌마다 표현 차이가 있어 **정도와 상황을 함께 서술**하는 편이 안전하다)",
    interpretation: "- **후방 변연 과신장·과두께**가 가장 흔한 유발 요인 — 설계로 상당 부분 해결된다\n- **심인성 요소**가 크면 단계적 노출·행동 조절이 필요하고 처치 시간을 짧게 나눈다\n- Grade III 이상이면 **인상 방식·진료 시간·상담 내용**을 미리 조정하고 기록",
    pitfalls: "<div class=\"danger\"><b>🚫 자극 검사를 반복하지 마세요</b>확인하려고 여러 번 유발하면 환자의 불안이 커져 <u>이후 인상과 장착이 훨씬 어려워집니다.</u> 병력 문진으로 대부분 판단되고, 자극은 최소한으로 한 번이면 충분합니다.</div>",
  },
  {
    title: "기존 의치 평가",
    category: "무치악 평가", order: 8,
    source: "Zarb·Boucher, Prosthodontic Treatment for Edentulous Patients / Cawood & Howell (1988) / Atwood (1971)",
    purpose: "- **무엇이 성공했고 무엇이 실패했는지**를 계측해 새 의치에 반영\n- 환자 호소의 원인 구조를 특정",
    technique: "**의치를 구내에 넣은 상태와 뺀 상태를 나누어 본다**\n\n**변연**\n- **Border extension**: 부위별 under / over-extended\n- **Post-dam** 유무·형태, **border seal** 확인(전방 견인 저항)\n\n**조직면**\n- **PIP**로 조직면 접촉 분포(**intaglio adaptation**) — 주지지역이 실제로 지지하는지\n- 이장·수리 흔적, 조직면 거칠기\n\n**교합**\n- 양측 균등 접촉 여부, **VDO / FWS 계측**\n- **인공치 마모(artificial tooth wear)** 평탄화 정도로 VDO 감소량 추정\n\n**심미**\n- 정중선(midline), 안정 시·미소 시 **절치 노출량(incisal display, mm)**, 순측 지지(lip support)\n\n**위생**\n- 바이오필름·치석 침착, 냄새, 세척 습관\n\n**계측값과 사진을 남긴다** — 새 의치의 출발점이 된다",
    criteria: "- 각 항목을 **수치 또는 부위로** 기록(“낡음” 같은 표현은 정보가 아니다)\n- 성공 요소(유지되는 부분)와 실패 요소를 나누어 표기",
    interpretation: "- **환자가 만족하는 부분은 그대로 복제**하고, 불만 부분만 바꾸는 것이 재제작 성공률을 높인다\n- 호소를 세 축으로 분해: 빠진다(유지) / 움직인다(안정) / 아프다(지지)\n- **VDO가 낮아져 있으면** 구각염·저작 효율 저하와 연결해 설명",
    pitfalls: "<div class=\"warning\"><b>⚠️ 기존 의치를 “참고만” 하고 버리지 마세요</b>환자가 수년간 적응한 <u>순측 지지·절치 위치·구개 두께</u>는 가장 값진 정보입니다. 계측 없이 새로 만들면 “예전 것이 나았다”는 말을 듣게 됩니다.</div>",
  },
  {
    title: "무치악 난이도 분류 및 적응 유형",
    category: "무치악 평가", order: 9,
    source: "ACP Prosthodontic Diagnostic Index — McGarry et al., J Prosthodont 1999·2004 / House classification",
    purpose: "- 치료 난이도를 **미리 층화**해 상담·시간·비용·의뢰를 결정\n- 예후 설명의 근거를 문서로 남긴다",
    technique: "**ACP PDI(완전무치악) 판정 요소를 순서대로 확인**\n1. **하악 골 높이**(파노라마 최소 수직 높이, mm)\n2. **상악 잔존 치조제 형태**\n3. **근부착 위치**(전정 깊이·소대)\n4. **악간 관계**(Class I / II / III)\n\n**적응 유형(House 분류)** — 문진과 태도 관찰로 판단\n- 과거 의치 적응 경험, 기대 수준, 설명에 대한 반응",
    criteria: "**ACP PDI Class I–IV** — 위 네 요소를 종합하며, **가장 불리한 항목이 등급을 결정**한다\n- 하악 골 높이 **Class I ≥21 / II 16–20 / III 11–15 / IV ≤10 mm** (네 요소 중 가장 불리한 항목이 전체 Class 를 결정)\n\n**House 적응 유형**\n<dl><dt>Philosophical</dt><dd>현실적이고 협조적 — <b>예후 가장 양호</b></dd><dt>Exacting</dt><dd>요구가 정밀·과도. 설명과 문서화가 특히 중요</dd><dt>Indifferent</dt><dd>무관심·비협조 — 유지관리 이행이 낮다</dd><dt>Hysterical</dt><dd>정서적으로 불안정 — <b>예후 가장 불량</b>, 기대 조정이 선행</dd></dl>",
    interpretation: "- **Class III–IV**면 통상 총의치의 한계를 **처음 상담에서** 명시하고 임플란트 오버덴처를 함께 제시\n- **해부학적 조건이 좋아도 적응 유형이 불리하면 실패한다** — 총의치 성공의 최대 변수는 환자 요인이라는 점을 반영\n- 등급과 근거를 함께 적으면 이후 불만 상황에서 설명의 근거가 된다",
    pitfalls: "<div class=\"tip\"><b>💡 난이도는 상담을 위한 도구입니다</b>등급을 매기는 목적은 분류가 아니라, <u>무엇이 어려울지 미리 말하고 기대를 맞추는 것</u>입니다. 완성 후에 설명하면 변명이 되고, 시작 전에 설명하면 동의가 됩니다.</div>",
  },

  // ═══════════ 임플란트 ═══════════
  {
    title: "임플란트 주위 탐침 및 변연골 판독",
    category: "임플란트", order: 1,
    source: "Misch, Dental Implant Prosthetics / 2017 World Workshop · ITI Treatment Guide",
    purpose: "- **임플란트 주위 점막염 / 주위염**의 감별\n- 정기 리콜의 핵심 검사 — **점막염 단계에서 잡는 것**이 목표",
    technique: "**탐침**\n1. **플라스틱 또는 전용 프로브** 사용(티타늄 표면 손상 방지 목적으로 널리 권장)\n2. 힘은 **가볍게 — 약 0.25 N**. 임플란트 주위 조직은 자연치보다 프로브가 깊이 들어간다\n3. **6점** 기록, **BOP·배농(suppuration)** 확인\n4. 각화점막 폭, 퇴축 함께 기록\n\n**방사선**\n1. **규격 촬영**(평행법·홀더 사용) — 각도가 달라지면 비교가 무의미\n2. **장착 시점 baseline과 동일 조건**으로 촬영\n3. 나사산을 눈금 삼아 **변연골 수준 변화량(mm)** 을 계측",
    criteria: "**2017 World Workshop 기준**\n<dl><dt>건강</dt><dd>염증 징후 없음, BOP 없음, 초기 개조 이후 진행성 골소실 없음</dd><dt>주위 점막염</dt><dd><b>BOP(+)</b>, 발적·부종 — 초기 개조를 넘는 골소실 <b>없음</b>. <u>가역적</u></dd><dt>주위염</dt><dd>BOP/배농 + 탐침 깊이 증가 + <b>진행성 변연골 소실</b>. 기준 자료가 없으면 <u>골정이 골내부 최상방에서 ≥3 mm 근단측 + PD ≥6 mm + BOP</u></dd></dl>\n\n- 성공 기준(Albrektsson 1986): 첫 해 이후 **연간 골소실 &lt;0.2 mm**",
    interpretation: "- **점막염은 치태 조절만으로 대부분 회복** — 여기서 잡아야 한다\n- **주위염은 치료 결과가 예측 불가능**하고 재발이 흔하다\n- 원인은 대개 복합: 치태, **잉여 시멘트**, 과부하, 청소 불가능한 보철 형태, 각화점막 부족, 흡연, 치주염 병력\n- 통증은 늦게 나타난다 — **“안 아프다”가 건강의 근거가 되지 않는다**",
    pitfalls: "<div class=\"warning\"><b>⚠️ baseline이 없으면 판독할 수 없습니다</b>장착 시점 규격 방사선을 저장해 두지 않으면 골소실이 “원래 그런 것”인지 “진행된 것”인지 구분할 수 없습니다. 장착 당일 baseline 촬영과 시스템·토크값 기재를 습관화하세요.</div>",
  },
  {
    title: "골유착 평가 (타진 · 동요 · ISQ)",
    category: "임플란트", order: 2,
    source: "Misch, Dental Implant Prosthetics / 2017 World Workshop · ITI Treatment Guide",
    purpose: "- 보철 진행 전 **골유착 성립 여부** 확인\n- 하중 시기 결정의 근거",
    technique: "1. **타진(percussion)** — 기구 손잡이로 가볍게. **맑은 금속음** vs 둔탁한 음\n2. **동요(mobility)** — 기구 두 개로 확인. 임플란트는 **동요가 있으면 곧 실패**\n3. **방사선** — 나사산 주위 **투과대(radiolucency)** 유무, 변연골 수준\n4. **ISQ (RFA, resonance frequency analysis)** — 전용 페그를 체결해 측정. **같은 장비·같은 방향**으로 반복 측정해야 비교 가능\n5. 통증·배농·발적 확인",
    criteria: "- 타진: **맑은 금속음**\n- 동요: **없음**(자연치와 달리 생리적 동요가 없다)\n- 방사선: **투과대 없음**\n- **ISQ**: 일반적으로 **70 이상이면 안정적**으로 해석하는 경우가 많다(장비·부위·시스템에 따라 해석 폭이 있음)",
    interpretation: "- **동요 (+) = 골유착 실패** — 보철을 진행하지 않는다\n- ISQ는 **절대값보다 추세**가 중요 — 시간에 따라 상승하면 안정화, 하락하면 경고\n- 저밀도 골(상악 후방)에서는 치유 기간을 늘리고 즉시 하중을 피하는 것이 통례",
    pitfalls: "<div class=\"warning\"><b>⚠️ ISQ 해석 주의</b>측정 방향(협설/근원심), 페그 종류, 장비가 다르면 값이 달라집니다. <u>같은 조건에서 반복 측정한 추세</u>로 보세요. 단일 수치 하나로 하중 시기를 결정하지 않습니다.</div>",
  },
  {
    title: "임플란트 보철 점검 (리콜)",
    category: "임플란트", order: 3,
    source: "Misch, Dental Implant Prosthetics / ITI Treatment Guide",
    purpose: "- 기계적 합병증을 **증상 전에** 발견\n- 시간에 따라 변하는 교합·접촉을 보정",
    technique: "1. **나사 풀림 확인**: 보철물을 손가락으로 흔들어 미세 동요·소리 확인. 의심되면 access 개방\n2. **교합 재확인**: 경교합에서 shimstock이 **빠지는지**, 강교합에서 **잡히는지**\n3. **인접 접촉**: 치실·shimstock — **접촉 상실은 시간이 지나 새로 생긴다**\n4. **도재 상태**: chipping·균열\n5. (시멘트 유지형) **잔여 시멘트** 방사선 확인\n6. **위생 접근성** 확인(아래 별도 항목)",
    criteria: "- 나사 풀림 없음, 교합은 implant-protected 상태 유지\n- 인접 접촉 유지, 도재 손상 없음\n- 이상 발견 시 **원인까지 기재**",
    interpretation: "- **자연치는 마모·이동하지만 임플란트는 그대로** — 리콜마다 상대적 고접촉이 새로 생긴다\n- **접촉 상실**은 인접 자연치의 근심 이동 결과이며 식편압입·주위 염증으로 이어진다\n- 나사 풀림은 **경고 신호**다 — 재조임만 하고 원인을 두면 파절로 진행",
    pitfalls: "<div class=\"danger\"><b>🚫 재조임만 하고 끝내지 마세요</b>풀림은 결과이고 원인은 대개 <u>교합 과부하·부정합·cantilever</u>입니다. 원인을 적지 않으면 다음 술자가 같은 처치를 반복하게 됩니다.</div>",
  },
  {
    title: "위생 접근성 평가",
    category: "임플란트", order: 4,
    source: "ITI Treatment Guide / 2017 World Workshop (peri-implant diseases)",
    purpose: "- 환자가 **실제로 청소할 수 있는 형태인지** 확인\n- 임플란트 주위 질환의 가장 큰 인재성 위험 인자 제거",
    technique: "1. **수퍼플로스**를 보철물 하방으로 통과시켜 본다\n2. **치간칫솔**을 크기별로 넣어 실제로 들어가는 크기를 찾는다\n3. 보철물 하방·emergence 형태를 거울로 확인 — 오목한 함몰이 있는지\n4. **환자에게 직접 해보게 한다** — 술자가 되는 것과 환자가 되는 것은 다르다\n5. 다수 연결 보철·오버덴처는 부속 주변 접근성도 확인",
    criteria: "- 수퍼플로스·치간칫솔이 **저항 없이 통과**\n- 환자가 스스로 수행 가능\n- 통과하지 못하면 **보철물 형태 수정 대상**",
    interpretation: "- **청소 불가능한 형태는 위생 교육으로 해결되지 않는다** — 형태를 바꿔야 한다\n- 과도한 emergence, 하방 함몰, 긴 cantilever가 대표적 원인\n- 각화점막 부족이 동반되면 불편으로 위생이 더 나빠진다",
    pitfalls: "<div class=\"tip\"><b>💡 환자 손에 도구를 쥐여 주세요</b>“치간칫솔 쓰세요”로 끝내면 크기도 모르고 각도도 모릅니다. <u>진료실에서 크기를 골라 주고 직접 해보게</u> 하는 것이 이 검사의 실제 목적입니다.</div>",
  },

  // ═══════════ 계측·기록 ═══════════
  {
    title: "Ferrule · 잔존 치질 계측",
    category: "계측·기록", order: 1,
    source: "Shillingburg / Fradeani, Esthetic Rehabilitation / White & Pharoah, Oral Radiology",
    purpose: "- 실활치·광범위 결손치의 **수복 가능 여부**와 예후를 가르는 계측\n- post & core, 치관연장술, 발치 결정의 분기점",
    technique: "1. 기존 수복물·우식을 **완전히 제거**한 뒤 계측(제거 전 값은 의미 없음)\n2. **예정 변연 위치**를 기준으로 그 상방 건전 치질의 **높이**를 계측\n3. 같은 부위의 **두께**를 계측\n4. **면별로 기록**: **B / L / M / D** — 평균이 아니라 **가장 부족한 면**이 예후를 결정\n5. **연속성(continuous)** 여부를 명시 — 한 바퀴 이어지는지",
    criteria: "- 목표: **높이 ≥1.5–2 mm**, **두께 ≥1 mm**, **연속적**\n- 축벽 높이(저항형태): 구치 **&lt;3–4 mm**면 보조 유지형태(홈·box) 필요\n- **C:R ratio**: 이상 1:2, **최소 1:1**",
    interpretation: "- 연속적 ferrule은 post-core 수복치의 **파절 저항을 유의하게 높인다**(Sorensen & Engelman; SR Juloski)\n- **부분(한 면만) ferrule은 예측성이 낮다** → 치관연장술 / 교정적 정출 / 발치 후 임플란트를 저울질\n- **post는 치아를 강화하지 않는다** — core를 유지할 뿐이며 post space 형성 자체가 치질을 제거한다",
    pitfalls: "<div class=\"danger\"><b>🚫 판단 순서</b>“post를 어떻게 넣을까”보다 <u>“이 치아를 살릴 가치가 있는가”</u>가 먼저입니다. ferrule 확보 불가 + C:R 불량 + 치주 지지 소실이 겹치면, 무리한 수복은 수년 뒤 <b>수복 불가능한 치근 파절</b>로 끝나고 임플란트 예후(골 소실)까지 나빠집니다.</div>",
  },
  {
    title: "색조 채득 (Shade taking)",
    category: "계측·기록", order: 2,
    source: "Shillingburg / Fradeani, Esthetic Rehabilitation / White & Pharoah, Oral Radiology",
    purpose: "- 재현 가능한 색 정보를 기공에 전달\n- 심미 실패의 상당수는 **채득 조건**에서 갈린다",
    technique: "**시점**\n- **삭제·러버댐 격리 전, 진료 초반에** 채득 — 치아가 **탈수되면 명도가 올라가** 실제보다 밝게 보인다\n- 탈수된 경우 **수분 회복까지 기다린다**\n\n**조건**\n- **자연광 또는 색온도 교정 광원**(주광색). 강한 무영등 아래는 피한다\n- 환자의 **립스틱·화려한 옷**은 가리고, 배경은 중간 회색\n- 눈의 피로를 피해 **5–7초 내에 판단**하고, 사이사이 회색을 본다\n\n**순서 — 명도부터**\n1. **Value(명도)** → 2. **Chroma(채도)** → 3. **Hue(색상)**\n2. 치경부·중앙·절단 **부위별로** 기록\n3. 특성 기록: 백반, 균열선, 투명대, 착색\n\n**전달**\n- **shade tab을 치아 옆에 대고 사진 촬영**(편광·역광 포함), 회색카드 동반\n- 반투명 재료(베니어·전부도재)는 **stump shade(지대치 색)** 를 함께 전달",
    criteria: "- Vita classical(A1–D4) 또는 3D-Master 등 **사용한 체계를 명시**\n- 부위별 shade와 특성을 함께 기재",
    interpretation: "- **명도(value)가 가장 먼저 눈에 띈다** — 명도가 어긋나면 채도·색상이 맞아도 튄다\n- 미백 예정이면 **미백 완료 후 1–2주 뒤** 최종 색을 결정한다(잔류 산소가 접착도 저하시킨다)\n- 사진은 육안 판정을 **대체하지 않고 보완**한다",
    pitfalls: "<div class=\"warning\"><b>⚠️ 순서를 틀리면 다시 만듭니다</b>① 삭제 후 탈수된 치아로 채득 → 밝게 나옴 → 최종이 어두워 보임. ② 보철을 먼저 하고 나중에 미백 → 색 불일치로 <b>재제작</b>. 올바른 순서는 <u>미백 → 2주 대기 → 색 결정 → 수복·보철</u>입니다.</div>",
  },
  {
    title: "규격 사진 · 방사선 촬영과 판독",
    category: "계측·기록", order: 3,
    source: "Shillingburg / Fradeani, Esthetic Rehabilitation / White & Pharoah, Oral Radiology",
    purpose: "- **비교 가능한** 기록 확보 — 경과 추적과 판독의 전제\n- 심미 계획, 기공 소통, 분쟁 예방",
    technique: "**규격 사진**\n- 구내 5장(정면·좌우 협측·상하 교합면) + 안모 3장(정면·미소·측방)\n- **동일한 배율·거리·각도·조명**으로 반복 촬영해야 비교가 가능\n- 리트랙터·미러 사용, 김서림 방지, 타액 제거\n- 심미 증례는 **편광·역광** 추가\n\n**방사선**\n- **평행법 + 홀더** 사용 — 각도가 달라지면 골 수준 비교가 무의미\n- **임플란트는 baseline과 동일 조건**으로 촬영\n- 촬영 범위·빈도는 **임상 소견과 위험도에 따라 선택적으로**(무증상 저위험군에 일률적 촬영은 지양)\n\n**판독 체크리스트**\n1. 골 수준·양상(수평/수직), 골지지 %\n2. **C:R ratio**\n3. 치근단 병소·근관 상태\n4. 변연부 투과상, 이차우식, **잔여 시멘트**\n5. 해부 구조: 상악동, 하치조신경관, 이공",
    criteria: "- 사진: 동일 조건 재현 가능\n- 방사선: 왜곡 최소(치근 길이·나사산이 좌우 대칭으로 보이는지)\n- 임플란트: baseline 대비 **변연골 변화량(mm)** 산출 가능",
    interpretation: "- **방사선은 협설 병소·초기 골 결손을 보여주지 않는다** — 임상 검사와 반드시 함께\n- 각도가 다른 두 장은 **골 변화 판독의 근거가 될 수 없다**\n- 사진은 심미 합의와 기공 지시의 **가장 강력한 수단**",
    pitfalls: "<div class=\"warning\"><b>⚠️ 비교 불가능한 기록은 기록이 아닙니다</b>각도·배율이 매번 다르면 “좋아졌는지 나빠졌는지”를 말할 수 없습니다. 홀더와 촬영 조건을 고정하고, 임플란트는 <b>장착 당일 baseline</b>을 반드시 남기세요.</div>",
  },
  {
    title: "CBCT 판독 체크리스트",
    category: "계측·기록", order: 4,
    source: "White & Pharoah, Oral Radiology / ITI Treatment Guide",
    purpose: "- 촬영한 범위를 **빠짐없이** 읽는다\n- 임플란트 계획에 필요한 계측값 확보와 우연 소견 발견",
    technique: "**촬영 정당화가 먼저** — 임상 정보가 진단·치료를 바꿀 때만 촬영한다(선택 기준·ALARA)\n\n**판독 순서를 고정한다**\n1. **촬영 범위 전체를 훑는다** — 관심 부위만 보면 우연 소견을 놓친다\n2. **골**: 높이·폭(mm), 밀도, 피질골 두께, **협측 골판 두께**\n3. **해부 구조**: 하치조신경관·이공(전방 loop), 상악동저·중격, 절치관, 설측 함몰\n4. **병소**: 치근단 병소, 낭·종양, 부비동 점막 비후\n5. **치아**: 치근 형태·흡수, 파절선, 근관 상태\n6. **인공음영 구분**: 금속 줄무늬가 해부를 가로지르면 허상\n\n**계측**은 임플란트 예정 위치의 단면에서 수행하고 값을 기록",
    criteria: "- 계측값은 **mm 단위와 측정 위치**를 함께\n- 판독 한계를 명시(예: “금속 인공음영으로 근심 골 수준 평가 제한”)",
    interpretation: "- **골 높이보다 협측 골판 두께가 심미부 예후를 좌우**한다\n- 신경관까지 안전 거리를 확보하고, 전방 loop를 고려\n- 우연 소견은 **범위 밖이라도 기록하고 필요 시 의뢰**한다 — 판독 책임은 촬영 범위 전체에 미친다",
    pitfalls: "<div class=\"danger\"><b>🚫 관심 부위만 보지 마세요</b>임플란트 자리만 확인하고 넘기면 상악동 병변·낭·종양 같은 우연 소견을 놓칩니다. <u>촬영한 범위 전체가 판독 대상</u>입니다.</div>",
  },
  {
    title: '항응고·항혈소판제 복용 평가',
    category: '전신 평가', order: 2,
    source: 'SDCEP, Management of Dental Patients Taking Anticoagulants or Antiplatelet Drugs / 관련 체계적 문헌고찰',
    purpose: '- 침습 처치 전 **출혈 위험과 혈전 위험을 함께** 저울질\n- 약을 끊을 것인지 여부는 치과가 단독으로 정하지 않는다 — 판단 근거를 기록으로 남긴다',
    technique: '**① 약제를 정확히 특정한다**\n- 항응고제: 와파린 / DOAC(아픽사반·리바록사반·다비가트란·에독사반)\n- 항혈소판제: 아스피린 / 클로피도그렐 / 이중 항혈소판요법(DAPT)\n- **복용 목적**(심방세동·기계판막·스텐트·정맥혈전) 과 **시작 시점**\n\n**② 와파린은 INR 을 확인한다**\n- 안정적인 환자라면 **처치 전 24–72시간 이내** 값, 불안정하면 당일 값\n- 값과 측정 일시를 그대로 기록\n\n**③ DOAC 은 INR 이 의미가 없다**\n- 대신 **마지막 복용 시각**, 신기능(고령·신부전에서 축적), 하루 복용 횟수를 확인\n\n**④ 처치의 출혈 위험을 등급으로 나눈다**\n- 낮음: 단순 발치 1–3개, 치주 탐침, 보철 인상\n- 높음: 다수 발치, 판막 거상, 골 삭제, 광범위 소파\n\n**⑤ 국소 지혈 준비를 처치 전에 갖춘다** — 봉합, 산화셀룰로오스·젤라틴 스펀지, 트라넥삼산 함수(기관 프로토콜), 압박 거즈',
    criteria: '- **와파린**: SDCEP 지침은 INR 이 <mark style="background:#fef08a">4.0 미만</mark>이면 통상 치과 처치를 그대로 진행할 수 있다고 본다. 국내·기관에 따라 <b>3.5</b> 를 기준선으로 삼기도 하므로 소속 프로토콜을 따른다\n- **DOAC**: 대부분의 치과 처치에서 **중단 없이 진행**하되, 출혈 위험이 큰 처치는 아침 복용을 늦추는 등의 조정을 처방의와 협의\n- **항혈소판제**: 단독·이중 모두 **원칙적으로 중단하지 않는다**',
    interpretation: '- **끊는 쪽이 더 위험한 경우가 많다.** 치과 처치로 인한 중증 출혈 보고는 드문 반면, 항응고를 중단했다가 색전 사건이 생긴 보고는 반복해서 나온다\n- INR 이 기준을 넘거나 값이 불안정하면 **처치를 미루고 처방의와 협의** — 치과에서 용량을 조정하지 않는다\n- DOAC 과 와파린(INR 2–4)의 발치 후 출혈률은 비슷한 수준으로 보고되며, DOAC 이 오히려 낮다는 메타분석도 있으나 **근거의 질은 낮다**\n- 출혈이 생기면 대부분 **국소 지혈로 해결된다** — 그 준비가 되어 있는지가 실질적 안전 요인',
    pitfalls: '<div class="danger"><b>🚫 “안전하게 며칠 끊고 오세요”가 가장 위험한 지시입니다</b>치과 처치의 출혈은 대개 국소 지혈로 해결되지만, <u>중단으로 생긴 뇌졸중·색전은 되돌릴 수 없습니다.</u> 중단은 처방의의 판단 영역입니다.</div>\n\n- 오래된 INR 값을 그대로 사용 — 측정 일시를 반드시 기록\n- DOAC 환자에게 INR 을 요구 — 의미 없는 검사다\n- 약제명을 “피 묽어지는 약”으로만 기록 — 계열이 다르면 대응이 다르다\n- 국소 지혈 준비 없이 처치 시작'
  },
  {
    title: '골흡수억제제 복용력 및 MRONJ 위험 평가',
    category: '전신 평가', order: 3,
    source: 'AAOMS Position Paper on MRONJ — 2022 Update',
    purpose: '- 발치·임플란트 등 **골 침습 처치 전** 약제관련 악골괴사 위험을 판정\n- 위험을 과대평가해 필요한 치료를 미루지도, 과소평가해 처치하지도 않기 위한 근거를 만든다',
    technique: '**① 약제를 특정한다**\n- **비스포스포네이트**(경구/정맥), **데노수맙**, 혈관신생억제제, 일부 표적치료제\n- **투여 경로·용량·기간·마지막 투여 시점**을 모두 확인 — 기간이 길수록 위험이 올라간다\n- 골다공증 목적인지 **악성종양 목적**인지 구분 — 위험 차이가 크다\n\n**② 구강 내를 본다**\n- 노출된 골, 누공, 치조골 불규칙, 발치와 치유 지연\n- 방사선: 경화성 변화, 치조백선 비후, 부골, 상악동·하악관 변화\n\n**③ 위험 요인을 함께 기록한다**\n- 스테로이드·당뇨·흡연·항암치료 병용\n- 치주염·부적합 의치에 의한 만성 자극\n\n**④ 처치 전 계획**\n- 가능한 침습 처치를 **약제 시작 전에** 마치는 것이 원칙\n- 이미 복용 중이면 **비침습 대안**(근관치료 후 치관 절제 등)을 먼저 검토',
    criteria: '- **MRONJ 진단 3요건**: ① 현재/과거 골흡수억제제·혈관신생억제제 투여 ② 노출된 골 또는 구내외 누공으로 탐침되는 골이 <b>8주 이상</b> 지속 ③ 악골에 <b>방사선 조사 병력 없음</b>, 전이성 병소 아님\n- **병기**: Stage 0(비특이 증상·영상 소견, 노출골 없음) / 1(무증상 노출골) / 2(감염 동반 증상성 노출골) / 3(하연·상악동 등으로 확장, 병적 골절·누공)\n- **발생률(AAOMS 2022)**: 골다공증 환자 <mark style="background:#fef08a">0.02–0.3%</mark>, 암 환자 <mark style="background:#fef08a">0.5–5%</mark>',
    interpretation: '- 대부분의 MRONJ 는 **자발 발생이 아니라 치조 수술 이후**에 나타난다 → 발치·임플란트 계획에서 가장 신중해야 한다\n- 골다공증 목적 경구 투여의 절대 위험은 **매우 낮다.** 위험을 이유로 필요한 발치를 무기한 미루면 감염이 더 큰 문제가 된다\n- **약물 휴지기(drug holiday)** 는 논쟁적이다. AAOMS 는 적절하다고 판단될 경우 일부 약제에서 마지막 투여 후 **3–4개월** 시점의 수술을 언급하지만, 효과를 입증한 고수준 근거는 없다 — **처방의와 협의해 결정하고 그 협의 내용을 기록**한다\n- 임플란트는 금기가 아니지만 **암 환자·정맥 투여군에서는 신중**하며, 환자에게 위험을 설명하고 동의를 받는다',
    pitfalls: '<div class="warning"><b>⚠️ 흔한 오류</b>① <b>데노수맙을 비스포스포네이트와 같게</b> 취급 — 반감기와 중단 후 회복 양상이 다릅니다 ② “골다공증 약 먹는다”만 기록하고 <b>기간·경로</b> 누락 ③ 치과가 단독으로 약을 중단시킴 ④ Stage 0(노출골 없는 증상)을 놓침.</div>'
  },
  {
    title: '감염성 심내막염 예방적 항생제 적응증 확인',
    category: '전신 평가', order: 4,
    source: 'AHA Scientific Statement 2021 (2007 권고 유지) / ADA Oral Health Topics',
    purpose: '- 예방적 항생제가 **정말 필요한 소수**를 가려낸다\n- 불필요한 투여를 줄이는 것도 임상 판단의 일부다',
    technique: '**① 심장 상태를 확인한다** — 병력 청취 + 필요 시 주치의 확인\n**② 처치가 적응증에 해당하는지 본다**\n- 대상: **치은 조직·치근단 부위를 다루거나 구강 점막을 천공하는** 처치(발치, 치주 처치, 임플란트, 근관계 기구 조작 등)\n- 비대상: 국소마취 주사(비감염 조직), 방사선 촬영, 가철성 보철·교정 장치 착탈, 유치 탈락, 입술·구강 점막 외상\n**③ 투여 시점**: 처치 **30–60분 전** 1회\n**④ 알레르기 병력**을 확인해 대체 약제를 선택',
    criteria: '**투여를 고려하는 최고위험군(AHA)**\n- 인공 심장판막 또는 판막 수복에 인공물 사용(링·chord·clip 포함)\n- **감염성 심내막염 기왕력**\n- 특정 선천성 심질환 — 미교정 청색증형, 인공물로 교정 후 6개월 이내, 잔존 결손이 있는 경우\n- **심장 이식 후 판막병증**이 있는 경우\n\n그 외의 심잡음·승모판탈출·류마티스열 병력·관상동맥 스텐트 등은 **일반적으로 대상이 아니다.**',
    interpretation: '- 2021년 AHA 성명의 결론은 **2007년 권고를 바꿀 근거가 없다**는 것이었다. 즉 대상은 여전히 **최고위험군으로 제한**된다\n- **클린다마이신은 더 이상 권장되지 않는다**(중대한 부작용 위험) — 대체 약제는 최신 지침을 확인\n- 지침이 반복해서 강조하는 점: **예방적 항생제보다 평소 구강위생과 정기 치과 관리가 더 중요하다**\n- 인공 관절 치환술 환자에 대한 일상적 예방 투여는 **권장되지 않는다**(정형외과 주치의 판단이 필요한 예외 존재)',
    pitfalls: '<div class="warning"><b>⚠️ 자주 나는 오류</b>① 심잡음·스텐트 환자에게 <b>관행적으로</b> 투여 ② 투여 시점을 놓치고 처치 후 투여 ③ 알레르기 확인 누락 ④ 최고위험군인데 <b>확인 없이</b> 처치.</div>\n\n- 환자가 “예전에 먹었다”고 하면 <b>당시 사유</b>를 확인 — 오래된 지침에 따른 것일 수 있다'
  },
  {
    title: '당뇨 조절 상태 평가 (HbA1c)',
    category: '전신 평가', order: 5,
    source: '임플란트-당뇨 체계적 문헌고찰(2016·2021) / 관련 내러티브 리뷰',
    purpose: '- 치유·감염 위험과 **임플란트 예후**를 가늠한다\n- 조절 상태에 따라 처치 시점과 범위를 조정한다',
    technique: '**① 병력에서 확인할 것**\n- 진단 시점, 치료 방식(경구약/인슐린), **최근 HbA1c 값과 측정일**\n- 저혈당 병력, 최근 식사 시각, 합병증(신·망막·신경병증)\n\n**② 필요 시 당일 혈당 측정**\n- 증상이 있거나 장시간 처치 예정이면 처치 전 측정\n- 저혈당 대비(경구 포도당) 준비\n\n**③ 예약 조정**\n- 오전, 식사·투약 후 시간대를 우선\n- 장시간 처치는 나누어 계획',
    criteria: '- **HbA1c 7.0% 미만** 양호 / **7.0–8.0%** 중등도 / **8.0% 초과** 불량 — 문헌에서 통용되는 구분\n- 조절 양호군의 임플란트 생존율은 **5년 95–96%, 10년 92–94%** 수준으로 비당뇨군과 유사하게 보고된다\n- **HbA1c 8% 초과**에서는 변연골 소실·탐침 깊이 등 임플란트 주위 지표가 나빠진다',
    interpretation: '- 당뇨 자체가 금기가 아니라 **조절 상태가 변수**다. 수치를 기록하고 그 위에서 판단한다\n- HbA1c 가 오를수록 임상·방사선 결과가 나빠지는 **용량-반응 경향**이 보고된다(근거 수준은 중등도)\n- 조절이 불량하면: 침습 처치를 미루고 내과 협진, 치주 치료·감염 관리 우선, 임플란트는 조절 후 재평가\n- 치주염과 당뇨는 양방향 관계 — **치주 치료가 혈당 지표를 개선**할 수 있다는 점을 설명에 포함',
    pitfalls: '<div class="warning"><b>⚠️ 흔한 오류</b>① “당뇨 있음”만 기록하고 <b>수치·측정일</b> 없음 ② 공복 혈당 한 번으로 조절 상태 판단 ③ 저혈당 대비 없이 장시간 처치 ④ 수치가 나쁜데 <b>임플란트를 그대로 진행</b>.</div>'
  },
  {
    title: '두경부 방사선치료 병력 및 ORN 위험 평가',
    category: '전신 평가', order: 6,
    source: 'ISOO-MASCC-ASCO Guideline / 발치 후 ORN 체계적 문헌고찰',
    purpose: '- 방사선 조사 부위의 **발치·수술 위험**을 판정\n- 조사 전이라면 **미리 정리**하고, 조사 후라면 침습을 최소화한다',
    technique: '**① 방사선 정보를 확보한다**\n- **총 선량(Gy)**, 조사 범위(악골 포함 여부), 조사 종료 시점, 분할 방식\n- 가능하면 방사선종양학과 기록에서 **해당 부위 선량**을 확인 — “머리에 방사선 받았다”만으로는 판단할 수 없다\n\n**② 구강 상태 평가**\n- 우식(방사선 우식은 치경부·절단연에 급속 진행), 치주 상태, 잔존 치근\n- **타액 분비량**, 구강건조·점막 상태, 개구량(섬유화에 의한 제한)\n- 노출골·부골·누공 유무\n\n**③ 조사 전이라면**\n- 예후 불량 치아는 **조사 시작 전에 발치**하고 치유 기간(통상 2–3주 이상)을 확보\n- 불소 도포·구강위생 프로그램, 의치 조정 계획',
    criteria: '- ORN 위험이 뚜렷하게 올라가는 선량은 <mark style="background:#fef08a">60 Gy 이상</mark> — 보고된 ORN 사례의 약 96% 가 해당 부위 60 Gy 이상에서 발생했다\n- 조사 후 발치에서의 ORN 발생률은 **약 7%** 로 보고된다(예방적 고압산소 병용 4%, 항생제 병용 6%)\n- **하악**이 상악보다 위험이 크다',
    interpretation: '- 위험이 가장 큰 조합은 **하악 + 60 Gy 초과 + 조사 후 발치**다. 이 조합에서는 대안을 먼저 검토한다(근관치료 후 치관 절제 등)\n- 발치가 불가피하면 **외상 최소화·1차 봉합·치조골 성형·한 번에 적은 개수·주술기 항생제**가 권고된다\n- 흡연·음주 지속은 위험을 더 높인다 — 기록하고 중재한다\n- 고압산소요법의 예방 효과는 **논쟁적**이며 일상적 적용은 권고되지 않는다',
    pitfalls: '<div class="warning"><b>⚠️ 흔한 오류</b>① 선량·조사 부위를 확인하지 않고 <b>병력만으로</b> 판단 ② 조사 전 정리 기회를 놓치고 조사 후 발치 ③ 방사선 우식을 일반 우식처럼 관리 ④ 개구 제한을 기록하지 않아 보철 계획이 어긋남.</div>'
  },
  {
    title: '전신질환의 구강 발현 스크리닝',
    category: '전신 평가', order: 7,
    source: "Burket's Oral Medicine / Neville, Oral and Maxillofacial Pathology",
    purpose: '- 구강 소견에서 **아직 진단되지 않은 전신질환**의 단서를 잡는다\n- 치과 치료의 실패 원인이 구강 밖에 있는 경우를 놓치지 않는다',
    technique: '**① 점막의 색과 출혈 양상**\n- **창백**(빈혈), **점상출혈·반상출혈**(혈소판·응고 이상), 자발 치은 출혈\n- 황달, 색소침착(부신기능저하·약물)\n\n**② 혀와 구강 건조**\n- 위축성 설염·설유두 소실(철·엽산·B12 결핍)\n- **구강건조**(쇼그렌·약물·방사선), 우식 급증 양상\n\n**③ 감염과 치유**\n- 반복되는 **칸디다증**·치주 농양·치유 지연 → 당뇨·면역저하 의심\n- 아프타성 궤양의 반복 → 혈액질환·염증성 장질환·베체트\n\n**④ 치은과 치주**\n- **약물성 치은 증식**(칼슘길항제·페니토인·사이클로스포린)\n- 급속 진행 치주염 → 당뇨·면역 이상\n\n**⑤ 골과 방사선 소견**\n- 치조백선 소실·부유치 양상, 다발성 방사선투과상\n\n**⑥ 약물 목록을 함께 본다** — 구강 소견의 상당수는 질환이 아니라 **약물의 결과**다',
    criteria: '- 소견은 **관찰한 그대로** 기록한다(부위·크기·색·수·경과)\n- “의심된다”는 표현과 **확인된 사실**을 구분해 적는다\n- 전신 증상(체중 감소·발열·야간 발한·피로)을 함께 청취해 기록',
    interpretation: '- 구강 소견은 **비특이적인 경우가 많다.** 하나의 소견으로 진단하지 않고 <b>패턴</b>으로 본다\n- 치과에서 하는 일은 진단이 아니라 **의뢰 판단**이다 — 무엇을 보고 왜 의뢰하는지 기록에 남긴다\n- 보철 치료 계획에 직접 영향을 주는 것들: 구강건조(우식·의치 유지), 점막 취약(의치 통증), 출혈 경향(침습 처치), 면역저하(감염)\n- 의뢰 후 **회신 내용을 기록에 반영**하고 치료 계획을 갱신한다',
    pitfalls: '<div class="warning"><b>⚠️ 흔한 오류</b>① 약물 목록을 받지 않아 <b>약물 유발 소견을 질환으로</b> 오인 ② 반복되는 칸디다증·치유 지연을 국소 문제로만 처리 ③ 의뢰만 하고 <b>회신을 확인하지 않음</b> ④ 소견을 “특이사항 없음”으로 뭉뚱그림.</div>'
  },
  {
    title: '소아 맹출·치열 발육 단계 평가',
    category: '소아·성장', order: 1,
    source: 'McDonald & Avery, Dentistry for the Child and Adolescent / AAPD',
    purpose: '- 연령에 맞는 **치열 단계**를 확인하고 이탈을 잡아낸다\n- 보철·교정·수복 계획의 시기를 정하는 근거',
    technique: '**① 치열 단계를 판정한다**\n- **유치열기** → **혼합치열기(전기·후기)** → **영구치열기**\n- 구강 내 맹출 치아를 치식으로 기록하고, 좌우·상하 **대칭성**을 본다\n\n**② 맹출 시기와 순서를 확인한다**\n- 좌우 동명치의 맹출 시차가 크면(통상 **6개월 이상**) 원인을 찾는다\n- 순서 이상(예: 견치가 소구치보다 먼저)도 기록\n\n**③ 공간을 계측한다**\n- 유치열의 **영장 간극·발육 간극** 유무\n- 조기 상실 부위의 **공간 소실** 여부 — 인접치 경사·정중선 변위\n- 필요 시 모형 계측(치아 크기–악궁 길이 부조화)\n\n**④ 방사선**\n- 파노라마로 **미맹출 치배의 유무·위치·발육 단계**, 과잉치, 매복, 치근 흡수 상태 확인',
    criteria: '- 유치는 대략 생후 6개월경 시작해 **2세 반–3세경 완성**, 영구치는 **6세경 제1대구치·하악 중절치**부터 시작한다(개인차가 크다)\n- **맹출 지연 판단은 평균값보다 좌우 대칭성과 방사선 소견**으로 한다\n- 유치 조기 상실 시 **공간유지의 필요 여부**를 부위·잔여 맹출 기간·공간 상태로 판단',
    interpretation: '- **평균 맹출 시기는 참고값이다.** 6–12개월의 편차는 흔하며, 문제는 <b>비대칭</b>과 <b>정지</b>다\n- 좌우 차이가 크거나 예상 시기를 크게 지나면: 과잉치, 매복, 유착, 치배 결손, 낭종, 전신 원인(내분비·증후군)을 감별\n- 유치 조기 상실은 **공간 소실 → 영구치 총생**으로 이어질 수 있으므로 공간 관리 계획을 명시\n- 성장기 환자에서 **임플란트는 성장 완료 후**가 원칙 — 계획 단계에서 미리 설명한다',
    pitfalls: '<div class="warning"><b>⚠️ 흔한 오류</b>① 평균 시기와 다르다는 이유만으로 <b>이상으로 판단</b> ② 좌우 비대칭을 지나침 ③ 방사선 없이 맹출 지연을 결론 ④ 유치 조기 상실 후 <b>공간 평가 없이</b> 경과 관찰.</div>'
  },
  {
    title: '소아 협조도·행동 평가 (Frankl 척도)',
    category: '소아·성장', order: 2,
    source: 'AAPD Behavior Guidance Guideline / Frankl 1962',
    purpose: '- 진료 계획과 **행동 조절 방법**을 정하기 위한 객관적 기록\n- 회차별 변화를 비교할 수 있는 공통 언어를 만든다',
    technique: '**① 첫 내원부터 등급을 기록한다**\n- 대기실·진료실 진입·기구 노출 각 시점의 반응을 관찰\n- 보호자와의 분리 반응, 지시 수용 정도\n\n**② 등급을 매기고 근거를 함께 적는다**\n- 숫자만 적으면 다음 술자가 해석할 수 없다 — **무엇을 보고 그렇게 판정했는지** 한 줄\n\n**③ 함께 기록할 것**\n- 연령·발달 수준, 이전 치과 경험, 보호자의 불안 수준\n- 성공한 접근법(tell-show-do, 강화, 음성 조절)과 실패한 접근법',
    criteria: '**Frankl 행동 등급**\n- **1 (definitely negative)** — 강한 거부, 울음, 치료 거절\n- **2 (negative)** — 마지못해 수용, 비협조적 태도\n- **3 (positive)** — 수용적, 조심스럽지만 지시를 따름\n- **4 (definitely positive)** — 좋은 관계, 적극적 협조\n\n기록 예: <b>Frankl 2 — 기구 노출 시 회피, 보호자 설득으로 개구 가능</b>',
    interpretation: '- **1–2 등급**: 처치 범위를 줄이고 적응 위주 내원, 행동 조절 기법 계획, 필요 시 진정·전신마취 상담\n- **3–4 등급**: 통상 진료 가능. 다만 **처치 길이와 통증 관리**가 등급을 떨어뜨릴 수 있다\n- 등급은 고정된 성격이 아니라 **상황 반응**이다 — 회차별로 다시 매긴다\n- 보호자의 불안이 아동에게 전이되는 경우가 흔하다. 보호자 대응 계획도 함께 기록',
    pitfalls: '<div class="warning"><b>⚠️ 흔한 오류</b>① 등급만 적고 <b>근거를 안 적음</b> ② 한 번의 등급을 그 환자의 성격으로 고정 ③ 실패한 접근법을 기록하지 않아 <b>같은 실수를 반복</b> ④ 통증 조절 실패를 협조도 문제로 기록.</div>'
  },
];
