/* ─────────────────────────────────────────────────────────────
 * 차팅 용어 — 한국어 임상 표현 → 영어 차팅 표현
 *
 * 목적은 번역이 아니라 "어느 단어를 골라야 하는가"의 감별.
 * 한 표현이 대상·원인에 따라 다른 영어 단어가 되는 지점을 중심으로 정리한다.
 *
 * section 태그
 *   O  — 관찰·기술 용어. 진단이 아님
 *   A  — 진단·판정 용어
 *   O·A — 맥락에 따라 양쪽
 *
 * 각 항목
 *   meaning  — 무엇을 가리키는가
 *   variants — 갈리는 지점(대상·원인별로 다른 단어)
 *   example  — 실제 차팅 문장
 *   caution  — 혼동·오용 주의
 * ───────────────────────────────────────────────────────────── */

const TERM_CATS = ['연조직', '치아·수복물', '치주', '치수·치근단', '교합·악관절', '의치', '임플란트', '방사선'];
const TERM_SEED_VERSION = 1;

const TERM_SEED = [
  // ═══════════ 연조직 ═══════════
  { ko: '협점막 백선', en: 'linea alba', section: 'O', category: '연조직', order: 1,
    meaning: '교합면 높이를 따라 협점막에 나타나는 흰 선상 각화. 양측성이 흔하다.',
    example: 'Linea alba present bilaterally along the occlusal plane.',
    caution: '**소견이지 진단이 아니다.** parafunction의 간접 징후로 해석할 수는 있으나 O에는 관찰만 적고, 이갈이 판단은 A로 보낸다. 병적 백색병변(leukoplakia)과 반드시 구분해 기술할 것.' },
  { ko: '혀 압흔', en: 'tongue scalloping (crenated tongue)', section: 'O', category: '연조직', order: 2,
    meaning: '혀 측연에 치아 압흔이 남은 상태.',
    example: 'Tongue scalloping noted on lateral borders.',
    caution: 'linea alba와 함께 parafunction·거대설·기도 문제의 간접 단서로 쓰이나, 단독으로 진단 근거가 되지 않는다.' },
  { ko: '궤양', en: 'ulcer / ulceration', section: 'O', category: '연조직', order: 3,
    meaning: '상피가 소실되어 하부 결합조직이 노출된 병소.',
    variants: '<dl><dt>ulcer</dt><dd>병소 자체(명사)</dd><dt>ulceration</dt><dd>궤양이 생긴 상태·과정</dd><dt>erosion</dt><dd>상피 일부만 소실(연조직 맥락). <b>치아의 침식과 동음이의</b>이므로 문맥을 분명히</dd></dl>',
    example: 'Linear ulcer 4 x 2 mm on the left mylohyoid ridge area, surrounded by erythema.',
    caution: '크기·형태·위치를 반드시 함께 — `linear` / `round` / `irregular`, mm 단위.' },
  { ko: '발적', en: 'erythema / redness', section: 'O', category: '연조직', order: 4,
    meaning: '점막·치은의 붉은 변화.',
    variants: '<dl><dt>localized erythema</dt><dd>국소</dd><dt>diffuse erythema</dt><dd>미만성 — 의치성 구내염 Newton II의 기술</dd></dl>',
    example: 'Diffuse erythema of the palatal mucosa corresponding to the denture-bearing area.' },
  { ko: '부종', en: 'edema / swelling', section: 'O', category: '연조직', order: 5,
    meaning: '조직의 종창.',
    variants: '<dl><dt>edema</dt><dd>조직 내 체액 증가(기술적)</dd><dt>swelling</dt><dd>육안으로 부어오른 상태(일반)</dd><dt>fluctuant swelling</dt><dd>파동감 있는 종창 — 농양 시사</dd></dl>',
    example: 'Localized fluctuant swelling in the buccal vestibule adjacent to #24.' },
  { ko: '경결 / 파동감', en: 'induration / fluctuance', section: 'O', category: '연조직', order: 6,
    meaning: '촉진 시 단단함(경결) / 액체가 만져지는 물렁함(파동감).',
    example: 'Fluctuance(+) on palpation; no induration.',
    caution: '**induration은 악성 병변의 경고 소견**이기도 하다. 궤양이 2주 이상 지속되며 경결이 동반되면 조직검사 의뢰를 고려한다.' },
  { ko: '창백해짐', en: 'blanching', section: 'O', category: '연조직', order: 7,
    meaning: '압박으로 혈류가 차단되어 조직이 하얗게 되는 것.',
    example: 'Mild blanching on abutment seating, resolved within 3 minutes.',
    caution: '보철·abutment 장착 시 확인 항목. **수분 내 회복되지 않으면 과압박**이므로 조정한다.' },
  { ko: '증식 조직', en: 'hyperplastic tissue', section: 'O', category: '연조직', order: 8,
    meaning: '만성 자극으로 증식한 연조직.',
    variants: '<dl><dt>epulis fissuratum</dt><dd>의치 변연에 의한 <b>주름형 증식</b> — 원인이 명확할 때</dd><dt>papillary hyperplasia</dt><dd>구개의 <b>유두상 증식</b> — 의치성 구내염 Newton III</dd><dt>hyperplastic tissue</dt><dd>원인·형태 불특정 시</dd></dl>',
    example: 'Epulis fissuratum along the labial flange of the maxillary denture.' },
  { ko: '구각염', en: 'angular cheilitis', section: 'O·A', category: '연조직', order: 9,
    meaning: '구각부의 균열·발적·가피.',
    example: 'Angular cheilitis present bilaterally.',
    caution: 'VDO 감소·칸디다 감염·영양 결핍과 연관될 수 있다. **O에는 소견만**, 원인 추정은 A로.' },
  { ko: '누공', en: 'sinus tract', section: 'O', category: '연조직', order: 10,
    meaning: '농이 배출되는 통로가 점막으로 열린 것.',
    variants: '<dl><dt>sinus tract</dt><dd>구강 내로 열린 배농로 — <b>치과에서 통상 쓰는 표현</b></dd><dt>fistula</dt><dd>엄밀히는 두 상피면을 잇는 통로. 흔히 혼용되나 sinus tract가 정확</dd></dl>',
    example: 'Sinus tract at the mucogingival junction of #36; gutta-percha tracing to the mesial root apex.',
    caution: '**치은변연 가까이** 열린 누공은 치주 기원 또는 **수직치근파절**을 시사한다 — 위치를 반드시 기재.' },
  { ko: '구강건조', en: 'xerostomia / hyposalivation', section: 'O·A', category: '연조직', order: 11,
    meaning: '입 마름.',
    variants: '<dl><dt>xerostomia</dt><dd><b>환자가 호소하는 주관적 건조감</b> → S에 가깝다</dd><dt>hyposalivation</dt><dd><b>객관적으로 측정된 타액 감소</b> → O</dd></dl>',
    example: 'Saliva viscous and scant; patient reports dry mouth (xerostomia). Suspected medication-induced hyposalivation.',
    caution: '두 단어를 구분하면 S와 O가 자연스럽게 나뉜다.' },
  { ko: '압통', en: 'tenderness to palpation', section: 'O', category: '연조직', order: 12,
    meaning: '촉진 시 통증.',
    example: 'Masseter tender to palpation bilaterally; temporalis NT.',
    caution: '약어 **TTP**(tender to palpation), **NT**(non-tender)가 흔히 쓰인다. 근육 촉진에서는 **referred pain(연관통)** 유무를 함께 기재.' },

  // ═══════════ 치아·수복물 ═══════════
  { ko: '보철물 탈락', en: 'decementation / debonding / dislodgement', section: 'A', category: '치아·수복물', order: 1,
    meaning: '보철물이 지대치에서 떨어진 것. **원인에 따라 단어가 다르다.**',
    variants: '<dl><dt>decementation</dt><dd><b>시멘트 실패</b> — 보철물은 온전하고 시멘트 계면에서 탈락</dd><dt>debonding</dt><dd><b>접착(레진) 실패</b> — 베니어·접착성 보철·교정 브라켓</dd><dt>dislodgement</dt><dd>원인 불문 <b>일반 표현</b></dd></dl>',
    example: 'Decementation of #46 full gold crown secondary to recurrent caries at the distal margin.',
    caution: '차팅에서는 **원인까지 붙이는 것이 표준**이다 — `secondary to recurrent caries` / `due to inadequate retention form`. “fell out” 같은 구어체는 쓰지 않는다.' },
  { ko: '이차우식', en: 'secondary caries / recurrent caries', section: 'A', category: '치아·수복물', order: 2,
    meaning: '기존 수복물 변연에 새로 생긴 우식.',
    example: 'Recurrent caries at the distal margin of #46 crown.',
    caution: '**진단(A)** 이다. O에는 `marginal radiolucency`, `explorer catch`, `softened dentin` 같은 **소견**으로 적는다.' },
  { ko: '변연에 걸린다', en: 'explorer catch', section: 'O', category: '치아·수복물', order: 3,
    meaning: '탐침이 변연에서 걸리는 촉감.',
    example: 'Explorer catch(+) at the distal margin of #46 crown.',
    caution: '이것은 **소견**이고, 그로부터 내리는 판단(이차우식·변연 부적합)은 A다.' },
  { ko: '변연 부적합', en: 'marginal discrepancy', section: 'O', category: '치아·수복물', order: 4,
    meaning: '보철물 변연이 치아와 맞지 않음.',
    variants: '<dl><dt>open margin</dt><dd>변연이 뜬 상태(간극)</dd><dt>overhang</dt><dd>변연이 <b>과충전되어 튀어나온</b> 상태</dd><dt>underhang / deficient margin</dt><dd>변연이 <b>부족한</b> 상태</dd><dt>marginal gap</dt><dd>간극의 정량 표현(μm)</dd></dl>',
    example: 'Open margin with detectable gap at the mesial of #26 crown on PA.' },
  { ko: '도재 파절', en: 'porcelain chipping / fracture', section: 'O', category: '치아·수복물', order: 5,
    meaning: '도재부의 깨짐.',
    variants: '<dl><dt>chipping</dt><dd><b>작은 조각</b>이 떨어져 나감 — 하부구조 노출 없음</dd><dt>fracture</dt><dd>더 큰 파절, 흔히 <b>하부구조(코어) 노출</b> 동반</dd><dt>delamination</dt><dd>도재가 하부구조에서 <b>박리</b></dd></dl>',
    example: 'Porcelain chipping at the mesiolingual cusp of #36 crown; framework not exposed.' },
  { ko: '균열선', en: 'craze line', section: 'O', category: '치아·수복물', order: 6,
    meaning: '법랑질 내에 국한된 미세 균열. 대개 무증상.',
    example: 'Craze lines visible on the buccal surface of #14 under transillumination.',
    caution: '**craze line(법랑질 내, 무증상)** 과 **cracked tooth(상아질까지, 증상 동반)** 는 예후가 완전히 다르다 — 섞어 쓰지 말 것.' },
  { ko: '균열치', en: 'cracked tooth', section: 'A', category: '치아·수복물', order: 7,
    meaning: '상아질까지 진행된 균열로 증상을 동반하는 상태.',
    variants: '<dl><dt>cracked tooth</dt><dd>불완전 균열, 증상 동반</dd><dt>split tooth</dt><dd><b>완전히 분리</b>된 상태</dd><dt>cuspal fracture</dt><dd>교두 파절</dd></dl>',
    example: 'Cracked tooth #37 — positive bite test on the mesiolingual cusp with rebound pain.',
    caution: '**보철 전에 반드시 배제**해야 하는 진단이다. 놓치면 크라운 완성 후 치아가 갈라진다.' },
  { ko: '수직치근파절', en: 'vertical root fracture (VRF)', section: 'A', category: '치아·수복물', order: 8,
    meaning: '치근을 장축 방향으로 가르는 파절. **원칙적으로 수복 불가.**',
    example: 'VRF suspected at #25 — isolated narrow probing defect 9 mm on the buccal with J-shaped radiolucency.',
    caution: '결정적 소견 3가지를 함께 기재 — **isolated deep narrow pocket**, **J-shaped / halo radiolucency**, **sinus tract near the gingival margin**.' },
  { ko: '마모면', en: 'wear facet', section: 'O', category: '치아·수복물', order: 9,
    meaning: '마모로 생긴 평탄면.',
    example: 'Wear facets on #13, 23 with matching antagonist contacts.',
    caution: '**대합치와 일치하는지(matching)** 를 반드시 함께 적는다 — 일치하면 attrition을 시사한다. 마모의 원인 판정은 A로.' },
  { ko: '치아 마모 (원인별)', en: 'attrition / erosion / abrasion', section: 'A', category: '치아·수복물', order: 10,
    meaning: '치질 소실의 원인별 진단명.',
    variants: '<dl><dt>attrition</dt><dd><b>치아 간 접촉</b>에 의한 마모 — 대합면과 일치하는 평탄 facet</dd><dt>erosion</dt><dd><b>산</b>에 의한 화학적 소실 — cupping, 구개면 함몰, <b>수복물이 솟아 보임</b></dd><dt>abrasion</dt><dd><b>외부 마찰</b>(칫솔 등) — 치경부 wedge-shaped 결손</dd><dt>abfraction</dt><dd>교합 응력에 의한 치경부 소실이라는 <b>가설적 개념</b> — 논쟁이 있음</dd></dl>',
    example: 'Generalized erosion with cupping of occlusal surfaces; restorations standing proud of adjacent tooth structure.',
    caution: '“수복물이 주위 치질보다 솟아 보인다”는 **erosion의 특징적 소견**이다.' },
  { ko: '쐐기형 결손', en: 'wedge-shaped cervical defect', section: 'O', category: '치아·수복물', order: 11,
    meaning: '치경부의 쐐기 모양 결손.',
    example: 'Wedge-shaped cervical defects on #34, 35 with exposed dentin.',
    caution: '`abfraction lesion`은 **원인을 전제한 표현**이므로, O에는 형태 기술(wedge-shaped defect)로 남기는 편이 안전하다.' },
  { ko: '컵 모양 함몰', en: 'cupping', section: 'O', category: '치아·수복물', order: 12,
    meaning: '교두정·절단연에 생긴 오목한 함몰. 침식의 전형적 형태.',
    example: 'Cupping of the cusp tips on #16, 26.' },
  { ko: '정출', en: 'supraeruption (overeruption)', section: 'O', category: '치아·수복물', order: 13,
    meaning: '대합치 결손으로 치아가 교합평면을 넘어 맹출한 상태.',
    example: 'Supraeruption of #17 into the edentulous space of #47.',
    caution: '보철 공간 부족의 흔한 원인 — **available interocclusal space**와 함께 기재.' },
  { ko: '경사', en: 'tipping / tilting', section: 'O', category: '치아·수복물', order: 14,
    meaning: '치아 장축이 기울어진 상태.',
    example: 'Mesial tipping of #37 into the #36 edentulous space.',
    caution: 'RPD에서는 **착탈로·guide plane 설계**에 직접 영향을 준다.' },
  { ko: '식편압입', en: 'food impaction', section: 'O·A', category: '치아·수복물', order: 15,
    meaning: '인접부에 음식물이 끼어 들어가는 것.',
    example: 'Food impaction reported at the mesial of #46 implant crown; proximal contact loss confirmed with floss.',
    caution: '**원인 소견(proximal contact loss)** 을 함께 적어야 처치가 이어진다. 임플란트 보철에서는 인접 자연치 이동으로 시간이 지나 새로 생긴다.' },
  { ko: '인접 접촉 상실', en: 'proximal contact loss / open contact', section: 'O', category: '치아·수복물', order: 16,
    meaning: '인접 접촉이 없어 치실이 저항 없이 통과하는 상태.',
    example: 'Open contact at the mesial of #46 — floss passes without resistance.' },
  { ko: '착색 / 변색', en: 'staining / discoloration', section: 'O', category: '치아·수복물', order: 17,
    meaning: '외인성 착색 / 내인성 변색.',
    variants: '<dl><dt>extrinsic staining</dt><dd>표면 착색(커피·흡연) — 제거 가능</dd><dt>intrinsic discoloration</dt><dd>치질 내부의 변색(연령·테트라사이클린·외상) — 미백·수복 대상</dd></dl>',
    example: 'Generalized intrinsic discoloration, uniform yellow; no banded pattern.' },
  { ko: '지각과민', en: 'dentin hypersensitivity', section: 'A', category: '치아·수복물', order: 18,
    meaning: '노출 상아질에 대한 자극으로 유발되며 자극 제거 시 즉시 소실되는 단시간 통증.',
    example: 'Dentin hypersensitivity #34, 35 — sharp response to cold resolving immediately on stimulus removal.',
    caution: '**자극 제거 후 지속되면 지각과민이 아니다** — 비가역성 치수염·균열치를 먼저 배제할 것.' },

  // ═══════════ 치주 ═══════════
  { ko: '탐침 깊이', en: 'probing depth (PD)', section: 'O', category: '치주', order: 1,
    meaning: '치은연에서 열구·낭 기저부까지의 깊이.',
    example: 'PD 3-3-4 / 3-3-5 mm at #46.',
    caution: '**PD와 CAL은 다르다.** 퇴축이 있으면 PD가 얕아도 부착 소실은 클 수 있다 — 둘 다 기재.' },
  { ko: '탐침 시 출혈', en: 'bleeding on probing (BOP)', section: 'O', category: '치주', order: 2,
    meaning: '탐침 후 출혈 여부. 전악 백분율로도 표기.',
    example: 'BOP(+) at #46 buccal; full-mouth BOP 12%.',
    caution: '**탐침 10–30초 후** 판정한다. BOP(−)는 안정의 음성 예측에 유용하지만, BOP(+) 하나만으로 진행을 단정하지 않는다.' },
  { ko: '부착 소실', en: 'clinical attachment loss (CAL)', section: 'O', category: '치주', order: 3,
    meaning: 'CEJ에서 부착 기저부까지의 거리. 실제 지지 소실량.',
    example: 'CAL 6 mm at #36 mesial.' },
  { ko: '퇴축', en: 'gingival recession (GR)', section: 'O', category: '치주', order: 4,
    meaning: '치은연이 CEJ보다 근단측으로 이동한 상태.',
    example: 'GR 2 mm on the buccal of #34, 35.' },
  { ko: '동요', en: 'mobility', section: 'O', category: '치주', order: 5,
    meaning: '치아의 흔들림. **대상에 따라 완전히 다른 단어를 쓴다.**',
    variants: '<dl><dt>치아</dt><dd><b>mobility</b> (Miller Class I–III)</dd><dt>임플란트 나사</dt><dd><b>screw loosening</b> — 임플란트 자체의 mobility는 골유착 실패를 뜻한다</dd><dt>의치</dt><dd><b>instability</b> / <b>loss of retention</b></dd><dt>보철물</dt><dd><b>decementation</b> (탈락) / <b>rocking</b> (미안착)</dd></dl>',
    example: 'Mobility Class II at #35.',
    caution: '“흔들린다”를 전부 mobility로 옮기면 임플란트·의치 기록이 완전히 틀어진다.' },
  { ko: '근분지부 병소', en: 'furcation involvement', section: 'O·A', category: '치주', order: 6,
    meaning: '다근치의 근분지부에 부착이 소실된 상태.',
    example: 'Furcation involvement Grade II on the buccal of #36 (Glickman).',
    caution: '분류 체계(**Glickman I–IV** / Hamp I–III)를 명시할 것.' },
  { ko: '각화치은', en: 'keratinized tissue (KT)', section: 'O', category: '치주', order: 7,
    meaning: '치은연에서 MGJ까지의 각화된 조직 폭.',
    example: 'KT width 2 mm on the buccal of #46 implant.',
    caution: '임플란트에서 **2 mm 미만**이면 위생 관리와 점막 건강에 불리하다는 보고가 축적되어 있다.' },
  { ko: '치은 비대', en: 'gingival enlargement / overgrowth', section: 'O', category: '치주', order: 8,
    meaning: '치은 조직의 증대.',
    example: 'Generalized gingival enlargement, drug-associated pattern suspected.',
    caution: '`hyperplasia`는 조직학적 용어이므로 임상 기술에는 **enlargement / overgrowth**가 적절하다.' },
  { ko: '가성낭', en: 'pseudopocket', section: 'A', category: '치주', order: 9,
    meaning: '부착 소실 없이 치은 비대만으로 깊어진 낭.',
    example: 'Pseudopockets 4–5 mm with CAL within normal limits.' },
  { ko: '치태 / 치석', en: 'plaque (biofilm) / calculus', section: 'O', category: '치주', order: 10,
    meaning: '연성 세균막 / 석회화된 침착물.',
    example: 'Heavy supragingival calculus on the lingual of the mandibular anteriors; plaque score 70%.',
    caution: '`supragingival`(치은연상) / `subgingival`(치은연하)를 함께 적는다.' },
  { ko: '배농', en: 'suppuration / purulent exudate', section: 'O', category: '치주', order: 11,
    meaning: '농이 나오는 것.',
    example: 'Suppuration on probing at #36 distal.' },
  { ko: '진동 (교합 외상)', en: 'fremitus', section: 'O', category: '치주', order: 12,
    meaning: '기능 접촉 시 치아에서 느껴지는 진동. 손가락을 순면에 대고 폐구시켜 확인.',
    example: 'Fremitus detected on #11, 21 during tapping.',
    caution: '교합 외상의 임상 지표. **mobility와 다른 소견**이므로 별도로 기재.' },
  { ko: '생물학적 폭경 침범', en: 'violation of the supracrestal tissue attachment', section: 'A', category: '치주', order: 13,
    meaning: '수복 변연이 부착 조직 영역을 침범한 상태.',
    example: 'Violation of the supracrestal tissue attachment at the distal of #46 — bone sounding 1.5 mm from the planned margin.',
    caution: '**2017 World Workshop 이후 공식 용어가 supracrestal tissue attachment**로 정리되었다. `biologic width`는 구용어로, 병용하더라도 새 용어를 우선한다.' },

  // ═══════════ 치수·치근단 ═══════════
  { ko: '자극 후 지속통', en: 'lingering pain', section: 'O', category: '치수·치근단', order: 1,
    meaning: '자극을 제거한 뒤에도 통증이 지속되는 것.',
    example: 'Cold test #36: lingering pain persisting approximately 20 seconds after stimulus removal.',
    caution: '**비가역성 치수염을 가르는 핵심 소견.** 지속 시간을 초 단위로 적는다.' },
  { ko: '자발통 / 야간통', en: 'spontaneous pain / nocturnal pain', section: 'O', category: '치수·치근단', order: 2,
    meaning: '유발 자극 없이 발생하는 통증 / 야간에 악화되는 통증.',
    example: 'Patient reports spontaneous, nocturnal pain unrelieved by analgesics.' },
  { ko: '가역성 치수염', en: 'reversible pulpitis', section: 'A', category: '치수·치근단', order: 3,
    meaning: '자극 시에만 통증이 있고 제거 시 즉시 소실되는 치수 염증.',
    example: 'Reversible pulpitis #16.' },
  { ko: '비가역성 치수염', en: 'symptomatic irreversible pulpitis', section: 'A', category: '치수·치근단', order: 4,
    meaning: '지속통·자발통을 동반해 치수 회복이 기대되지 않는 상태.',
    example: 'Symptomatic irreversible pulpitis with symptomatic apical periodontitis, #36.',
    caution: '**증상 유무를 접두어로 명시**하는 것이 현행 표준 표기다 — `symptomatic` / `asymptomatic`.' },
  { ko: '치수 괴사', en: 'pulp necrosis', section: 'A', category: '치수·치근단', order: 5,
    meaning: '치수 조직이 괴사한 상태.',
    example: 'Pulp necrosis #21 with asymptomatic apical periodontitis.' },
  { ko: '치근단 치주염', en: 'apical periodontitis', section: 'A', category: '치수·치근단', order: 6,
    meaning: '치근단 조직의 염증.',
    variants: '<dl><dt>symptomatic apical periodontitis</dt><dd>타진통·저작통 동반</dd><dt>asymptomatic apical periodontitis</dt><dd>무증상, 방사선 병소만</dd><dt>acute apical abscess</dt><dd>급성 농양 — 부종·배농·전신 증상 가능</dd><dt>chronic apical abscess</dt><dd>만성 — <b>sinus tract 동반</b></dd></dl>',
    example: 'Asymptomatic apical periodontitis #35 — well-defined periapical radiolucency, Perc(−).' },
  { ko: '방사선 투과상', en: 'radiolucency', section: 'O', category: '치수·치근단', order: 7,
    meaning: '방사선상 어둡게 보이는 영역.',
    example: 'Well-defined periapical radiolucency approximately 4 mm in diameter at the apex of #35.',
    caution: '**소견(O)** 이다. 이를 근거로 붙이는 진단명(apical periodontitis 등)은 A로 간다. 경계(well-defined / diffuse)와 크기를 함께.' },

  // ═══════════ 교합·악관절 ═══════════
  { ko: '조기접촉', en: 'premature contact', section: 'O', category: '교합·악관절', order: 1,
    meaning: '다른 치아보다 먼저 닿는 접촉.',
    example: 'Premature contact at the mesial incline of #36 in centric relation.' },
  { ko: '간섭', en: 'interference', section: 'O', category: '교합·악관절', order: 2,
    meaning: '편심 운동을 방해하는 접촉.',
    variants: '<dl><dt>working interference</dt><dd>작업측 간섭</dd><dt>non-working (balancing) interference</dt><dd>비작업측 간섭 — <b>원칙적으로 제거</b></dd><dt>protrusive interference</dt><dd>전방운동 간섭</dd></dl>',
    example: 'Non-working interference on the mesiolingual cusp of #26 during left lateral excursion.' },
  { ko: '활주', en: 'slide (CR–MIP slide)', section: 'O', category: '교합·악관절', order: 3,
    meaning: '중심위에서 최대교두감합위로 이동하는 거리.',
    example: 'CR–MIP slide 1.0 mm in the anterior direction.',
    caution: '**방향과 양(mm)** 을 함께 기재한다.' },
  { ko: '견치 유도 / 군기능', en: 'canine guidance / group function', section: 'O', category: '교합·악관절', order: 4,
    meaning: '측방 운동 시 유도를 담당하는 치아 양식.',
    example: 'Group function on the right; canine guidance on the left.' },
  { ko: '개구 제한', en: 'limited (restricted) mouth opening', section: 'O', category: '교합·악관절', order: 5,
    meaning: '최대 개구가 정상 범위 미만인 상태.',
    example: 'Maximum opening 32 mm — restricted.',
    caution: '통상 **40 mm 미만**을 제한으로 본다. 무통 개구와 최대 개구를 구분해 기재.' },
  { ko: '편위 / 편향', en: 'deviation / deflection', section: 'O', category: '교합·악관절', order: 6,
    meaning: '개구 시 하악 정중선의 이동 양상. **두 단어의 의미가 다르다.**',
    variants: '<dl><dt>deviation</dt><dd>개구 중 편위했다가 <b>정중선으로 복귀</b> — 정복성 디스크 변위 시사</dd><dt>deflection</dt><dd>편위한 채 <b>복귀하지 않음</b> — 비정복성 변위·유착 시사</dd></dl>',
    example: 'Deflection to the left at maximum opening.',
    caution: '혼용하면 진단 방향이 반대가 된다.' },
  { ko: '관절음', en: 'joint sound: click / crepitus', section: 'O', category: '교합·악관절', order: 7,
    meaning: '악관절에서 나는 소리.',
    variants: '<dl><dt>click</dt><dd>짧고 뚜렷한 소리 — 디스크 변위 시사</dd><dt>reciprocal click</dt><dd>개구·폐구 <b>양쪽</b>에서 발생</dd><dt>crepitus</dt><dd>거친 마찰음 — <b>퇴행성 변화</b> 시사</dd></dl>',
    example: 'Opening click at the left TMJ; no crepitus.',
    caution: '**어느 시점**(opening / closing)에 나는지 기재. 무증상 click은 그 자체로 치료 대상이 아니다.' },
  { ko: '이갈이 / 이악물기', en: 'sleep bruxism / awake bruxism (clenching)', section: 'A', category: '교합·악관절', order: 8,
    meaning: '수면 중 또는 각성 중의 파라펑션 근활동.',
    example: 'Probable sleep bruxism — wear facets with matching antagonists, morning jaw stiffness, sleep partner report.',
    caution: '국제 합의는 건강한 개인에서 이를 **질환이 아니라 근활동**으로 규정한다. 확진이 어려운 경우 `probable`을 붙이는 것이 정확하다.' },
  { ko: '근막통', en: 'myalgia / myofascial pain', section: 'A', category: '교합·악관절', order: 9,
    meaning: '저작근 기원의 통증.',
    example: 'Myalgia of the masseter and temporalis bilaterally (DC/TMD).',
    caution: '**연관통(referred pain)** 이 치통으로 오인되는 일이 흔하다 — 치수 검사가 정상인데 통증이 지속되면 근육을 촉진할 것.' },
  { ko: '잠김', en: 'locking (closed / open lock)', section: 'O·A', category: '교합·악관절', order: 10,
    meaning: '하악이 특정 위치에서 움직이지 않는 상태.',
    variants: '<dl><dt>closed lock</dt><dd><b>입이 벌어지지 않음</b> — 비정복성 디스크 변위</dd><dt>open lock</dt><dd><b>입이 다물어지지 않음</b> — 과두 아탈구</dd></dl>',
    example: 'History of intermittent closed lock, currently resolved.' },

  // ═══════════ 의치 ═══════════
  { ko: '유지 / 안정 / 지지', en: 'retention / stability / support', section: 'O', category: '의치', order: 1,
    meaning: '의치 평가의 세 축. **호소를 이 셋으로 나누면 원인이 좁혀진다.**',
    variants: '<dl><dt>retention</dt><dd><b>이탈(수직 탈락)에 대한 저항</b> — “빠진다·들린다” → border seal·post-dam</dd><dt>stability</dt><dd><b>수평·회전력에 대한 저항</b> — “움직인다·돌아간다” → 교합·연마면 형태·neutral zone</dd><dt>support</dt><dd><b>수직 압력에 대한 저항</b> — “아프다” → 지지영역·과압박</dd></dl>',
    example: 'Retention poor, stability fair, support adequate for the mandibular denture.' },
  { ko: '압박부', en: 'pressure area', section: 'O', category: '의치', order: 2,
    meaning: 'PIP로 확인되는 조직면 과압박 지점.',
    example: 'Pressure area over the left mylohyoid ridge identified with PIP; relieved.' },
  { ko: '과신장 / 과소신장', en: 'over-extension / under-extension', section: 'O', category: '의치', order: 3,
    meaning: '의치 변연이 기능 범위를 넘거나 못 미치는 상태.',
    example: 'Over-extension of the left buccal border by approximately 1 mm; shortened.',
    caution: '**과신장은 선상 궤양**, **과소신장은 유지 상실**로 나타난다 — 증상과 연결해 기재.' },
  { ko: '변연 폐쇄', en: 'border seal', section: 'O', category: '의치', order: 4,
    meaning: '변연을 따라 형성되는 밀폐. 유지력의 물리적 기반.',
    example: 'Border seal intact; posterior palatal seal effective.' },
  { ko: '이장 / 개상', en: 'reline / rebase', section: 'A·P', category: '의치', order: 5,
    meaning: '의치 적합 회복 술식. **범위가 다르다.**',
    variants: '<dl><dt>reline</dt><dd><b>조직면만</b> 새 재료로 갱신</dd><dt>rebase</dt><dd><b>의치상 전체</b>를 교체하고 인공치만 유지</dd><dt>tissue conditioning</dt><dd>연조직 회복을 위한 <b>임시</b> 연성 이장</dd></dl>',
    example: 'Functional reline of the mandibular denture indicated due to distal extension settling.' },
  { ko: '의치성 구내염', en: 'denture stomatitis', section: 'A', category: '의치', order: 6,
    meaning: '의치 지지 점막의 염증.',
    example: 'Denture stomatitis, Newton type II (diffuse erythema) of the palatal mucosa.',
    caution: '**Newton 분류(I 국소 점상 / II 미만성 발적 / III 유두 증식성)** 를 함께 기재.' },
  { ko: '가동 치조제', en: 'flabby ridge (mobile ridge)', section: 'O', category: '의치', order: 7,
    meaning: '섬유성으로 변해 가동성을 가진 치조제.',
    example: 'Flabby ridge in the anterior maxilla, approximately 10 mm in span.',
    caution: '**선택적 무압인상(window technique)** 의 적응증이므로 범위를 mm로 기재.' },
  { ko: '치조제 흡수', en: 'residual ridge resorption', section: 'A', category: '의치', order: 8,
    meaning: '무치악 치조제의 진행성 흡수.',
    example: 'Severe residual ridge resorption of the mandible with a knife-edge crest.',
    caution: '형태 표현: **well-formed / knife-edge / flat / resorbed**.' },

  // ═══════════ 임플란트 ═══════════
  { ko: '골유착', en: 'osseointegration', section: 'A', category: '임플란트', order: 1,
    meaning: '임플란트와 골의 직접 결합.',
    example: 'Osseointegration confirmed — clear percussion tone, no mobility, no peri-implant radiolucency, ISQ 76.' },
  { ko: '나사 풀림 / 파절', en: 'screw loosening / screw fracture', section: 'A', category: '임플란트', order: 2,
    meaning: 'abutment 또는 보철 나사의 풀림·파절.',
    example: 'Screw loosening of the #46 implant crown; screw replaced and retorqued to 25 Ncm.',
    caution: '**재조임만 하면 재발한다** — 교합 과부하 등 원인 교정을 함께 기재.' },
  { ko: '변연골 소실', en: 'marginal bone loss', section: 'O', category: '임플란트', order: 3,
    meaning: '임플란트 주위 변연골 수준의 감소.',
    example: 'Marginal bone loss 2.5 mm compared with the baseline radiograph, saucer-shaped defect.',
    caution: '**baseline 대비**임을 반드시 명시한다. 기준 영상이 없으면 판독 근거가 약해진다.' },
  { ko: '임플란트 주위 점막염', en: 'peri-implant mucositis', section: 'A', category: '임플란트', order: 4,
    meaning: 'BOP를 동반한 연조직 염증으로 **골소실이 없는** 가역적 상태.',
    example: 'Peri-implant mucositis at #46 — BOP(+), no progressive bone loss beyond initial remodeling.' },
  { ko: '임플란트 주위염', en: 'peri-implantitis', section: 'A', category: '임플란트', order: 5,
    meaning: 'BOP·탐침 깊이 증가와 함께 **진행성 변연골 소실**을 동반한 상태.',
    example: 'Peri-implantitis at #46 — BOP(+), PD 6 mm, progressive marginal bone loss 2.5 mm from baseline.',
    caution: '두 진단을 가르는 것은 **골소실의 유무**다. 점막염 단계에서 잡는 것이 목표.' },
  { ko: '잉여 시멘트', en: 'excess (residual) cement', section: 'O', category: '임플란트', order: 6,
    meaning: '치은연하에 남은 시멘트.',
    example: 'Residual cement detected on PA at the distal of the #46 implant abutment.',
    caution: '임플란트 주위 질환과 강하게 연관된 인재(人災)성 원인이다.' },
  { ko: '수동적 적합', en: 'passive fit', section: 'O', category: '임플란트', order: 7,
    meaning: '강제력 없이 완전히 안착되는 적합.',
    example: 'Passive fit achieved; no rocking, complete seating confirmed radiographically.' },
  { ko: '완전 안착', en: 'complete seating', section: 'O', category: '임플란트', order: 8,
    meaning: '보철물·코핑이 완전히 자리 잡은 상태.',
    example: 'Complete seating of the impression coping confirmed on PA — no gap at the implant–coping interface.',
    caution: '임플란트에서는 **육안·촉진이 아니라 방사선으로** 확인한다.' },

  // ═══════════ 방사선 ═══════════
  { ko: '투과상 / 불투과상', en: 'radiolucency / radiopacity', section: 'O', category: '방사선', order: 1,
    meaning: '방사선상 어두운 영역 / 밝은 영역.',
    example: 'Marginal radiolucency at the distal of #46 crown.' },
  { ko: '골소실 양상', en: 'horizontal / vertical (angular) bone loss', section: 'O', category: '방사선', order: 2,
    meaning: '치조골 소실의 형태.',
    example: 'Generalized horizontal bone loss of 20–30%; vertical defect at the mesial of #36.',
    caution: '**수직 결손은 부위를 특정**해 기재한다 — 재생 술식 적응 판단에 직결.' },
  { ko: '골 수준', en: 'bone level', section: 'O', category: '방사선', order: 3,
    meaning: '치조골정의 위치. 임플란트에서는 플랫폼 기준.',
    example: 'Marginal bone level at the implant platform, unchanged from baseline.' },
  { ko: 'J형 투과상', en: 'J-shaped (halo) radiolucency', section: 'O', category: '방사선', order: 4,
    meaning: '치근 측면을 따라 치근단까지 이어지는 투과상.',
    example: 'J-shaped radiolucency along the distal root surface of #25.',
    caution: '**수직치근파절의 특징적 소견**이다.' },
  { ko: '골 경화', en: 'condensing osteitis / sclerotic bone', section: 'A', category: '방사선', order: 5,
    meaning: '만성 저강도 자극에 대한 반응성 골 경화.',
    example: 'Condensing osteitis at the apex of #36.' },
];
