/* ─────────────────────────────────────────────────────────────
 * 차팅 용어 — 한국어 임상 표현 → 영어 차팅 표현
 *
 * 목적은 번역이 아니라 "어느 단어를 골라야 하는가"의 감별.
 * 한 표현이 대상·원인에 따라 다른 영어 단어가 되는 지점을 중심으로 정리한다.
 *
 * section 태그
 *   O  — 관찰·기술 용어. 진단이 아님
 *   A  — 진단·판정 용어
 *   O·A — 맥락에 따라 양쪽
 *
 * 각 항목
 * 참고 교과서
 *   구강내과 — Burket's Oral Medicine / Neville, Oral and Maxillofacial Pathology
 *              Scully, Oral and Maxillofacial Medicine / Okeson, Management of TMD
 *   보철과   — GPT-10 (용어 기준) / Shillingburg / Rosenstiel / McCracken
 *              Zarb·Boucher, Prosthodontic Treatment for Edentulous Patients / Misch
 *   치주     — Newman & Carranza / 2017 World Workshop
 *
 *   meaning  — 무엇을 가리키는가
 *   variants — 갈리는 지점(대상·원인별로 다른 단어)
 *   example  — 실제 차팅 문장
 *   caution  — 혼동·오용 주의
 * ───────────────────────────────────────────────────────────── */

const TERM_CATS = ["연조직", "구강내과", "치아·수복물", "치주", "치수·치근단", "교합·악관절", "의치", "임플란트", "재료·기공", "방사선"];
const TERM_SEED_VERSION = 3;

const TERM_SEED = [
  // ── 연조직 · 파라펑션 징후 ──
  { ko: "협점막 백선", en: "linea alba", section: "O", category: "연조직", topic: "파라펑션 징후", order: 1,
    meaning: "교합면 높이를 따라 협점막에 나타나는 흰 선상 각화. 양측성이 흔하다.",
    example: "Linea alba present bilaterally along the occlusal plane.",
    caution: "**소견이지 진단이 아니다.** parafunction의 간접 징후로 해석할 수는 있으나 O에는 관찰만 적고, 이갈이 판단은 A로 보낸다. 병적 백색병변(leukoplakia)과 반드시 구분해 기술할 것.",
  },
  { ko: "혀 압흔", en: "tongue scalloping (crenated tongue)", section: "O", category: "연조직", topic: "파라펑션 징후", order: 2,
    meaning: "혀 측연에 치아 압흔이 남은 상태.",
    example: "Tongue scalloping noted on lateral borders.",
    caution: "linea alba와 함께 parafunction·거대설·기도 문제의 간접 단서로 쓰이나, 단독으로 진단 근거가 되지 않는다.",
  },

  // ── 연조직 · 궤양성 병변 ──
  { ko: "궤양", en: "ulcer / ulceration", section: "O", category: "연조직", topic: "궤양성 병변", order: 1,
    meaning: "상피가 소실되어 하부 결합조직이 노출된 병소.",
    variants: "<dl><dt>ulcer</dt><dd>병소 자체(명사)</dd><dt>ulceration</dt><dd>궤양이 생긴 상태·과정</dd><dt>erosion</dt><dd>상피 일부만 소실(연조직 맥락). <b>치아의 침식과 동음이의</b>이므로 문맥을 분명히</dd></dl>",
    example: "Linear ulcer 4 x 2 mm on the left mylohyoid ridge area, surrounded by erythema.",
    caution: "크기·형태·위치를 반드시 함께 — `linear` / `round` / `irregular`, mm 단위.",
  },
  { ko: "재발성 아프타", en: "recurrent aphthous stomatitis (RAS)", section: "A", category: "연조직", topic: "궤양성 병변", order: 2,
    meaning: "비각화 점막에 반복 발생하는 통증성 궤양.",
    variants: "<dl><dt>minor</dt><dd>&lt;10 mm, 7–14일 내 반흔 없이 치유</dd><dt>major</dt><dd>&gt;10 mm, 깊고 오래가며 반흔 남길 수 있음</dd><dt>herpetiform</dt><dd>작은 궤양 다발</dd></dl>",
    example: "Minor recurrent aphthous ulcer, 4 mm, on the labial mucosa.",
  },
  { ko: "외상성 궤양", en: "traumatic ulcer", section: "A", category: "연조직", topic: "궤양성 병변", order: 3,
    meaning: "물리적 자극(의치 변연·예리한 수복물·저작)에 의한 궤양.",
    example: "Traumatic ulcer corresponding to the over-extended denture flange.",
    caution: "**원인 제거 후 2주 내 치유되지 않으면 재평가·조직검사**를 고려한다.",
  },
  { ko: "구강작열감증후군", en: "burning mouth syndrome (BMS)", section: "A", category: "연조직", topic: "궤양성 병변", order: 4,
    meaning: "뚜렷한 병변 없이 지속되는 작열감. 배제 진단.",
    example: "Burning mouth syndrome — no mucosal lesion, normal salivary flow, symptoms >6 months.",
    caution: "의치 부적합·칸디다·구강건조·영양 결핍을 **먼저 배제**한 뒤에만 쓰는 명칭이다.",
  },
  { ko: "구강칸디다증", en: "oral candidiasis", section: "A", category: "연조직", topic: "궤양성 병변", order: 5,
    meaning: "칸디다에 의한 구강 감염.",
    variants: "<dl><dt>pseudomembranous</dt><dd>백태형 — <b>문질러 벗겨짐</b></dd><dt>erythematous</dt><dd>홍반형 — 의치성 구내염이 대표</dd><dt>hyperplastic</dt><dd>증식형 — 벗겨지지 않음</dd><dt>angular cheilitis</dt><dd>구각형</dd></dl>",
    example: "Erythematous candidiasis of the palate associated with continuous denture wear.",
    caution: "**벗겨지는지 여부**가 백반증과의 1차 감별점.",
  },

  // ── 연조직 · 기본 소견 ──
  { ko: "발적", en: "erythema / redness", section: "O", category: "연조직", topic: "기본 소견", order: 1,
    meaning: "점막·치은의 붉은 변화.",
    variants: "<dl><dt>localized erythema</dt><dd>국소</dd><dt>diffuse erythema</dt><dd>미만성 — 의치성 구내염 Newton II의 기술</dd></dl>",
    example: "Diffuse erythema of the palatal mucosa corresponding to the denture-bearing area.",
  },
  { ko: "부종", en: "edema / swelling", section: "O", category: "연조직", topic: "기본 소견", order: 2,
    meaning: "조직의 종창.",
    variants: "<dl><dt>edema</dt><dd>조직 내 체액 증가(기술적)</dd><dt>swelling</dt><dd>육안으로 부어오른 상태(일반)</dd><dt>fluctuant swelling</dt><dd>파동감 있는 종창 — 농양 시사</dd></dl>",
    example: "Localized fluctuant swelling in the buccal vestibule adjacent to #24.",
  },
  { ko: "경결 / 파동감", en: "induration / fluctuance", section: "O", category: "연조직", topic: "기본 소견", order: 3,
    meaning: "촉진 시 단단함(경결) / 액체가 만져지는 물렁함(파동감).",
    example: "Fluctuance(+) on palpation; no induration.",
    caution: "**induration은 악성 병변의 경고 소견**이기도 하다. 궤양이 2주 이상 지속되며 경결이 동반되면 조직검사 의뢰를 고려한다.",
  },
  { ko: "창백해짐", en: "blanching", section: "O", category: "연조직", topic: "기본 소견", order: 4,
    meaning: "압박으로 혈류가 차단되어 조직이 하얗게 되는 것.",
    example: "Mild blanching on abutment seating, resolved within 3 minutes.",
    caution: "보철·abutment 장착 시 확인 항목. **수분 내 회복되지 않으면 과압박**이므로 조정한다.",
  },
  { ko: "압통", en: "tenderness to palpation", section: "O", category: "연조직", topic: "기본 소견", order: 5,
    meaning: "촉진 시 통증.",
    example: "Masseter tender to palpation bilaterally; temporalis NT.",
    caution: "약어 **TTP**(tender to palpation), **NT**(non-tender)가 흔히 쓰인다. 근육 촉진에서는 **referred pain(연관통)** 유무를 함께 기재.",
  },

  // ── 연조직 · 증식성 병변 ──
  { ko: "증식 조직", en: "hyperplastic tissue", section: "O", category: "연조직", topic: "증식성 병변", order: 1,
    meaning: "만성 자극으로 증식한 연조직.",
    variants: "<dl><dt>epulis fissuratum</dt><dd>의치 변연에 의한 <b>주름형 증식</b> — 원인이 명확할 때</dd><dt>papillary hyperplasia</dt><dd>구개의 <b>유두상 증식</b> — 의치성 구내염 Newton III</dd><dt>hyperplastic tissue</dt><dd>원인·형태 불특정 시</dd></dl>",
    example: "Epulis fissuratum along the labial flange of the maxillary denture.",
  },
  { ko: "구개 융기 / 하악 융기", en: "torus palatinus / torus mandibularis", section: "O", category: "연조직", topic: "증식성 병변", order: 2,
    meaning: "정상 변이인 골성 융기.",
    example: "Torus mandibularis bilaterally, moderate size — may complicate denture design.",
    caution: "의치 설계에서 **완화 또는 외과적 제거** 판단이 필요하므로 크기·위치를 기재.",
  },
  { ko: "외골증", en: "exostosis", section: "O", category: "연조직", topic: "증식성 병변", order: 3,
    meaning: "치조골 협측 등에 생기는 국소 골 융기.",
    example: "Buccal exostoses in the maxillary posterior region.",
  },

  // ── 연조직 · 감염·염증 ──
  { ko: "구각염", en: "angular cheilitis", section: "O·A", category: "연조직", topic: "감염·염증", order: 1,
    meaning: "구각부의 균열·발적·가피.",
    example: "Angular cheilitis present bilaterally.",
    caution: "VDO 감소·칸디다 감염·영양 결핍과 연관될 수 있다. **O에는 소견만**, 원인 추정은 A로.",
  },
  { ko: "누공", en: "sinus tract", section: "O", category: "연조직", topic: "감염·염증", order: 2,
    meaning: "농이 배출되는 통로가 점막으로 열린 것.",
    variants: "<dl><dt>sinus tract</dt><dd>구강 내로 열린 배농로 — <b>치과에서 통상 쓰는 표현</b></dd><dt>fistula</dt><dd>엄밀히는 두 상피면을 잇는 통로. 흔히 혼용되나 sinus tract가 정확</dd></dl>",
    example: "Sinus tract at the mucogingival junction of #36; gutta-percha tracing to the mesial root apex.",
    caution: "**치은변연 가까이** 열린 누공은 치주 기원 또는 **수직치근파절**을 시사한다 — 위치를 반드시 기재.",
  },

  // ── 연조직 · 타액 ──
  { ko: "구강건조", en: "xerostomia / hyposalivation", section: "O·A", category: "연조직", topic: "타액", order: 1,
    meaning: "입 마름.",
    variants: "<dl><dt>xerostomia</dt><dd><b>환자가 호소하는 주관적 건조감</b> → S에 가깝다</dd><dt>hyposalivation</dt><dd><b>객관적으로 측정된 타액 감소</b> → O</dd></dl>",
    example: "Saliva viscous and scant; patient reports dry mouth (xerostomia). Suspected medication-induced hyposalivation.",
    caution: "두 단어를 구분하면 S와 O가 자연스럽게 나뉜다.",
  },

  // ── 연조직 · 백색·홍색 병변 ──
  { ko: "백반증", en: "leukoplakia", section: "A", category: "연조직", topic: "백색·홍색 병변", order: 1,
    meaning: "문질러 지워지지 않는 백색 반점으로 **다른 질환으로 설명되지 않는 것**. 배제 진단이다.",
    example: "Leukoplakia, 12 x 8 mm, non-scrapable, left lateral tongue — biopsy referral.",
    caution: "**임상적 배제 진단이며 잠재적 악성 장애**다. 지워지는 백색 병변(칸디다 등)과 구분하고, 지속 시 조직검사 의뢰.",
  },
  { ko: "홍반증", en: "erythroplakia", section: "A", category: "연조직", topic: "백색·홍색 병변", order: 2,
    meaning: "다른 질환으로 설명되지 않는 붉은 반점.",
    example: "Erythroplakia on the floor of the mouth — urgent biopsy referral.",
    caution: "**백반증보다 이형성·악성 비율이 높다.** 발견 시 지체 없이 의뢰.",
  },
  { ko: "구강편평태선", en: "oral lichen planus (OLP)", section: "A", category: "연조직", topic: "백색·홍색 병변", order: 3,
    meaning: "망상 백색선(Wickham striae)을 특징으로 하는 만성 면역매개 점막 질환.",
    variants: "<dl><dt>reticular</dt><dd>망상형 — 무증상이 흔함</dd><dt>erosive / atrophic</dt><dd>미란·위축형 — 통증 동반</dd></dl>",
    example: "Reticular oral lichen planus with Wickham striae, bilateral buccal mucosa.",
    caution: "**양측성 대칭**이 특징. 편측성이거나 수복물에 접해 있으면 **태선양 반응(lichenoid reaction)** 을 고려.",
  },
  { ko: "태선양 반응", en: "oral lichenoid lesion / reaction", section: "A", category: "연조직", topic: "백색·홍색 병변", order: 4,
    meaning: "치과 재료·약물에 대한 접촉성 반응으로 편평태선과 유사한 병변.",
    example: "Oral lichenoid lesion adjacent to the amalgam restoration of #36.",
    caution: "**접촉 부위에 국한**되고 원인 제거 시 호전되는 점이 OLP와의 감별점.",
  },
  { ko: "니코틴성 구내염", en: "nicotine stomatitis", section: "A", category: "연조직", topic: "백색·홍색 병변", order: 5,
    meaning: "흡연 열자극에 의한 구개의 백색 각화와 붉은 소타액선 개구부.",
    example: "Nicotine stomatitis of the hard palate with prominent minor salivary duct openings.",
  },

  // ── 구강내과 · 수포성·박탈성 질환 ──
  { ko: "박탈성 치은염", en: "desquamative gingivitis", section: "O", category: "구강내과", topic: "수포성·박탈성 질환", order: 1,
    meaning: "치은 상피가 벗겨져 붉고 광택 있는 미란을 보이는 임상 양상. 통증과 접촉 출혈을 동반.",
    example: "Desquamative gingivitis involving the attached gingiva of the maxillary anterior region.",
    caution: "**임상 기술이지 진단명이 아니다.** 편평태선·유천포창·천포창의 공통 발현이므로, 치태성 치은염으로 오인해 스케일링만 반복하면 안 된다 — **생검·직접면역형광 의뢰**가 원칙.",
  },
  { ko: "천포창", en: "pemphigus vulgaris", section: "A", category: "구강내과", topic: "수포성·박탈성 질환", order: 2,
    meaning: "자가항체가 상피세포 간 접착을 파괴해 **상피 내(suprabasilar) 수포**를 만드는 질환. 구강 병변이 첫 증상인 경우가 많다.",
    example: "Pemphigus vulgaris — multiple ragged erosions, Nikolsky sign positive; biopsy with DIF requested.",
    caution: "**치명적일 수 있어 조기 진단이 중요**하다. 수포는 쉽게 터져 미란으로만 관찰되는 경우가 흔하다.",
  },
  { ko: "점막유천포창", en: "mucous membrane pemphigoid", section: "A", category: "구강내과", topic: "수포성·박탈성 질환", order: 3,
    meaning: "기저막대를 표적으로 하는 자가면역질환으로 **상피 하(subepithelial) 수포**를 형성. 박탈성 치은염이 흔한 발현.",
    example: "Mucous membrane pemphigoid presenting as desquamative gingivitis; DIF shows linear deposition at the basement membrane zone.",
    caution: "**안구 침범(반흔·검구유착) 시 실명 위험**이 있어 안과 협진이 필요하다. 구강 소견만 보고 지나치지 말 것.",
  },
  { ko: "Nikolsky 징후", en: "Nikolsky sign", section: "O", category: "구강내과", topic: "수포성·박탈성 질환", order: 4,
    meaning: "정상으로 보이는 점막을 문지르거나 공기를 불었을 때 상피가 벗겨지거나 수포가 생기는 현상.",
    example: "Nikolsky sign positive on the buccal mucosa.",
    caution: "수포성 질환을 시사하는 소견으로, **양성이면 즉시 생검·의뢰**를 고려한다.",
  },
  { ko: "다형홍반", en: "erythema multiforme", section: "A", category: "구강내과", topic: "수포성·박탈성 질환", order: 5,
    meaning: "급성 과민 반응성 질환. 구순의 **출혈성 가피**와 광범위 구강 미란이 특징이며 피부에는 표적 병변이 나타날 수 있다.",
    example: "Erythema multiforme with hemorrhagic crusting of the lips and diffuse oral erosions.",
    caution: "단순포진·약물이 유발 인자로 흔히 지목된다. 급격한 발병과 **구순 가피**가 편평태선과의 감별점.",
  },

  // ── 구강내과 · 백색·색소 병변 ──
  { ko: "증식성 사마귀양 백반증", en: "proliferative verrucous leukoplakia (PVL)", section: "A", category: "구강내과", topic: "백색·색소 병변", order: 1,
    meaning: "다발성으로 퍼지며 사마귀 모양으로 진행하는 백반증의 한 형태.",
    example: "Proliferative verrucous leukoplakia involving multiple sites of the gingiva.",
    caution: "**악성 전환율이 높고 재발이 잦은 고위험 병변**으로 알려져 있다. 장기 추적과 다부위 생검이 필요하다.",
  },
  { ko: "구강점막하섬유증", en: "oral submucous fibrosis", section: "A", category: "구강내과", topic: "백색·색소 병변", order: 2,
    meaning: "점막 고유층의 섬유화로 창백해지고 섬유성 띠가 촉지되며 개구가 제한되는 만성 질환. 빈랑(areca nut) 저작과 연관.",
    example: "Oral submucous fibrosis — blanched buccal mucosa with palpable fibrous bands, MO 24 mm.",
    caution: "**잠재적 악성 장애**이며, 개구 제한 때문에 보철 술식 자체가 어려워진다.",
  },
  { ko: "아말감 문신", en: "amalgam tattoo", section: "A", category: "구강내과", topic: "백색·색소 병변", order: 3,
    meaning: "아말감 입자가 점막에 매몰되어 생긴 청회색 색소 침착.",
    example: "Amalgam tattoo on the buccal mucosa adjacent to #36; radiopaque particles visible on PA.",
    caution: "**흑색종과의 감별**이 핵심이다. 방사선상 불투과 입자가 보이면 진단에 도움이 되나, 보이지 않고 병변이 커지거나 변화하면 생검한다.",
  },
  { ko: "흡연자 멜라닌증", en: "smoker's melanosis", section: "A", category: "구강내과", topic: "백색·색소 병변", order: 4,
    meaning: "흡연에 의한 반응성 멜라닌 색소 침착. 하악 전방 치은에 흔하다.",
    example: "Smoker's melanosis of the mandibular anterior attached gingiva.",
  },
  { ko: "멜라닌반", en: "melanotic macule", section: "A", category: "구강내과", topic: "백색·색소 병변", order: 5,
    meaning: "경계가 뚜렷한 갈색 반점. 대개 양성이며 크기가 변하지 않는다.",
    example: "Oral melanotic macule, 4 mm, well-defined, on the lower lip vermilion.",
    caution: "**크기 증가·경계 불규칙·색조 불균일**이 있으면 흑색종 배제를 위해 생검한다.",
  },
  { ko: "구강 흑색종", en: "oral melanoma", section: "A", category: "구강내과", topic: "백색·색소 병변", order: 6,
    meaning: "구강 점막의 악성 흑색종. 구개와 상악 치은에 호발.",
    example: "Rapidly enlarging pigmented lesion of the palate with irregular borders — urgent referral for biopsy.",
    caution: "드물지만 **예후가 매우 불량**하다. 색소 병변이 커지거나 궤양·출혈을 동반하면 지체 없이 의뢰.",
  },

  // ── 구강내과 · 설 병변 ──
  { ko: "지도설", en: "geographic tongue (benign migratory glossitis)", section: "A", category: "구강내과", topic: "설 병변", order: 1,
    meaning: "사상유두가 소실된 홍반 부위가 백색 테두리를 두르고 위치가 이동하는 양성 병변.",
    example: "Geographic tongue — migratory erythematous patches with serpiginous white borders on the dorsum.",
    caution: "**양성이며 치료 불요**인 경우가 대부분이다. 자극성 음식에 작열감을 호소할 수 있다.",
  },
  { ko: "균열설", en: "fissured tongue", section: "O", category: "구강내과", topic: "설 병변", order: 2,
    meaning: "설배면의 깊은 열구. 정상 변이로 보는 경우가 많다.",
    example: "Fissured tongue with deep central groove; no erythema.",
    caution: "열구에 음식·세균이 정체되면 작열감·구취의 원인이 될 수 있어 **설 세정 교육**이 유효하다.",
  },
  { ko: "모설", en: "hairy tongue (coated tongue)", section: "O", category: "구강내과", topic: "설 병변", order: 3,
    meaning: "사상유두가 신장·착색되어 털처럼 보이는 상태.",
    example: "Hairy tongue with brown-black discoloration of the dorsum.",
  },
  { ko: "정중능형설염", en: "median rhomboid glossitis", section: "A", category: "구강내과", topic: "설 병변", order: 4,
    meaning: "설배 정중 후방의 유두 소실성 홍반 병소. 칸디다 연관이 보고된다.",
    example: "Median rhomboid glossitis — well-demarcated depapillated area anterior to the circumvallate papillae.",
  },
  { ko: "위축성 설염", en: "atrophic glossitis", section: "O", category: "구강내과", topic: "설 병변", order: 5,
    meaning: "유두가 소실되어 혀가 매끈하고 붉게 보이는 상태.",
    example: "Atrophic glossitis with generalized loss of filiform papillae.",
    caution: "**철·엽산·비타민 B12 결핍, 칸디다증**의 신호일 수 있다 — 전신 평가·혈액검사 협진을 고려.",
  },

  // ── 구강내과 · 감염 ──
  { ko: "일차 헤르페스성 치은구내염", en: "primary herpetic gingivostomatitis", section: "A", category: "구강내과", topic: "감염", order: 1,
    meaning: "HSV 초감염. 발열·권태와 함께 광범위한 소수포·궤양과 **심한 변연 치은염**을 보인다.",
    example: "Primary herpetic gingivostomatitis — fever, diffuse vesicles and ulcers, markedly inflamed marginal gingiva.",
    caution: "**아프타와 달리 각화 점막(치은·구개)에도 발생**하고 전신 증상을 동반한다 — 이 점이 감별의 핵심.",
  },
  { ko: "재발성 구순포진", en: "recurrent herpes labialis", section: "A", category: "구강내과", topic: "감염", order: 2,
    meaning: "잠복 HSV의 재활성화로 구순부에 반복되는 소수포·가피. 전구 감각(tingling)이 선행.",
    example: "Recurrent herpes labialis with prodromal tingling; vesicles on the vermilion border.",
    caution: "수포기에는 **전염력이 있어** 관혈적 처치를 연기하는 것이 안전하다.",
  },
  { ko: "재발성 구내 헤르페스", en: "recurrent intraoral herpes", section: "A", category: "구강내과", topic: "감염", order: 3,
    meaning: "재발성 HSV의 구내 발현. **각화 점막(경구개·부착치은)** 에 국한되는 것이 특징.",
    example: "Recurrent intraoral herpes — clustered ulcers confined to the hard palate.",
    caution: "**비각화 점막에 생기는 아프타와 부위로 감별**한다.",
  },
  { ko: "대상포진", en: "herpes zoster", section: "A", category: "구강내과", topic: "감염", order: 4,
    meaning: "VZV 재활성화. **신경 분포를 따라 편측·정중선에서 멈추는** 수포성 발진과 신경통이 특징.",
    example: "Herpes zoster of the V2 distribution — unilateral vesicles stopping at the midline.",
    caution: "치통으로 오인되기 쉽다. **편측성이며 정중선을 넘지 않는** 분포가 결정적 단서이며, 후유증으로 대상포진후신경통이 남을 수 있다.",
  },
  { ko: "방선균증", en: "actinomycosis", section: "A", category: "구강내과", topic: "감염", order: 5,
    meaning: "만성 화농성 감염. 다발성 누공과 배출물 내 **황색 과립(sulfur granules)** 이 특징.",
    example: "Cervicofacial actinomycosis with multiple draining sinus tracts and sulfur granules.",
  },
  { ko: "골수염", en: "osteomyelitis", section: "A", category: "구강내과", topic: "감염", order: 6,
    meaning: "악골 골수의 감염성 염증.",
    variants: "<dl><dt>sequestrum</dt><dd>분리된 <b>괴사 골편</b></dd><dt>involucrum</dt><dd>괴사 골을 둘러싸는 <b>신생골 껍질</b></dd></dl>",
    example: "Chronic suppurative osteomyelitis of the mandible with sequestrum formation.",
  },

  // ── 구강내과 · 타액선·구강건조 ──
  { ko: "타석", en: "sialolith", section: "A", category: "구강내과", topic: "타액선·구강건조", order: 1,
    meaning: "타액선 도관 내 석회화 결석. 악하선에 가장 흔하다.",
    example: "Sialolith in the left submandibular duct — recurrent prandial swelling.",
    caution: "**식사 시 종창·통증(prandial swelling)** 이 전형적 병력이다.",
  },
  { ko: "타액선염", en: "sialadenitis", section: "A", category: "구강내과", topic: "타액선·구강건조", order: 2,
    meaning: "타액선의 염증. 세균성은 도관 개구부에서 농이 배출된다.",
    example: "Acute bacterial sialadenitis of the parotid — purulent discharge from Stensen duct on massage.",
  },
  { ko: "점액낭종 / 하마종", en: "mucocele / ranula", section: "A", category: "구강내과", topic: "타액선·구강건조", order: 3,
    meaning: "소타액선 도관 손상으로 점액이 저류된 낭성 병변. 구강저의 큰 것을 ranula라 한다.",
    example: "Mucocele of the lower lip, 6 mm, fluctuant and bluish.",
  },
  { ko: "쇼그렌 증후군", en: "Sjögren syndrome", section: "A", category: "구강내과", topic: "타액선·구강건조", order: 4,
    meaning: "외분비선을 침범하는 자가면역질환. 구강건조와 안구건조가 주 증상.",
    example: "Suspected Sjögren syndrome — xerostomia, keratoconjunctivitis sicca; referred for serology and labial gland biopsy.",
    caution: "**우식이 치경부·절단연에 급속히 다발**하는 양상이 흔하다. 보철 계획에서 우식 위험을 최고 등급으로 잡아야 한다.",
  },
  { ko: "타액 분비율", en: "salivary flow rate", section: "O", category: "구강내과", topic: "타액선·구강건조", order: 5,
    meaning: "단위 시간당 타액 분비량. 비자극·자극 전타액으로 나누어 측정.",
    example: "Unstimulated whole salivary flow 0.06 mL/min — consistent with hyposalivation.",
    caution: "기준치는 문헌마다 차이가 있으나 **비자극 전타액이 대략 0.1 mL/min 미만**이면 저하로 보는 것이 통례다. 측정 조건(시간대·금식)을 함께 기록.",
  },
  { ko: "미각 이상", en: "dysgeusia / ageusia / hypogeusia", section: "O", category: "구강내과", topic: "타액선·구강건조", order: 6,
    meaning: "미각의 왜곡 / 소실 / 감소.",
    example: "Dysgeusia reported following initiation of the new antihypertensive.",
    caution: "약물·구강건조·아연 결핍·신경 손상이 흔한 원인이다. **의치 장착 후 호소**되면 구개 피개와 재료를 먼저 점검.",
  },
  { ko: "구취", en: "halitosis (oral malodor)", section: "O·A", category: "구강내과", topic: "타액선·구강건조", order: 7,
    meaning: "호기의 불쾌한 냄새. 대부분 구강 내 기원이며 **설태**가 주요 원인.",
    example: "Oral malodor with heavy tongue coating; organoleptic score 3.",
    caution: "원인 물질은 **휘발성 황화합물(VSC)** 이다. 치주 질환·설태·구강건조를 먼저 평가하고, 구강에서 설명되지 않으면 이비인후과·내과 의뢰.",
  },

  // ── 구강내과 · 구강안면통증 ──
  { ko: "삼차신경통", en: "trigeminal neuralgia", section: "A", category: "구강내과", topic: "구강안면통증", order: 1,
    meaning: "삼차신경 분포를 따라 **전기 충격 같은 발작성 통증**이 수 초간 반복되는 질환. 유발 부위(trigger zone) 자극으로 촉발된다.",
    example: "Trigeminal neuralgia, V2 distribution — paroxysmal electric-shock pain triggered by light touch of the upper lip.",
    caution: "**치통으로 오인되어 근관치료·발치가 반복되는 대표적 질환**이다. 발작성·수 초·유발점이라는 3요소가 있으면 치성 원인을 재검토하고 의뢰한다.",
  },
  { ko: "지속성 특발성 안면통", en: "persistent idiopathic facial pain", section: "A", category: "구강내과", topic: "구강안면통증", order: 2,
    meaning: "뚜렷한 기질적 원인 없이 지속되는 둔한 안면 통증. 부위가 모호하고 신경 분포를 따르지 않는다.",
    example: "Persistent idiopathic facial pain — continuous dull ache, poorly localized, no neurological deficit.",
    caution: "**배제 진단**이며, 침습적 치과 처치가 증상을 악화시킬 수 있다.",
  },
  { ko: "비치성 치통", en: "non-odontogenic toothache", section: "A", category: "구강내과", topic: "구강안면통증", order: 3,
    meaning: "치아에서 느껴지지만 원인이 치아가 아닌 통증. 근막·신경·부비동·심장 기원 등.",
    example: "Non-odontogenic toothache of muscular origin — pain reproduced by masseter palpation, all pulp tests within normal limits.",
    caution: "**치수 검사 정상 + 국소마취로 통증이 사라지지 않음**이면 강하게 의심한다. 원인 불명 상태에서 근관치료를 시행하지 않는다.",
  },
  { ko: "신경병성 통증", en: "neuropathic pain", section: "A", category: "구강내과", topic: "구강안면통증", order: 4,
    meaning: "신경 손상·기능 이상에서 기원하는 통증. 작열감·전기감·저림을 동반.",
    example: "Neuropathic pain following implant placement, with allodynia over the mental nerve distribution.",
  },
  { ko: "이질통 / 통각과민", en: "allodynia / hyperalgesia", section: "O", category: "구강내과", topic: "구강안면통증", order: 5,
    meaning: "통증을 유발하지 않는 자극에 통증을 느낌 / 통증 자극에 과도하게 반응함.",
    example: "Allodynia to light touch over the left cheek.",
  },
  { ko: "거대세포동맥염", en: "giant cell (temporal) arteritis", section: "A", category: "구강내과", topic: "구강안면통증", order: 6,
    meaning: "측두동맥 등을 침범하는 혈관염. 측두부 통증과 **저작 시 턱 파행(jaw claudication)** 이 특징.",
    example: "Suspected giant cell arteritis — temporal tenderness with jaw claudication; urgent medical referral.",
    caution: "**치료가 늦으면 실명 위험**이 있는 응급 질환이다. 고령 환자의 새로운 측두부 두통 + 저작 시 턱 피로는 즉시 의뢰.",
  },
  { ko: "측두하악장애", en: "temporomandibular disorder (TMD)", section: "A", category: "구강내과", topic: "구강안면통증", order: 7,
    meaning: "악관절·저작근·연관 구조의 통증과 기능 이상을 포괄하는 용어.",
    example: "TMD — myalgia with disc displacement with reduction, left TMJ (DC/TMD).",
    caution: "**단일 질환이 아니라 상위 범주**다. 차팅에는 DC/TMD의 구체적 진단명까지 적는 것이 정확하다.",
  },

  // ── 구강내과 · 전신·약물 ──
  { ko: "약제관련 악골괴사", en: "medication-related osteonecrosis of the jaw (MRONJ)", section: "A", category: "구강내과", topic: "전신·약물", order: 1,
    meaning: "항흡수제·항혈관형성제 투여력이 있고 방사선 조사력이 없는 환자에서, 악골의 노출 또는 누공을 통해 탐침되는 골이 **8주 이상 지속**되는 상태.",
    variants: "<dl><dt>Stage 0</dt><dd>노출 골 없이 비특이 증상·영상 소견</dd><dt>Stage 1</dt><dd>노출 골, <b>무증상·감염 없음</b></dd><dt>Stage 2</dt><dd>노출 골 + <b>통증·감염</b></dd><dt>Stage 3</dt><dd>치조골을 넘는 확장 — 병적 골절, 구외 누공, 상악동 교통 등</dd></dl>",
    example: "MRONJ stage 2 of the left posterior mandible in a patient on denosumab.",
    caution: "가철성 보철의 **압박 궤양도 유발 인자**다. 투여력이 있는 환자는 의치 변연 조정에 각별히 주의하고 정기 점검 간격을 좁힌다.",
  },
  { ko: "골방사선괴사", en: "osteoradionecrosis (ORN)", section: "A", category: "구강내과", topic: "전신·약물", order: 2,
    meaning: "방사선 조사 부위에서 골이 노출된 채 치유되지 않는 상태.",
    example: "Osteoradionecrosis of the mandible following 66 Gy radiotherapy.",
    caution: "**방사선 조사 부위의 발치는 고위험**이다. 두경부 방사선력이 있으면 선량·부위·시기를 반드시 확인하고 협진한다.",
  },
  { ko: "약물성 치은 증식", en: "drug-influenced gingival enlargement", section: "A", category: "구강내과", topic: "전신·약물", order: 3,
    meaning: "항경련제·칼슘통로차단제·면역억제제와 연관된 치은 증대.",
    example: "Drug-influenced gingival enlargement associated with amlodipine; plaque control reinforced.",
    caution: "**치태가 발현을 증폭**시키므로 위생 관리가 1차 처치다. 약제 변경은 처방의와 협의.",
  },
  { ko: "구강 편평세포암", en: "oral squamous cell carcinoma (OSCC)", section: "A", category: "구강내과", topic: "전신·약물", order: 4,
    meaning: "구강에서 가장 흔한 악성 종양.",
    example: "Suspicious ulcerated lesion with rolled indurated margins on the lateral tongue — urgent biopsy referral.",
    caution: "경고 소견 — **2주 이상 낫지 않는 궤양, 경결, 융기된 변연, 고정, 원인 없는 출혈, 지속되는 백·홍색 병변, 편측 림프절 종대**. 무치악 고령 환자의 정기 검진에서도 반드시 선별.",
  },
  { ko: "점막염", en: "oral mucositis", section: "A", category: "구강내과", topic: "전신·약물", order: 5,
    meaning: "항암화학요법·방사선치료로 인한 구강 점막의 광범위한 염증·궤양.",
    example: "Grade 3 oral mucositis during chemoradiotherapy; oral care protocol reinforced.",
  },

  // ── 치아·수복물 · 보철물 문제 ──
  { ko: "보철물 탈락", en: "decementation / debonding / dislodgement", section: "A", category: "치아·수복물", topic: "보철물 문제", order: 1,
    meaning: "보철물이 지대치에서 떨어진 것. **원인에 따라 단어가 다르다.**",
    variants: "<dl><dt>decementation</dt><dd><b>시멘트 실패</b> — 보철물은 온전하고 시멘트 계면에서 탈락</dd><dt>debonding</dt><dd><b>접착(레진) 실패</b> — 베니어·접착성 보철·교정 브라켓</dd><dt>dislodgement</dt><dd>원인 불문 <b>일반 표현</b></dd></dl>",
    example: "Decementation of #46 full gold crown secondary to recurrent caries at the distal margin.",
    caution: "차팅에서는 **원인까지 붙이는 것이 표준**이다 — `secondary to recurrent caries` / `due to inadequate retention form`. “fell out” 같은 구어체는 쓰지 않는다.",
  },
  { ko: "이차우식", en: "secondary caries / recurrent caries", section: "A", category: "치아·수복물", topic: "보철물 문제", order: 2,
    meaning: "기존 수복물 변연에 새로 생긴 우식.",
    example: "Recurrent caries at the distal margin of #46 crown.",
    caution: "**진단(A)** 이다. O에는 `marginal radiolucency`, `explorer catch`, `softened dentin` 같은 **소견**으로 적는다.",
  },
  { ko: "변연에 걸린다", en: "explorer catch", section: "O", category: "치아·수복물", topic: "보철물 문제", order: 3,
    meaning: "탐침이 변연에서 걸리는 촉감.",
    example: "Explorer catch(+) at the distal margin of #46 crown.",
    caution: "이것은 **소견**이고, 그로부터 내리는 판단(이차우식·변연 부적합)은 A다.",
  },
  { ko: "변연 부적합", en: "marginal discrepancy", section: "O", category: "치아·수복물", topic: "보철물 문제", order: 4,
    meaning: "보철물 변연이 치아와 맞지 않음.",
    variants: "<dl><dt>open margin</dt><dd>변연이 뜬 상태(간극)</dd><dt>overhang</dt><dd>변연이 <b>과충전되어 튀어나온</b> 상태</dd><dt>underhang / deficient margin</dt><dd>변연이 <b>부족한</b> 상태</dd><dt>marginal gap</dt><dd>간극의 정량 표현(μm)</dd></dl>",
    example: "Open margin with detectable gap at the mesial of #26 crown on PA.",
  },
  { ko: "도재 파절", en: "porcelain chipping / fracture", section: "O", category: "치아·수복물", topic: "보철물 문제", order: 5,
    meaning: "도재부의 깨짐.",
    variants: "<dl><dt>chipping</dt><dd><b>작은 조각</b>이 떨어져 나감 — 하부구조 노출 없음</dd><dt>fracture</dt><dd>더 큰 파절, 흔히 <b>하부구조(코어) 노출</b> 동반</dd><dt>delamination</dt><dd>도재가 하부구조에서 <b>박리</b></dd></dl>",
    example: "Porcelain chipping at the mesiolingual cusp of #36 crown; framework not exposed.",
  },

  // ── 치아·수복물 · 균열·파절 ──
  { ko: "균열선", en: "craze line", section: "O", category: "치아·수복물", topic: "균열·파절", order: 1,
    meaning: "법랑질 내에 국한된 미세 균열. 대개 무증상.",
    example: "Craze lines visible on the buccal surface of #14 under transillumination.",
    caution: "**craze line(법랑질 내, 무증상)** 과 **cracked tooth(상아질까지, 증상 동반)** 는 예후가 완전히 다르다 — 섞어 쓰지 말 것.",
  },
  { ko: "균열치", en: "cracked tooth", section: "A", category: "치아·수복물", topic: "균열·파절", order: 2,
    meaning: "상아질까지 진행된 균열로 증상을 동반하는 상태.",
    variants: "<dl><dt>cracked tooth</dt><dd>불완전 균열, 증상 동반</dd><dt>split tooth</dt><dd><b>완전히 분리</b>된 상태</dd><dt>cuspal fracture</dt><dd>교두 파절</dd></dl>",
    example: "Cracked tooth #37 — positive bite test on the mesiolingual cusp with rebound pain.",
    caution: "**보철 전에 반드시 배제**해야 하는 진단이다. 놓치면 크라운 완성 후 치아가 갈라진다.",
  },
  { ko: "수직치근파절", en: "vertical root fracture (VRF)", section: "A", category: "치아·수복물", topic: "균열·파절", order: 3,
    meaning: "치근을 장축 방향으로 가르는 파절. **원칙적으로 수복 불가.**",
    example: "VRF suspected at #25 — isolated narrow probing defect 9 mm on the buccal with J-shaped radiolucency.",
    caution: "결정적 소견 3가지를 함께 기재 — **isolated deep narrow pocket**, **J-shaped / halo radiolucency**, **sinus tract near the gingival margin**.",
  },

  // ── 치아·수복물 · 치질 소실 ──
  { ko: "마모면", en: "wear facet", section: "O", category: "치아·수복물", topic: "치질 소실", order: 1,
    meaning: "마모로 생긴 평탄면.",
    example: "Wear facets on #13, 23 with matching antagonist contacts.",
    caution: "**대합치와 일치하는지(matching)** 를 반드시 함께 적는다 — 일치하면 attrition을 시사한다. 마모의 원인 판정은 A로.",
  },
  { ko: "치아 마모 (원인별)", en: "attrition / erosion / abrasion", section: "A", category: "치아·수복물", topic: "치질 소실", order: 2,
    meaning: "치질 소실의 원인별 진단명.",
    variants: "<dl><dt>attrition</dt><dd><b>치아 간 접촉</b>에 의한 마모 — 대합면과 일치하는 평탄 facet</dd><dt>erosion</dt><dd><b>산</b>에 의한 화학적 소실 — cupping, 구개면 함몰, <b>수복물이 솟아 보임</b></dd><dt>abrasion</dt><dd><b>외부 마찰</b>(칫솔 등) — 치경부 wedge-shaped 결손</dd><dt>abfraction</dt><dd>교합 응력에 의한 치경부 소실이라는 <b>가설적 개념</b> — 논쟁이 있음</dd></dl>",
    example: "Generalized erosion with cupping of occlusal surfaces; restorations standing proud of adjacent tooth structure.",
    caution: "“수복물이 주위 치질보다 솟아 보인다”는 **erosion의 특징적 소견**이다.",
  },
  { ko: "쐐기형 결손", en: "wedge-shaped cervical defect", section: "O", category: "치아·수복물", topic: "치질 소실", order: 3,
    meaning: "치경부의 쐐기 모양 결손.",
    example: "Wedge-shaped cervical defects on #34, 35 with exposed dentin.",
    caution: "`abfraction lesion`은 **원인을 전제한 표현**이므로, O에는 형태 기술(wedge-shaped defect)로 남기는 편이 안전하다.",
  },
  { ko: "컵 모양 함몰", en: "cupping", section: "O", category: "치아·수복물", topic: "치질 소실", order: 4,
    meaning: "교두정·절단연에 생긴 오목한 함몰. 침식의 전형적 형태.",
    example: "Cupping of the cusp tips on #16, 26.",
  },
  { ko: "지각과민", en: "dentin hypersensitivity", section: "A", category: "치아·수복물", topic: "치질 소실", order: 5,
    meaning: "노출 상아질에 대한 자극으로 유발되며 자극 제거 시 즉시 소실되는 단시간 통증.",
    example: "Dentin hypersensitivity #34, 35 — sharp response to cold resolving immediately on stimulus removal.",
    caution: "**자극 제거 후 지속되면 지각과민이 아니다** — 비가역성 치수염·균열치를 먼저 배제할 것.",
  },

  // ── 치아·수복물 · 치아 위치 ──
  { ko: "정출", en: "supraeruption (overeruption)", section: "O", category: "치아·수복물", topic: "치아 위치", order: 1,
    meaning: "대합치 결손으로 치아가 교합평면을 넘어 맹출한 상태.",
    example: "Supraeruption of #17 into the edentulous space of #47.",
    caution: "보철 공간 부족의 흔한 원인 — **available interocclusal space**와 함께 기재.",
  },
  { ko: "경사", en: "tipping / tilting", section: "O", category: "치아·수복물", topic: "치아 위치", order: 2,
    meaning: "치아 장축이 기울어진 상태.",
    example: "Mesial tipping of #37 into the #36 edentulous space.",
    caution: "RPD에서는 **착탈로·guide plane 설계**에 직접 영향을 준다.",
  },

  // ── 치아·수복물 · 인접 관계 ──
  { ko: "식편압입", en: "food impaction", section: "O·A", category: "치아·수복물", topic: "인접 관계", order: 1,
    meaning: "인접부에 음식물이 끼어 들어가는 것.",
    example: "Food impaction reported at the mesial of #46 implant crown; proximal contact loss confirmed with floss.",
    caution: "**원인 소견(proximal contact loss)** 을 함께 적어야 처치가 이어진다. 임플란트 보철에서는 인접 자연치 이동으로 시간이 지나 새로 생긴다.",
  },
  { ko: "인접 접촉 상실", en: "proximal contact loss / open contact", section: "O", category: "치아·수복물", topic: "인접 관계", order: 2,
    meaning: "인접 접촉이 없어 치실이 저항 없이 통과하는 상태.",
    example: "Open contact at the mesial of #46 — floss passes without resistance.",
  },

  // ── 치아·수복물 · 색·심미 ──
  { ko: "착색 / 변색", en: "staining / discoloration", section: "O", category: "치아·수복물", topic: "색·심미", order: 1,
    meaning: "외인성 착색 / 내인성 변색.",
    variants: "<dl><dt>extrinsic staining</dt><dd>표면 착색(커피·흡연) — 제거 가능</dd><dt>intrinsic discoloration</dt><dd>치질 내부의 변색(연령·테트라사이클린·외상) — 미백·수복 대상</dd></dl>",
    example: "Generalized intrinsic discoloration, uniform yellow; no banded pattern.",
  },

  // ── 치아·수복물 · 흡수·형성이상 ──
  { ko: "치근 흡수", en: "root resorption", section: "A", category: "치아·수복물", topic: "흡수·형성이상", order: 1,
    meaning: "치근 경조직의 병적 소실. **유형에 따라 예후와 처치가 완전히 다르다.**",
    variants: "<dl><dt>external surface resorption</dt><dd>표재성 — 자기 제한적, 경과 관찰</dd><dt>external inflammatory resorption</dt><dd>염증성 — <b>근관치료로 정지</b> 가능</dd><dt>external replacement resorption</dt><dd>치환성 = <b>ankylosis</b>, 진행성·비가역</dd><dt>external cervical resorption (ECR)</dt><dd>치경부 침습성 — 조기 발견 시 수복 가능</dd><dt>internal resorption</dt><dd>치수강 내부에서 진행 — 근관치료 적응</dd></dl>",
    example: "External cervical resorption class 2 at #12, buccal.",
    caution: "내흡수와 외흡수는 **방사선 각도를 바꿔 촬영**하면 감별에 도움이 된다 — 내흡수는 병소가 치수강과 함께 움직이지 않는다.",
  },
  { ko: "치아 유착", en: "dental ankylosis", section: "A", category: "치아·수복물", topic: "흡수·형성이상", order: 2,
    meaning: "치주인대가 소실되어 치근이 골과 직접 융합된 상태.",
    example: "Ankylosis of #46 — metallic percussion tone, absent mobility, infraocclusion.",
    caution: "**타진음이 금속성**이고 동요가 전혀 없는 것이 단서. 교정적 이동이 불가능하다.",
  },
  { ko: "저위교합", en: "infraocclusion", section: "O", category: "치아·수복물", topic: "흡수·형성이상", order: 3,
    meaning: "인접치보다 교합면이 낮게 위치한 상태. 유착치에서 흔하다.",
    example: "Infraocclusion of #85 by approximately 2 mm.",
  },
  { ko: "법랑질 형성부전", en: "enamel hypoplasia / hypomineralization", section: "A", category: "치아·수복물", topic: "흡수·형성이상", order: 4,
    meaning: "법랑질의 양적 결함(hypoplasia) 또는 질적 결함(hypomineralization).",
    variants: "<dl><dt>hypoplasia</dt><dd><b>양적</b> 결함 — 표면 함몰·홈</dd><dt>hypomineralization</dt><dd><b>질적</b> 결함 — 두께는 정상, 불투명 반점</dd><dt>MIH</dt><dd>molar-incisor hypomineralization</dd></dl>",
    example: "Demarcated opacities on #16, 26 and incisors — consistent with MIH.",
  },
  { ko: "치수강 폐쇄", en: "pulp canal obliteration (calcific metamorphosis)", section: "O", category: "치아·수복물", topic: "흡수·형성이상", order: 5,
    meaning: "외상·자극 후 경조직 침착으로 치수강이 좁아지거나 사라진 상태.",
    example: "Pulp canal obliteration of #11 with yellowish crown discoloration.",
    caution: "**무증상이면 즉시 근관치료 대상이 아니다** — 병소 발생 시 개입하는 것이 통례.",
  },

  // ── 치아·수복물 · 근관 관련 ──
  { ko: "치근 천공", en: "root perforation", section: "A", category: "치아·수복물", topic: "근관 관련", order: 1,
    meaning: "근관 내부와 치주조직이 인위적·병적으로 통하게 된 것.",
    variants: "<dl><dt>strip perforation</dt><dd>만곡 치근 <b>내면이 얇아져</b> 생긴 세장형 천공</dd><dt>furcal perforation</dt><dd>근분지부 천공 — 예후 불량</dd></dl>",
    example: "Furcal perforation of #36 repaired with MTA.",
  },
  { ko: "계단 형성", en: "ledge", section: "O", category: "치아·수복물", topic: "근관 관련", order: 2,
    meaning: "근관 형성 중 만곡부 바깥쪽에 생긴 인위적 단차. 원래 근관으로의 접근을 막는다.",
    example: "Ledge at the apical third of the mesiobuccal canal.",
  },
  { ko: "기구 파절", en: "separated (fractured) instrument", section: "O", category: "치아·수복물", topic: "근관 관련", order: 3,
    meaning: "근관 내에 파절되어 잔존한 기구.",
    example: "Separated instrument in the apical third of the distal canal of #46.",
    caution: "**환자 고지 의무 사항**이다. 위치·길이와 설명 내용을 기록한다.",
  },
  { ko: "근관충전 과충전 / 미달", en: "overfilling / underfilling (short fill)", section: "O", category: "치아·수복물", topic: "근관 관련", order: 4,
    meaning: "근관충전재가 근단공을 넘거나 미치지 못한 상태.",
    example: "Underfilled root canal, 3 mm short of the radiographic apex.",
  },

  // ── 치아·수복물 · 보철 설계 ──
  { ko: "지대치", en: "abutment", section: "O·A", category: "치아·수복물", topic: "보철 설계", order: 1,
    meaning: "보철물을 지지·유지하는 치아 또는 임플란트.",
    example: "Abutment teeth #34 and #44 for the mandibular RPD.",
    caution: "임플란트에서는 **fixture 위에 체결하는 부품**을 뜻해 의미가 다르다 — 문맥을 분명히.",
  },
  { ko: "유지형태 / 저항형태", en: "retention form / resistance form", section: "O", category: "치아·수복물", topic: "보철 설계", order: 2,
    meaning: "보철물의 탈락(축방향)에 저항하는 형태 / 회전·측방 변위에 저항하는 형태.",
    example: "Inadequate resistance form due to short axial walls — auxiliary grooves placed.",
    caution: "“유지가 부족하다”를 영어로 옮길 때 **어느 쪽인지 구분**해야 처치가 달라진다. 축벽이 짧으면 taper를 줄여도 해결되지 않고 **홈·box**가 필요하다.",
  },
  { ko: "착탈로", en: "path of insertion (path of placement)", section: "O", category: "치아·수복물", topic: "보철 설계", order: 3,
    meaning: "보철물이 삽입·제거되는 방향.",
    example: "Single path of insertion confirmed; abutment preparations parallel.",
  },
  { ko: "서베이 라인", en: "survey line (height of contour)", section: "O", category: "치아·수복물", topic: "보철 설계", order: 4,
    meaning: "착탈로에서 본 치아의 최대풍융선. 유지부와 비유지부를 가른다.",
    example: "Survey line placed at the middle third; 0.25 mm undercut at the distobuccal.",
  },
  { ko: "간접유지", en: "indirect retention", section: "O", category: "치아·수복물", topic: "보철 설계", order: 5,
    meaning: "유리단 의치가 조직에서 들리는 회전을 막는 요소. fulcrum line에 수직으로 멀리 배치.",
    example: "Indirect retention provided by cingulum rests on #33 and #43.",
  },
  { ko: "pontic 형태", en: "pontic design", section: "O", category: "치아·수복물", topic: "보철 설계", order: 6,
    meaning: "가공치의 조직면 형태.",
    variants: "<dl><dt>ovate</dt><dd>치조제에 <b>오목하게 함입</b> — 심미 최상, 부위 형성 필요</dd><dt>modified ridge lap</dt><dd>협측만 접촉 — <b>심미와 위생의 절충, 통상 선택</b></dd><dt>sanitary (hygienic)</dt><dd>치조제와 <b>이격</b> — 위생 최상, 비심미부</dd></dl>",
    example: "Modified ridge lap pontic at the #46 site.",
  },

  // ── 치주 · 계측 지표 ──
  { ko: "탐침 깊이", en: "probing depth (PD)", section: "O", category: "치주", topic: "계측 지표", order: 1,
    meaning: "치은연에서 열구·낭 기저부까지의 깊이.",
    example: "PD 3-3-4 / 3-3-5 mm at #46.",
    caution: "**PD와 CAL은 다르다.** 퇴축이 있으면 PD가 얕아도 부착 소실은 클 수 있다 — 둘 다 기재.",
  },
  { ko: "탐침 시 출혈", en: "bleeding on probing (BOP)", section: "O", category: "치주", topic: "계측 지표", order: 2,
    meaning: "탐침 후 출혈 여부. 전악 백분율로도 표기.",
    example: "BOP(+) at #46 buccal; full-mouth BOP 12%.",
    caution: "**탐침 10–30초 후** 판정한다. BOP(−)는 안정의 음성 예측에 유용하지만, BOP(+) 하나만으로 진행을 단정하지 않는다.",
  },
  { ko: "부착 소실", en: "clinical attachment loss (CAL)", section: "O", category: "치주", topic: "계측 지표", order: 3,
    meaning: "CEJ에서 부착 기저부까지의 거리. 실제 지지 소실량.",
    example: "CAL 6 mm at #36 mesial.",
  },
  { ko: "동요", en: "mobility", section: "O", category: "치주", topic: "계측 지표", order: 4,
    meaning: "치아의 흔들림. **대상에 따라 완전히 다른 단어를 쓴다.**",
    variants: "<dl><dt>치아</dt><dd><b>mobility</b> (Miller Class I–III)</dd><dt>임플란트 나사</dt><dd><b>screw loosening</b> — 임플란트 자체의 mobility는 골유착 실패를 뜻한다</dd><dt>의치</dt><dd><b>instability</b> / <b>loss of retention</b></dd><dt>보철물</dt><dd><b>decementation</b> (탈락) / <b>rocking</b> (미안착)</dd></dl>",
    example: "Mobility Class II at #35.",
    caution: "“흔들린다”를 전부 mobility로 옮기면 임플란트·의치 기록이 완전히 틀어진다.",
  },

  // ── 치주 · 조직 형태 ──
  { ko: "퇴축", en: "gingival recession (GR)", section: "O", category: "치주", topic: "조직 형태", order: 1,
    meaning: "치은연이 CEJ보다 근단측으로 이동한 상태.",
    example: "GR 2 mm on the buccal of #34, 35.",
  },
  { ko: "각화치은", en: "keratinized tissue (KT)", section: "O", category: "치주", topic: "조직 형태", order: 2,
    meaning: "치은연에서 MGJ까지의 각화된 조직 폭.",
    example: "KT width 2 mm on the buccal of #46 implant.",
    caution: "임플란트에서 **2 mm 미만**이면 위생 관리와 점막 건강에 불리하다는 보고가 축적되어 있다.",
  },
  { ko: "치은 비대", en: "gingival enlargement / overgrowth", section: "O", category: "치주", topic: "조직 형태", order: 3,
    meaning: "치은 조직의 증대.",
    example: "Generalized gingival enlargement, drug-associated pattern suspected.",
    caution: "`hyperplasia`는 조직학적 용어이므로 임상 기술에는 **enlargement / overgrowth**가 적절하다.",
  },
  { ko: "치주 표현형", en: "periodontal phenotype", section: "O", category: "치주", topic: "조직 형태", order: 4,
    meaning: "치은 두께와 각화치은 폭, 골 형태를 합친 개념.",
    example: "Thin periodontal phenotype with 1 mm keratinized tissue at #31.",
    caution: "**2017 World Workshop에서 `biotype` → `phenotype`으로 용어가 정리**되었다. phenotype은 환경에 따라 변할 수 있다는 함의를 담는다.",
  },
  { ko: "부착치은", en: "attached gingiva", section: "O", category: "치주", topic: "조직 형태", order: 5,
    meaning: "각화치은 중 하부 골·백악질에 부착된 부분.",
    example: "Attached gingiva 1 mm at #41 (KT 3 mm minus PD 2 mm).",
    caution: "**각화치은(KT)과 다르다** — 부착치은 = KT 폭 − 열구 깊이. 혼용하면 계산이 틀어진다.",
  },
  { ko: "치은 퇴축 분류", en: "recession type (Cairo RT1–RT3)", section: "A", category: "치주", topic: "조직 형태", order: 6,
    meaning: "인접부 부착 소실 정도에 따른 퇴축 분류. 근단 피개 예측에 쓰인다.",
    variants: "<dl><dt>RT1</dt><dd>인접부 부착 소실 없음 — <b>완전 피개 기대 가능</b></dd><dt>RT2</dt><dd>인접부 소실 ≤ 협측 소실 — 부분~완전</dd><dt>RT3</dt><dd>인접부 소실 &gt; 협측 소실 — <b>완전 피개 기대 어려움</b></dd></dl>",
    example: "Cairo RT1 recession, 3 mm, at #13 buccal.",
    caution: "Miller 분류도 여전히 쓰이나, **인접부 부착 수준을 기준으로 하는 Cairo 분류**가 예측성이 높다는 평가를 받는다.",
  },

  // ── 치주 · 골 결손 ──
  { ko: "근분지부 병소", en: "furcation involvement", section: "O·A", category: "치주", topic: "골 결손", order: 1,
    meaning: "다근치의 근분지부에 부착이 소실된 상태.",
    example: "Furcation involvement Grade II on the buccal of #36 (Glickman).",
    caution: "분류 체계(**Glickman I–IV** / Hamp I–III)를 명시할 것.",
  },
  { ko: "치조골 열개 / 천공", en: "dehiscence / fenestration", section: "O", category: "치주", topic: "골 결손", order: 2,
    meaning: "치근을 덮는 협측 골판의 결손.",
    variants: "<dl><dt>dehiscence</dt><dd>골정에서 <b>이어져 내려온</b> V자 결손</dd><dt>fenestration</dt><dd>골정은 보존되고 <b>중간에 창처럼</b> 뚫린 결손</dd></dl>",
    example: "Buccal dehiscence at #23 noted on flap elevation.",
  },
  { ko: "골내 결손", en: "intrabony (infrabony) defect", section: "O", category: "치주", topic: "골 결손", order: 3,
    meaning: "결손 기저부가 인접 골정보다 근단측에 있는 수직 결손. 벽 수로 세분.",
    example: "Three-wall intrabony defect at the mesial of #36, depth 5 mm.",
    caution: "**잔존 벽 수(1·2·3-wall)** 가 재생 술식의 예후를 좌우하므로 반드시 기재.",
  },
  { ko: "치근 이개부 길이", en: "root trunk length", section: "O", category: "치주", topic: "골 결손", order: 4,
    meaning: "CEJ에서 근분지 입구까지의 거리.",
    example: "Short root trunk at #16 — furcation entrance close to the CEJ.",
    caution: "**짧을수록 근분지부 병소가 빨리 노출**되고, 길수록 일단 노출되면 접근이 어렵다.",
  },
  { ko: "치근 함몰", en: "root concavity", section: "O", category: "치주", topic: "골 결손", order: 5,
    meaning: "치근면의 오목한 함몰. 기구 접근과 위생을 어렵게 한다.",
    example: "Prominent mesial root concavity of #14.",
  },

  // ── 치주 · 진단·판정 ──
  { ko: "가성낭", en: "pseudopocket", section: "A", category: "치주", topic: "진단·판정", order: 1,
    meaning: "부착 소실 없이 치은 비대만으로 깊어진 낭.",
    example: "Pseudopockets 4–5 mm with CAL within normal limits.",
  },
  { ko: "생물학적 폭경 침범", en: "violation of the supracrestal tissue attachment", section: "A", category: "치주", topic: "진단·판정", order: 2,
    meaning: "수복 변연이 부착 조직 영역을 침범한 상태.",
    example: "Violation of the supracrestal tissue attachment at the distal of #46 — bone sounding 1.5 mm from the planned margin.",
    caution: "**2017 World Workshop 이후 공식 용어가 supracrestal tissue attachment**로 정리되었다. `biologic width`는 구용어로, 병용하더라도 새 용어를 우선한다.",
  },
  { ko: "괴사성 치주질환", en: "necrotizing periodontal disease", section: "A", category: "치주", topic: "진단·판정", order: 3,
    meaning: "유두 괴사·통증·출혈을 특징으로 하는 급성 질환.",
    variants: "<dl><dt>necrotizing gingivitis</dt><dd>치은에 국한</dd><dt>necrotizing periodontitis</dt><dd>부착·골 소실 동반</dd></dl>",
    example: "Necrotizing gingivitis — punched-out interdental papillae with pseudomembrane and halitosis.",
  },
  { ko: "치주-치수 병소", en: "endo-perio lesion", section: "A", category: "치주", topic: "진단·판정", order: 4,
    meaning: "치수와 치주 병변이 연결된 상태.",
    example: "Endo-perio lesion at #36 — necrotic pulp with a deep isolated periodontal defect.",
    caution: "**어느 쪽이 원발인지**에 따라 처치 순서와 예후가 달라진다. 치수 검사 결과를 반드시 함께 기재.",
  },

  // ── 치주 · 기본 소견 ──
  { ko: "치태 / 치석", en: "plaque (biofilm) / calculus", section: "O", category: "치주", topic: "기본 소견", order: 1,
    meaning: "연성 세균막 / 석회화된 침착물.",
    example: "Heavy supragingival calculus on the lingual of the mandibular anteriors; plaque score 70%.",
    caution: "`supragingival`(치은연상) / `subgingival`(치은연하)를 함께 적는다.",
  },
  { ko: "배농", en: "suppuration / purulent exudate", section: "O", category: "치주", topic: "기본 소견", order: 2,
    meaning: "농이 나오는 것.",
    example: "Suppuration on probing at #36 distal.",
  },

  // ── 치주 · 교합 외상 ──
  { ko: "진동 (교합 외상)", en: "fremitus", section: "O", category: "치주", topic: "교합 외상", order: 1,
    meaning: "기능 접촉 시 치아에서 느껴지는 진동. 손가락을 순면에 대고 폐구시켜 확인.",
    example: "Fremitus detected on #11, 21 during tapping.",
    caution: "교합 외상의 임상 지표. **mobility와 다른 소견**이므로 별도로 기재.",
  },

  // ── 치수·치근단 · 증상 기술 ──
  { ko: "자극 후 지속통", en: "lingering pain", section: "O", category: "치수·치근단", topic: "증상 기술", order: 1,
    meaning: "자극을 제거한 뒤에도 통증이 지속되는 것.",
    example: "Cold test #36: lingering pain persisting approximately 20 seconds after stimulus removal.",
    caution: "**비가역성 치수염을 가르는 핵심 소견.** 지속 시간을 초 단위로 적는다.",
  },
  { ko: "자발통 / 야간통", en: "spontaneous pain / nocturnal pain", section: "O", category: "치수·치근단", topic: "증상 기술", order: 2,
    meaning: "유발 자극 없이 발생하는 통증 / 야간에 악화되는 통증.",
    example: "Patient reports spontaneous, nocturnal pain unrelieved by analgesics.",
  },

  // ── 치수·치근단 · 진단명 ──
  { ko: "가역성 치수염", en: "reversible pulpitis", section: "A", category: "치수·치근단", topic: "진단명", order: 1,
    meaning: "자극 시에만 통증이 있고 제거 시 즉시 소실되는 치수 염증.",
    example: "Reversible pulpitis #16.",
  },
  { ko: "비가역성 치수염", en: "symptomatic irreversible pulpitis", section: "A", category: "치수·치근단", topic: "진단명", order: 2,
    meaning: "지속통·자발통을 동반해 치수 회복이 기대되지 않는 상태.",
    example: "Symptomatic irreversible pulpitis with symptomatic apical periodontitis, #36.",
    caution: "**증상 유무를 접두어로 명시**하는 것이 현행 표준 표기다 — `symptomatic` / `asymptomatic`.",
  },
  { ko: "치수 괴사", en: "pulp necrosis", section: "A", category: "치수·치근단", topic: "진단명", order: 3,
    meaning: "치수 조직이 괴사한 상태.",
    example: "Pulp necrosis #21 with asymptomatic apical periodontitis.",
  },
  { ko: "치근단 치주염", en: "apical periodontitis", section: "A", category: "치수·치근단", topic: "진단명", order: 4,
    meaning: "치근단 조직의 염증.",
    variants: "<dl><dt>symptomatic apical periodontitis</dt><dd>타진통·저작통 동반</dd><dt>asymptomatic apical periodontitis</dt><dd>무증상, 방사선 병소만</dd><dt>acute apical abscess</dt><dd>급성 농양 — 부종·배농·전신 증상 가능</dd><dt>chronic apical abscess</dt><dd>만성 — <b>sinus tract 동반</b></dd></dl>",
    example: "Asymptomatic apical periodontitis #35 — well-defined periapical radiolucency, Perc(−).",
  },

  // ── 치수·치근단 · 방사선 소견 ──
  { ko: "방사선 투과상", en: "radiolucency", section: "O", category: "치수·치근단", topic: "방사선 소견", order: 1,
    meaning: "방사선상 어둡게 보이는 영역.",
    example: "Well-defined periapical radiolucency approximately 4 mm in diameter at the apex of #35.",
    caution: "**소견(O)** 이다. 이를 근거로 붙이는 진단명(apical periodontitis 등)은 A로 간다. 경계(well-defined / diffuse)와 크기를 함께.",
  },

  // ── 교합·악관절 · 교합 접촉 ──
  { ko: "조기접촉", en: "premature contact", section: "O", category: "교합·악관절", topic: "교합 접촉", order: 1,
    meaning: "다른 치아보다 먼저 닿는 접촉.",
    example: "Premature contact at the mesial incline of #36 in centric relation.",
  },
  { ko: "간섭", en: "interference", section: "O", category: "교합·악관절", topic: "교합 접촉", order: 2,
    meaning: "편심 운동을 방해하는 접촉.",
    variants: "<dl><dt>working interference</dt><dd>작업측 간섭</dd><dt>non-working (balancing) interference</dt><dd>비작업측 간섭 — <b>원칙적으로 제거</b></dd><dt>protrusive interference</dt><dd>전방운동 간섭</dd></dl>",
    example: "Non-working interference on the mesiolingual cusp of #26 during left lateral excursion.",
  },
  { ko: "활주", en: "slide (CR–MIP slide)", section: "O", category: "교합·악관절", topic: "교합 접촉", order: 3,
    meaning: "중심위에서 최대교두감합위로 이동하는 거리.",
    example: "CR–MIP slide 1.0 mm in the anterior direction.",
    caution: "**방향과 양(mm)** 을 함께 기재한다.",
  },
  { ko: "견치 유도 / 군기능", en: "canine guidance / group function", section: "O", category: "교합·악관절", topic: "교합 접촉", order: 4,
    meaning: "측방 운동 시 유도를 담당하는 치아 양식.",
    example: "Group function on the right; canine guidance on the left.",
  },
  { ko: "교합 붕괴", en: "occlusal collapse", section: "A", category: "교합·악관절", topic: "교합 접촉", order: 5,
    meaning: "후방 지지 상실 후 교합고경·전치 관계가 연쇄적으로 무너진 상태.",
    example: "Posterior bite collapse with anterior flaring and loss of vertical dimension.",
  },
  { ko: "병적 치아 이동", en: "pathologic tooth migration", section: "O", category: "교합·악관절", topic: "교합 접촉", order: 6,
    meaning: "치주 지지 소실·교합력으로 치아가 위치를 이탈한 것. 전치 순측 경사·이개가 흔하다.",
    example: "Pathologic migration of #11, 21 with developing midline diastema.",
  },
  { ko: "전방유도", en: "anterior guidance", section: "O", category: "교합·악관절", topic: "교합 접촉", order: 7,
    meaning: "전방 운동 시 전치가 구치를 이개시키는 유도.",
    example: "Anterior guidance absent — posterior contacts persist in protrusion.",
  },
  { ko: "구치 이개", en: "posterior disclusion", section: "O", category: "교합·악관절", topic: "교합 접촉", order: 8,
    meaning: "편심 운동 시 구치가 떨어지는 것.",
    example: "Immediate posterior disclusion on both lateral excursions.",
  },
  { ko: "교합 외상", en: "occlusal trauma", section: "A", category: "교합·악관절", topic: "교합 접촉", order: 9,
    meaning: "교합력에 의한 치주 조직 손상.",
    variants: "<dl><dt>primary occlusal trauma</dt><dd><b>정상 지지</b> 치주에 과도한 힘</dd><dt>secondary occlusal trauma</dt><dd><b>이미 감소된 지지</b>에 정상~과도한 힘</dd></dl>",
    example: "Secondary occlusal trauma at #35 — Mobility II with reduced bone support and fremitus.",
  },

  // ── 교합·악관절 · 하악 운동 ──
  { ko: "개구 제한", en: "limited (restricted) mouth opening", section: "O", category: "교합·악관절", topic: "하악 운동", order: 1,
    meaning: "최대 개구가 정상 범위 미만인 상태.",
    example: "Maximum opening 32 mm — restricted.",
    caution: "통상 **40 mm 미만**을 제한으로 본다. 무통 개구와 최대 개구를 구분해 기재.",
  },
  { ko: "편위 / 편향", en: "deviation / deflection", section: "O", category: "교합·악관절", topic: "하악 운동", order: 2,
    meaning: "개구 시 하악 정중선의 이동 양상. **두 단어의 의미가 다르다.**",
    variants: "<dl><dt>deviation</dt><dd>개구 중 편위했다가 <b>정중선으로 복귀</b> — 정복성 디스크 변위 시사</dd><dt>deflection</dt><dd>편위한 채 <b>복귀하지 않음</b> — 비정복성 변위·유착 시사</dd></dl>",
    example: "Deflection to the left at maximum opening.",
    caution: "혼용하면 진단 방향이 반대가 된다.",
  },

  // ── 교합·악관절 · TMJ — 디스크·운동 ──
  { ko: "관절음", en: "joint sound: click / crepitus", section: "O", category: "교합·악관절", topic: "TMJ — 디스크·운동", order: 1,
    meaning: "악관절에서 나는 소리.",
    variants: "<dl><dt>click</dt><dd>짧고 뚜렷한 소리 — 디스크 변위 시사</dd><dt>reciprocal click</dt><dd>개구·폐구 <b>양쪽</b>에서 발생</dd><dt>crepitus</dt><dd>거친 마찰음 — <b>퇴행성 변화</b> 시사</dd></dl>",
    example: "Opening click at the left TMJ; no crepitus.",
    caution: "**어느 시점**(opening / closing)에 나는지 기재. 무증상 click은 그 자체로 치료 대상이 아니다.",
  },
  { ko: "잠김", en: "locking (closed / open lock)", section: "O·A", category: "교합·악관절", topic: "TMJ — 디스크·운동", order: 2,
    meaning: "하악이 특정 위치에서 움직이지 않는 상태.",
    variants: "<dl><dt>closed lock</dt><dd><b>입이 벌어지지 않음</b> — 비정복성 디스크 변위</dd><dt>open lock</dt><dd><b>입이 다물어지지 않음</b> — 과두 아탈구</dd></dl>",
    example: "History of intermittent closed lock, currently resolved.",
  },
  { ko: "정복성 디스크 변위", en: "disc displacement with reduction", section: "A", category: "교합·악관절", topic: "TMJ — 디스크·운동", order: 3,
    meaning: "개구 시 전위된 디스크가 과두 위로 되돌아오는(정복되는) 상태. 개구·폐구 시 상호성 click이 전형.",
    variants: "<dl><dt>with reduction</dt><dd>정복됨 — click 동반, 개구량 대개 정상</dd><dt>with reduction, with intermittent locking</dt><dd>간헐적으로 정복되지 않아 일시적 잠김</dd><dt>without reduction</dt><dd>정복 안 됨 — click 소실, 개구 제한 가능</dd></dl>",
    example: "Disc displacement with reduction, left TMJ — reciprocal click, MO 46 mm.",
    caution: "DC/TMD의 정식 진단 범주다. **click이 사라졌다 = 좋아졌다가 아니다** — 비정복성으로 이행하며 소리가 없어지는 경우가 있다.",
  },
  { ko: "비정복성 디스크 변위", en: "disc displacement without reduction", section: "A", category: "교합·악관절", topic: "TMJ — 디스크·운동", order: 4,
    meaning: "디스크가 정복되지 않아 과두 전방에 남아 개구를 방해하는 상태.",
    variants: "<dl><dt>with limited opening</dt><dd>급성 <b>closed lock</b> — 개구 제한 동반</dd><dt>without limited opening</dt><dd>만성기, 개구량 회복됨</dd></dl>",
    example: "Disc displacement without reduction with limited opening, right TMJ — MO 28 mm, deflection to the right.",
  },
  { ko: "아탈구 / 탈구", en: "subluxation / dislocation (open lock)", section: "A", category: "교합·악관절", topic: "TMJ — 디스크·운동", order: 5,
    meaning: "과두가 관절융기를 넘어 전방으로 이동한 상태.",
    variants: "<dl><dt>subluxation</dt><dd>환자가 <b>스스로 복위</b> 가능</dd><dt>dislocation (open lock)</dt><dd><b>타인의 도수 정복 필요</b> — 입이 다물어지지 않음</dd></dl>",
    example: "History of recurrent subluxation on wide opening; self-reducible.",
  },
  { ko: "관절 유착", en: "adhesion / adherence", section: "A", category: "교합·악관절", topic: "TMJ — 디스크·운동", order: 6,
    meaning: "관절면 사이의 일시적(adherence) 또는 섬유성(adhesion) 부착으로 활주가 제한된 상태.",
    example: "Suspected adhesion of the superior joint space — restricted translation with normal rotation.",
  },
  { ko: "관절 강직", en: "ankylosis (fibrous / bony)", section: "A", category: "교합·악관절", topic: "TMJ — 디스크·운동", order: 7,
    meaning: "관절 구조가 섬유성 또는 골성으로 융합되어 운동이 소실된 상태.",
    example: "Bony ankylosis of the left TMJ; MO 12 mm.",
    caution: "**개구 제한의 최중증 원인**이며 보철 전 반드시 감별. 도수 조작으로 개선되지 않는다.",
  },
  { ko: "관절원판후조직", en: "retrodiscal tissue", section: "O", category: "교합·악관절", topic: "TMJ — 디스크·운동", order: 8,
    meaning: "디스크 후방의 혈관·신경이 풍부한 조직. 디스크 전방 변위 시 과두 아래 눌려 통증원이 된다.",
    example: "Tenderness over the retrodiscal area on posterior palpation.",
  },
  { ko: "관절통", en: "arthralgia", section: "A", category: "교합·악관절", topic: "TMJ — 디스크·운동", order: 9,
    meaning: "악관절 기원의 통증. 촉진·기능 시 재현되는 것이 진단 요건.",
    example: "Arthralgia of the left TMJ — familiar pain reproduced on lateral pole palpation.",
    caution: "DC/TMD에서는 **“familiar pain(환자가 평소 겪던 그 통증)”이 재현되는지**가 핵심 기준이다.",
  },

  // ── 교합·악관절 · 파라펑션 ──
  { ko: "이갈이 / 이악물기", en: "sleep bruxism / awake bruxism (clenching)", section: "A", category: "교합·악관절", topic: "파라펑션", order: 1,
    meaning: "수면 중 또는 각성 중의 파라펑션 근활동.",
    example: "Probable sleep bruxism — wear facets with matching antagonists, morning jaw stiffness, sleep partner report.",
    caution: "국제 합의는 건강한 개인에서 이를 **질환이 아니라 근활동**으로 규정한다. 확진이 어려운 경우 `probable`을 붙이는 것이 정확하다.",
  },

  // ── 교합·악관절 · 근육 ──
  { ko: "근막통", en: "myalgia / myofascial pain", section: "A", category: "교합·악관절", topic: "근육", order: 1,
    meaning: "저작근 기원의 통증.",
    example: "Myalgia of the masseter and temporalis bilaterally (DC/TMD).",
    caution: "**연관통(referred pain)** 이 치통으로 오인되는 일이 흔하다 — 치수 검사가 정상인데 통증이 지속되면 근육을 촉진할 것.",
  },
  { ko: "연관통", en: "referred pain", section: "O", category: "교합·악관절", topic: "근육", order: 2,
    meaning: "자극 부위를 넘어 다른 부위에서 느껴지는 통증.",
    example: "Palpation of the left masseter reproduced referred pain to the mandibular molars.",
    caution: "**치통으로 오인되어 불필요한 근관치료·발치가 이루어지는 대표 원인.** 치수 검사가 정상인데 통증이 지속되면 근육을 촉진할 것.",
  },
  { ko: "근경축", en: "myospasm", section: "A", category: "교합·악관절", topic: "근육", order: 3,
    meaning: "갑작스러운 불수의적 근수축으로 개구 제한과 통증을 동반.",
    example: "Acute myospasm of the left medial pterygoid — sudden onset limited opening.",
  },
  { ko: "근염", en: "myositis", section: "A", category: "교합·악관절", topic: "근육", order: 4,
    meaning: "외상·감염에 이은 근육의 염증. 부종·발적을 동반할 수 있다.",
    example: "Myositis of the masseter following third molar surgery.",
  },
  { ko: "구축", en: "contracture", section: "A", category: "교합·악관절", topic: "근육", order: 5,
    meaning: "근·건의 섬유화로 신장이 제한되어 개구가 영구적으로 줄어든 상태.",
    example: "Contracture of the temporalis following prolonged immobilization.",
  },
  { ko: "개구장애", en: "trismus", section: "O", category: "교합·악관절", topic: "근육", order: 6,
    meaning: "근육 원인으로 입이 벌어지지 않는 상태.",
    example: "Trismus with MO 22 mm following inferior alveolar nerve block.",
    caution: "`limited opening`이 더 넓은 기술적 표현이고, **trismus는 근육 기원을 함의**한다. 관절 원인이면 trismus라 쓰지 않는 편이 정확하다.",
  },
  { ko: "교근 비대", en: "masseteric hypertrophy", section: "O", category: "교합·악관절", topic: "근육", order: 7,
    meaning: "교근의 용적 증가. 이악물기와 연관될 수 있다.",
    example: "Bilateral masseteric hypertrophy on clenching.",
  },

  // ── 교합·악관절 · TMJ — 골 변화 ──
  { ko: "퇴행성 관절질환", en: "degenerative joint disease (DJD)", section: "A", category: "교합·악관절", topic: "TMJ — 골 변화", order: 1,
    meaning: "관절면의 퇴행성 변화. 통증 유무로 하위 구분.",
    variants: "<dl><dt>osteoarthritis</dt><dd>퇴행성 변화 + <b>통증 동반</b></dd><dt>osteoarthrosis</dt><dd>퇴행성 변화, <b>무증상</b></dd></dl>",
    example: "Degenerative joint disease (osteoarthrosis) of the right condyle — flattening and osteophyte, no arthralgia.",
    caution: "한국어로는 둘 다 “퇴행성”으로 뭉뚱그려지기 쉬우나, **영어 표기는 통증 유무로 갈린다.**",
  },
  { ko: "과두 편평화", en: "condylar flattening", section: "O", category: "교합·악관절", topic: "TMJ — 골 변화", order: 2,
    meaning: "과두 상면의 볼록한 윤곽이 평탄해진 것. 퇴행성 변화의 초기 소견.",
    example: "Flattening of the anterosuperior aspect of the right condyle on CBCT.",
  },
  { ko: "골극", en: "osteophyte", section: "O", category: "교합·악관절", topic: "TMJ — 골 변화", order: 3,
    meaning: "관절면 변연에 형성된 골 돌기.",
    example: "Osteophyte at the anterior margin of the left condyle.",
  },
  { ko: "관절면 미란", en: "erosion (of the articular surface)", section: "O", category: "교합·악관절", topic: "TMJ — 골 변화", order: 4,
    meaning: "피질골이 소실되어 윤곽이 끊긴 상태. **활동성 변화**를 시사.",
    example: "Cortical erosion of the superior condylar surface, right TMJ.",
    caution: "치아의 erosion(산 침식)과 **동음이의**다 — 문맥을 분명히 할 것.",
  },
  { ko: "연골하 경화", en: "subchondral sclerosis", section: "O", category: "교합·악관절", topic: "TMJ — 골 변화", order: 5,
    meaning: "관절면 하방 골의 불투과성 증가. 부하에 대한 반응.",
    example: "Subchondral sclerosis of the condylar head.",
  },
  { ko: "연골하 낭", en: "subchondral cyst (Ely cyst)", section: "O", category: "교합·악관절", topic: "TMJ — 골 변화", order: 6,
    meaning: "연골 하방에 형성된 낭성 투과상. 가성낭(pseudocyst)에 해당.",
    example: "Subchondral pseudocyst within the left condyle.",
  },
  { ko: "과두 흡수", en: "condylar resorption", section: "A", category: "교합·악관절", topic: "TMJ — 골 변화", order: 7,
    meaning: "과두 용적이 진행성으로 감소하는 상태. 진행 시 하악 후퇴·전방개교합을 초래.",
    variants: "<dl><dt>idiopathic condylar resorption (ICR)</dt><dd>원인 불명, 젊은 여성에 호발</dd><dt>progressive condylar resorption</dt><dd>진행성임을 강조하는 표현</dd></dl>",
    example: "Progressive condylar resorption with developing anterior open bite.",
    caution: "**교합 재구성·악교정 전 반드시 활성도 확인.** 활동성 흡수 중에 보철을 완성하면 교합이 다시 무너진다.",
  },
  { ko: "첨형 과두", en: "pencil-shaped (beak-shaped) condyle", section: "O", category: "교합·악관절", topic: "TMJ — 골 변화", order: 8,
    meaning: "고도 흡수로 과두가 가늘고 뾰족하게 변한 형태.",
    example: "Pencil-shaped condyle bilaterally, consistent with advanced condylar resorption.",
    caution: "**형태 기술 용어이며 공식 분류명이 아니다.** 소견은 형태로 적고, 진단명은 condylar resorption / DJD 로 별도 기재하는 편이 안전하다.",
  },
  { ko: "이단 과두", en: "bifid condyle", section: "O", category: "교합·악관절", topic: "TMJ — 골 변화", order: 9,
    meaning: "과두 두부가 두 개의 융기로 나뉜 형태 이상. 대개 우연히 발견.",
    example: "Bifid condyle noted on the right, asymptomatic.",
  },
  { ko: "과두 과형성", en: "condylar hyperplasia", section: "A", category: "교합·악관절", topic: "TMJ — 골 변화", order: 10,
    meaning: "과두의 과성장으로 안면 비대칭·교합 편위를 일으키는 상태.",
    example: "Condylar hyperplasia on the left with mandibular deviation and occlusal cant.",
  },
  { ko: "관절강 협착", en: "narrowed joint space", section: "O", category: "교합·악관절", topic: "TMJ — 골 변화", order: 11,
    meaning: "과두와 관절와 사이 간격의 감소.",
    example: "Narrowed superior joint space on the closed-mouth view.",
  },

  // ── 교합·악관절 · 교합 이론·기록 ──
  { ko: "교합기", en: "articulator (arcon / non-arcon)", section: "O", category: "교합·악관절", topic: "교합 이론·기록", order: 1,
    meaning: "악관절과 하악 운동을 모사하는 기계 장치.",
    variants: "<dl><dt>arcon</dt><dd>과두 요소가 <b>하악 부재</b>에 — 해부학적 배치와 일치</dd><dt>non-arcon</dt><dd>과두 요소가 <b>상악 부재</b>에 — 개구 시 과로 경사가 변함</dd></dl>",
    example: "Mounted on a semi-adjustable arcon articulator with facebow transfer.",
  },
  { ko: "안궁 이전", en: "facebow transfer", section: "O", category: "교합·악관절", topic: "교합 이론·기록", order: 2,
    meaning: "상악과 과두 축의 관계를 교합기에 옮기는 절차.",
    variants: "<dl><dt>arbitrary facebow</dt><dd>해부학적 표준점 사용 — 통상 임상</dd><dt>kinematic facebow</dt><dd><b>실제 개폐 축을 측정</b> — VDO를 크게 바꾸는 증례</dd></dl>",
    example: "Arbitrary facebow transfer completed.",
    caution: "VDO를 변경하는 증례에서는 축 오차가 교합 오차로 증폭된다 — **개교합량이 클수록 kinematic 축의 이점**이 커진다.",
  },
  { ko: "개폐 축", en: "terminal hinge axis", section: "O", category: "교합·악관절", topic: "교합 이론·기록", order: 3,
    meaning: "중심위에서 하악이 순수 회전할 때의 가상 축.",
    example: "Terminal hinge axis located kinematically prior to increasing the vertical dimension.",
  },
  { ko: "시상 과로 경사", en: "sagittal condylar inclination", section: "O", category: "교합·악관절", topic: "교합 이론·기록", order: 4,
    meaning: "전방 운동 시 과두가 관절 융기를 따라 내려가는 시상면 각도.",
    example: "Sagittal condylar inclination set to 35 degrees from the protrusive record.",
  },
  { ko: "Bennett 운동 / 각", en: "Bennett movement / Bennett angle", section: "O", category: "교합·악관절", topic: "교합 이론·기록", order: 5,
    meaning: "측방 운동 시 하악 전체의 측방 이동(Bennett movement)과, 비작업측 과두가 시상면과 이루는 각(Bennett angle).",
    variants: "<dl><dt>immediate side shift</dt><dd>운동 초기에 <b>즉시</b> 일어나는 측방 이동 — 구치부 형태에 영향이 큼</dd><dt>progressive side shift</dt><dd>운동과 함께 <b>점진적</b>으로 일어남</dd></dl>",
    example: "Bennett angle 12 degrees; minimal immediate side shift.",
    caution: "**즉시 측방 이동이 클수록 구치 교두 경사를 낮춰야** 간섭이 생기지 않는다.",
  },
  { ko: "Christensen 현상", en: "Christensen phenomenon", section: "O", category: "교합·악관절", topic: "교합 이론·기록", order: 6,
    meaning: "전방·측방 운동 시 후방에 생기는 쐐기 모양의 이개 공간.",
    example: "Posterior open space consistent with the Christensen phenomenon during protrusion.",
    caution: "총의치에서 이 공간을 메우기 위해 **보상만곡**을 부여한다.",
  },
  { ko: "Spee 만곡 / Wilson 만곡", en: "curve of Spee / curve of Wilson", section: "O", category: "교합·악관절", topic: "교합 이론·기록", order: 7,
    meaning: "교합면의 전후방 만곡(Spee) / 협설측 만곡(Wilson).",
    example: "Exaggerated curve of Spee limiting restorative space in the mandibular posterior region.",
  },
  { ko: "보상 만곡", en: "compensating curve", section: "O", category: "교합·악관절", topic: "교합 이론·기록", order: 8,
    meaning: "총의치에서 균형교합을 얻기 위해 인공치 배열에 부여하는 만곡.",
    example: "Compensating curve established to achieve balanced articulation.",
  },
  { ko: "균형교합", en: "balanced occlusion", section: "O", category: "교합·악관절", topic: "교합 이론·기록", order: 9,
    meaning: "중심위와 편심위 모두에서 양측 다수 치아가 동시 접촉하는 교합 양식. 총의치의 안정을 위한 개념.",
    variants: "<dl><dt>bilateral balanced</dt><dd>양측 균형 — 전통적 총의치</dd><dt>lingualized</dt><dd><b>상악 설측교두만</b> 주 접촉 — 흡수 심한 증례에 유리</dd><dt>monoplane</dt><dd>무교두 — 안정성 우선</dd><dt>canine guided</dt><dd>자연치 수복의 표준적 선택지</dd></dl>",
    example: "Lingualized occlusion selected due to severe mandibular ridge resorption.",
    caution: "**자연치 수복에 균형교합을 그대로 적용하지 않는다** — 비작업측 접촉은 자연치에서 간섭이 된다.",
  },
  { ko: "중심 자유역", en: "freedom in centric (long centric)", section: "O", category: "교합·악관절", topic: "교합 이론·기록", order: 10,
    meaning: "CR과 MIP 사이에서 수직 고경 변화 없이 전후방으로 활주할 수 있도록 부여한 여유.",
    example: "Approximately 0.5 mm of freedom in centric provided in the restored occlusion.",
  },
  { ko: "전방·후방 결정 요소", en: "anterior / posterior determinants", section: "O", category: "교합·악관절", topic: "교합 이론·기록", order: 11,
    meaning: "하악 운동을 규정하는 요소. 전방은 전치 유도, 후방은 악관절.",
    example: "Posterior determinants recorded with a protrusive interocclusal record.",
    caution: "**후방 결정 요소는 바꿀 수 없고 전방 유도는 술자가 설계할 수 있다** — 교합 재구성의 출발점이 여기다.",
  },

  // ── 의치 · 평가 축 ──
  { ko: "유지 / 안정 / 지지", en: "retention / stability / support", section: "O", category: "의치", topic: "평가 축", order: 1,
    meaning: "의치 평가의 세 축. **호소를 이 셋으로 나누면 원인이 좁혀진다.**",
    variants: "<dl><dt>retention</dt><dd><b>이탈(수직 탈락)에 대한 저항</b> — “빠진다·들린다” → border seal·post-dam</dd><dt>stability</dt><dd><b>수평·회전력에 대한 저항</b> — “움직인다·돌아간다” → 교합·연마면 형태·neutral zone</dd><dt>support</dt><dd><b>수직 압력에 대한 저항</b> — “아프다” → 지지영역·과압박</dd></dl>",
    example: "Retention poor, stability fair, support adequate for the mandibular denture.",
  },
  { ko: "중립대", en: "neutral zone", section: "O", category: "의치", topic: "평가 축", order: 2,
    meaning: "혀와 협·순근의 힘이 상쇄되는 공간. 인공치·연마면을 여기에 두면 안정이 개선된다.",
    example: "Neutral zone technique used for the mandibular denture due to severe resorption.",
  },
  { ko: "연마면 형태", en: "polished surface contour", section: "O", category: "의치", topic: "평가 축", order: 3,
    meaning: "의치의 외면 형태. 근육이 의치를 눌러 앉히도록 설계한다.",
    example: "Concave polished surfaces developed to enhance stability.",
  },

  // ── 의치 · 조직면·변연 ──
  { ko: "압박부", en: "pressure area", section: "O", category: "의치", topic: "조직면·변연", order: 1,
    meaning: "PIP로 확인되는 조직면 과압박 지점.",
    example: "Pressure area over the left mylohyoid ridge identified with PIP; relieved.",
  },
  { ko: "과신장 / 과소신장", en: "over-extension / under-extension", section: "O", category: "의치", topic: "조직면·변연", order: 2,
    meaning: "의치 변연이 기능 범위를 넘거나 못 미치는 상태.",
    example: "Over-extension of the left buccal border by approximately 1 mm; shortened.",
    caution: "**과신장은 선상 궤양**, **과소신장은 유지 상실**로 나타난다 — 증상과 연결해 기재.",
  },
  { ko: "변연 폐쇄", en: "border seal", section: "O", category: "의치", topic: "조직면·변연", order: 3,
    meaning: "변연을 따라 형성되는 밀폐. 유지력의 물리적 기반.",
    example: "Border seal intact; posterior palatal seal effective.",
  },

  // ── 의치 · 술식 ──
  { ko: "이장 / 개상", en: "reline / rebase", section: "A·P", category: "의치", topic: "술식", order: 1,
    meaning: "의치 적합 회복 술식. **범위가 다르다.**",
    variants: "<dl><dt>reline</dt><dd><b>조직면만</b> 새 재료로 갱신</dd><dt>rebase</dt><dd><b>의치상 전체</b>를 교체하고 인공치만 유지</dd><dt>tissue conditioning</dt><dd>연조직 회복을 위한 <b>임시</b> 연성 이장</dd></dl>",
    example: "Functional reline of the mandibular denture indicated due to distal extension settling.",
  },
  { ko: "선택적 가압", en: "selective pressure", section: "O", category: "의치", topic: "술식", order: 2,
    meaning: "주지지역은 지지하고 완화부는 이격하는 인상 개념.",
    example: "Selective pressure impression with relief over the incisive papilla.",
  },
  { ko: "교합 재장착", en: "clinical remount", section: "O", category: "의치", topic: "술식", order: 3,
    meaning: "구내에서 새 악간관계를 채득해 교합기에 재부착 후 교합을 조정하는 절차.",
    example: "Clinical remount performed to correct processing-induced occlusal discrepancy.",
    caution: "중합 수축 오차는 **구내 조정만으로 교정되지 않는다** — 흔들리는 의치를 구내에서 갈면 오차가 함께 새겨진다.",
  },
  { ko: "선택 삭마", en: "selective grinding", section: "O", category: "의치", topic: "술식", order: 4,
    meaning: "교합기 상에서 규칙에 따라 특정 사면만 조정하는 것.",
    variants: "<dl><dt>CR 조기접촉</dt><dd>지지교두 보존, <b>대합 와를 깊게</b></dd><dt>작업측 간섭</dt><dd><b>BULL</b> — Buccal Upper, Lingual Lower 내사면</dd><dt>전방 간섭</dt><dd><b>DUML</b> — Distal Upper, Mesial Lower</dd></dl>",
    example: "Selective grinding per BULL rule to eliminate working interference.",
  },
  { ko: "조직 조정", en: "tissue conditioning", section: "O·A", category: "의치", topic: "술식", order: 5,
    meaning: "가소성 재료로 손상된 점막을 회복시키는 임시 처치.",
    example: "Tissue conditioner applied, to be changed every 5 days for 3 weeks.",
    caution: "**조직이 회복된 뒤 최종 인상**을 뜬다 — 부어 있는 상태의 인상은 회복 후 형태와 다르다.",
  },

  // ── 의치 · 병적 소견 ──
  { ko: "의치성 구내염", en: "denture stomatitis", section: "A", category: "의치", topic: "병적 소견", order: 1,
    meaning: "의치 지지 점막의 염증.",
    example: "Denture stomatitis, Newton type II (diffuse erythema) of the palatal mucosa.",
    caution: "**Newton 분류(I 국소 점상 / II 미만성 발적 / III 유두 증식성)** 를 함께 기재.",
  },

  // ── 의치 · 치조제 ──
  { ko: "가동 치조제", en: "flabby ridge (mobile ridge)", section: "O", category: "의치", topic: "치조제", order: 1,
    meaning: "섬유성으로 변해 가동성을 가진 치조제.",
    example: "Flabby ridge in the anterior maxilla, approximately 10 mm in span.",
    caution: "**선택적 무압인상(window technique)** 의 적응증이므로 범위를 mm로 기재.",
  },
  { ko: "치조제 흡수", en: "residual ridge resorption", section: "A", category: "의치", topic: "치조제", order: 2,
    meaning: "무치악 치조제의 진행성 흡수.",
    example: "Severe residual ridge resorption of the mandible with a knife-edge crest.",
    caution: "형태 표현: **well-formed / knife-edge / flat / resorbed**.",
  },

  // ── 의치 · RPD 구성요소 ──
  { ko: "대연결자", en: "major connector", section: "O", category: "의치", topic: "RPD 구성요소", order: 1,
    meaning: "의치의 좌우 요소를 연결하는 주 구조물.",
    variants: "<dl><dt>lingual bar</dt><dd>하악 기본형 — 유리치은연–구강저 <b>≥8 mm</b> 필요</dd><dt>lingual plate</dt><dd>공간 부족·전치 지지 필요 시</dd><dt>palatal strap</dt><dd>상악 — 폭 ≥8 mm, 치은연에서 6 mm 이격</dd><dt>AP palatal strap</dt><dd>강성 필요 시 전후방 이중 스트랩</dd></dl>",
    example: "Lingual bar major connector; floor of mouth height 9 mm.",
  },
  { ko: "소연결자", en: "minor connector", section: "O", category: "의치", topic: "RPD 구성요소", order: 2,
    meaning: "대연결자와 rest·클래스프 등을 잇는 구조물.",
    example: "Minor connectors placed at least 5 mm apart, entering the gingival margin perpendicularly.",
  },
  { ko: "클래스프 종류", en: "clasp designs: Akers / RPI / RPA / wrought wire", section: "O", category: "의치", topic: "RPD 구성요소", order: 3,
    meaning: "직접유지장치의 설계 유형.",
    variants: "<dl><dt>Akers (circumferential)</dt><dd>주조 원형 — <b>치아지지</b>에 적합</dd><dt>RPI</dt><dd>mesial rest + proximal plate + I-bar — <b>유리단 응력 완충</b></dd><dt>RPA</dt><dd>I-bar 대신 Akers 암 — 전정이 얕을 때</dd><dt>wrought wire</dt><dd>연성 와이어 — 유연해 응력 완충, 0.5 mm 언더컷</dd></dl>",
    example: "RPI clasp assemblies on #34 and #44 for the distal extension RPD.",
  },
  { ko: "유도면 / 인접판", en: "guiding plane / proximal plate", section: "O", category: "의치", topic: "RPD 구성요소", order: 4,
    meaning: "착탈로에 평행하게 형성한 인접면 / 그 면에 접하는 금속 판.",
    example: "Guiding planes prepared 3 mm in height on the distal of #34 and #44.",
  },
  { ko: "상반작용", en: "reciprocation", section: "O", category: "의치", topic: "RPD 구성요소", order: 5,
    meaning: "유지암이 언더컷을 지날 때 반대편에서 치아를 받쳐 측방력을 상쇄하는 작용.",
    example: "Reciprocation provided by the proximal plate and lingual bracing arm.",
    caution: "상반작용이 없으면 착탈 때마다 **지대치가 밀려 동요**가 생긴다.",
  },
  { ko: "레진 유지부", en: "retention lattice / mesh", section: "O", category: "의치", topic: "RPD 구성요소", order: 6,
    meaning: "의치상 레진을 금속 골격에 붙잡는 격자 구조.",
    example: "Open lattice retention designed for the distal extension bases.",
  },
  { ko: "완화", en: "relief", section: "O", category: "의치", topic: "RPD 구성요소", order: 7,
    meaning: "조직 압박을 피하기 위해 의치 내면을 의도적으로 이격하는 것.",
    example: "Relief provided over the midpalatine raphe and mandibular tori.",
  },

  // ── 의치 · 무치악 해부 ──
  { ko: "주지지역 / 부지지역", en: "primary / secondary stress-bearing area", section: "O", category: "의치", topic: "무치악 해부", order: 1,
    meaning: "저작압을 주로 받는 영역과 보조 영역.",
    variants: "<dl><dt>상악</dt><dd>주 — 수평 경구개 후방·치조제 정상</dd><dt>하악</dt><dd>주 — <b>buccal shelf</b> / 보조 — 치조제 정상·retromolar pad</dd></dl>",
    example: "Impression designed to load the buccal shelf as the primary stress-bearing area.",
  },
  { ko: "협붕", en: "buccal shelf", section: "O", category: "의치", topic: "무치악 해부", order: 2,
    meaning: "하악 구치부 협측의 넓고 치밀한 피질골 면. 하악 총의치의 주지지역.",
    example: "Buccal shelf adequately captured bilaterally.",
  },
  { ko: "구후융기", en: "retromolar pad", section: "O", category: "의치", topic: "무치악 해부", order: 3,
    meaning: "하악 최후방의 연조직 융기. 의치 후연의 기준이자 교합평면 높이의 지표.",
    example: "Denture border extended to cover the entire retromolar pad.",
    caution: "**교합평면은 통상 retromolar pad 상방 1/2–2/3 수준**에 둔다.",
  },
  { ko: "익돌하악 절흔", en: "hamular notch", section: "O", category: "의치", topic: "무치악 해부", order: 4,
    meaning: "상악 결절 후방의 함몰부. 후방 변연 폐쇄의 외측 종점.",
    example: "Hamular notches palpated and marked bilaterally.",
  },
  { ko: "진동선", en: "vibrating line", section: "O", category: "의치", topic: "무치악 해부", order: 5,
    meaning: "“아” 발음 시 연구개가 움직이기 시작하는 경계선. 후방 변연 폐쇄의 기준.",
    example: "Vibrating line identified with the “ah” sound and transferred to the cast.",
  },
  { ko: "후구개 봉쇄", en: "posterior palatal seal (post-dam)", section: "O", category: "의치", topic: "무치악 해부", order: 6,
    meaning: "상악 의치 후연에 형성해 변연 폐쇄를 강화하는 구조.",
    example: "Posterior palatal seal carved 1.5 mm deep in a butterfly form.",
  },
  { ko: "절치유두 / 정중구개봉합", en: "incisive papilla / midpalatine raphe", section: "O", category: "의치", topic: "무치악 해부", order: 7,
    meaning: "완화가 필요한 상악의 대표적 해부 구조.",
    example: "Relief provided over the incisive papilla and midpalatine raphe.",
    caution: "절치유두는 **비구개신경 통로**이므로 압박 시 통증·감각 이상을 유발한다.",
  },
  { ko: "악설골융선 / 구후설와", en: "mylohyoid ridge / retromylohyoid fossa", section: "O", category: "의치", topic: "무치악 해부", order: 8,
    meaning: "하악 설측의 예리한 골융선 / 그 후방의 함몰부.",
    example: "Relief over the sharp mylohyoid ridge; retromylohyoid fossa captured.",
  },
  { ko: "상악 결절", en: "maxillary tuberosity", section: "O", category: "의치", topic: "무치악 해부", order: 9,
    meaning: "상악 후방의 융기. 의치 안정에 기여하나 과도하면 공간을 잠식한다.",
    example: "Enlarged maxillary tuberosity limiting interocclusal space — reduction considered.",
  },

  // ── 임플란트 · 골·유착 ──
  { ko: "골유착", en: "osseointegration", section: "A", category: "임플란트", topic: "골·유착", order: 1,
    meaning: "임플란트와 골의 직접 결합.",
    example: "Osseointegration confirmed — clear percussion tone, no mobility, no peri-implant radiolucency, ISQ 76.",
  },
  { ko: "변연골 소실", en: "marginal bone loss", section: "O", category: "임플란트", topic: "골·유착", order: 2,
    meaning: "임플란트 주위 변연골 수준의 감소.",
    example: "Marginal bone loss 2.5 mm compared with the baseline radiograph, saucer-shaped defect.",
    caution: "**baseline 대비**임을 반드시 명시한다. 기준 영상이 없으면 판독 근거가 약해진다.",
  },
  { ko: "접시형 골결손", en: "saucer-shaped (crater) defect", section: "O", category: "임플란트", topic: "골·유착", order: 3,
    meaning: "임플란트 주위를 접시처럼 두르는 골 결손. 주위염의 전형적 형태.",
    example: "Circumferential saucer-shaped bone defect around the #46 implant.",
  },
  { ko: "나사산 노출", en: "thread exposure", section: "O", category: "임플란트", topic: "골·유착", order: 4,
    meaning: "골 소실로 임플란트 나사산이 드러난 상태.",
    example: "Two to three threads exposed on the mesial aspect.",
    caution: "**노출 나사산 수**로 표기하면 baseline 대비 변화를 추적하기 쉽다.",
  },
  { ko: "조기 실패 / 후기 실패", en: "early / late implant failure", section: "A", category: "임플란트", topic: "골·유착", order: 5,
    meaning: "골유착 성립 전 실패 / 성립 후 상실.",
    variants: "<dl><dt>early failure</dt><dd><b>골유착 성립 전</b> — 수술 술식·감염·과열·초기 안정성 부족</dd><dt>late failure</dt><dd><b>성립 후</b> — 주위염·과부하</dd></dl>",
    example: "Early implant failure at #36 — mobility at second-stage surgery.",
  },
  { ko: "협측 골판", en: "buccal bone plate", section: "O", category: "임플란트", topic: "골·유착", order: 6,
    meaning: "치조제 협측을 덮는 얇은 피질골. 심미부 예후의 핵심.",
    example: "Buccal bone plate thickness 0.8 mm on CBCT — grafting planned.",
    caution: "**2 mm 미만이면 흡수·퇴축 위험**이 커진다는 보고가 축적되어 있다.",
  },

  // ── 임플란트 · 기계적 합병증 ──
  { ko: "나사 풀림 / 파절", en: "screw loosening / screw fracture", section: "A", category: "임플란트", topic: "기계적 합병증", order: 1,
    meaning: "abutment 또는 보철 나사의 풀림·파절.",
    example: "Screw loosening of the #46 implant crown; screw replaced and retorqued to 25 Ncm.",
    caution: "**재조임만 하면 재발한다** — 교합 과부하 등 원인 교정을 함께 기재.",
  },
  { ko: "나사 예압", en: "preload", section: "O", category: "임플란트", topic: "기계적 합병증", order: 2,
    meaning: "토크로 나사에 형성되는 인장력. 나사 결합의 안정성을 좌우한다.",
    example: "Retorqued to the manufacturer-specified value to restore preload.",
    caution: "체결 직후 미세 표면 밀착으로 예압이 감소하는 **settling(embedment relaxation)** 때문에, 10분 뒤 재토크하는 프로토콜이 널리 쓰인다.",
  },
  { ko: "나사 풀림 반복", en: "recurrent screw loosening", section: "A", category: "임플란트", topic: "기계적 합병증", order: 3,
    meaning: "재조임에도 반복되는 나사 풀림.",
    example: "Recurrent screw loosening at #46 — occlusal overload and cantilever suspected.",
    caution: "**나사 교체만으로 끝내면 재발한다** — 교합·적합·cantilever 원인을 함께 기재.",
  },

  // ── 임플란트 · 주위 조직 ──
  { ko: "임플란트 주위 점막염", en: "peri-implant mucositis", section: "A", category: "임플란트", topic: "주위 조직", order: 1,
    meaning: "BOP를 동반한 연조직 염증으로 **골소실이 없는** 가역적 상태.",
    example: "Peri-implant mucositis at #46 — BOP(+), no progressive bone loss beyond initial remodeling.",
  },
  { ko: "임플란트 주위염", en: "peri-implantitis", section: "A", category: "임플란트", topic: "주위 조직", order: 2,
    meaning: "BOP·탐침 깊이 증가와 함께 **진행성 변연골 소실**을 동반한 상태.",
    example: "Peri-implantitis at #46 — BOP(+), PD 6 mm, progressive marginal bone loss 2.5 mm from baseline.",
    caution: "두 진단을 가르는 것은 **골소실의 유무**다. 점막염 단계에서 잡는 것이 목표.",
  },
  { ko: "잉여 시멘트", en: "excess (residual) cement", section: "O", category: "임플란트", topic: "주위 조직", order: 3,
    meaning: "치은연하에 남은 시멘트.",
    example: "Residual cement detected on PA at the distal of the #46 implant abutment.",
    caution: "임플란트 주위 질환과 강하게 연관된 인재(人災)성 원인이다.",
  },
  { ko: "연조직 두께", en: "mucosal (soft tissue) thickness", section: "O", category: "임플란트", topic: "주위 조직", order: 4,
    meaning: "임플란트 주위 점막의 수직 두께.",
    example: "Vertical mucosal thickness 1.5 mm — thin phenotype.",
    caution: "얇으면 초기 변연골 개조가 커지는 경향이 보고된다. **두께와 각화 폭은 다른 지표**이므로 각각 기재.",
  },

  // ── 임플란트 · 적합·설계 ──
  { ko: "수동적 적합", en: "passive fit", section: "O", category: "임플란트", topic: "적합·설계", order: 1,
    meaning: "강제력 없이 완전히 안착되는 적합.",
    example: "Passive fit achieved; no rocking, complete seating confirmed radiographically.",
  },
  { ko: "완전 안착", en: "complete seating", section: "O", category: "임플란트", topic: "적합·설계", order: 2,
    meaning: "보철물·코핑이 완전히 자리 잡은 상태.",
    example: "Complete seating of the impression coping confirmed on PA — no gap at the implant–coping interface.",
    caution: "임플란트에서는 **육안·촉진이 아니라 방사선으로** 확인한다.",
  },
  { ko: "플랫폼 스위칭", en: "platform switching", section: "O", category: "임플란트", topic: "적합·설계", order: 3,
    meaning: "fixture 직경보다 작은 abutment를 연결해 접합부를 내측으로 옮기는 설계.",
    example: "Platform-switched abutment placed; marginal bone level maintained at 12 months.",
  },

  // ── 임플란트 · 부품·연결 ──
  { ko: "픽스처 / 어버트먼트", en: "fixture (implant body) / abutment", section: "O", category: "임플란트", topic: "부품·연결", order: 1,
    meaning: "골 내에 식립되는 본체 / 그 위에 체결되어 보철을 지지하는 부품.",
    example: "Fixture ø4.5 x 10 mm with a titanium custom abutment.",
  },
  { ko: "커버 스크류 / 힐링 어버트먼트", en: "cover screw / healing abutment", section: "O", category: "임플란트", topic: "부품·연결", order: 2,
    meaning: "1차 수술 후 내부를 막는 나사 / 2차 수술 후 연조직 형태를 잡는 부품.",
    example: "Healing abutment ø5.0 x h4 mm connected at second-stage surgery.",
  },
  { ko: "인상 코핑 / 아날로그", en: "impression coping / implant analog", section: "O", category: "임플란트", topic: "부품·연결", order: 3,
    meaning: "인상에 임플란트 위치를 옮기는 부품 / 모형 내에 재현되는 복제품.",
    variants: "<dl><dt>open tray (pick-up)</dt><dd>인상재와 함께 <b>빠져 나옴</b> — 다수·비평행에 유리</dd><dt>closed tray (transfer)</dt><dd>구내에 <b>남고</b> 인상에 재위치 — 개구 제한 시 편리</dd></dl>",
    example: "Open tray impression coping splinted with pattern resin.",
  },
  { ko: "스캔 바디", en: "scan body", section: "O", category: "임플란트", topic: "부품·연결", order: 4,
    meaning: "디지털 인상에서 임플란트 위치·방향을 광학적으로 읽게 하는 부품.",
    example: "Scan body seated and verified radiographically before intraoral scanning.",
  },
  { ko: "멀티유닛 어버트먼트", en: "multi-unit abutment", section: "O", category: "임플란트", topic: "부품·연결", order: 5,
    meaning: "다수 임플란트를 연결한 스크류 유지 보철에서 공통 착탈로와 각도 보정을 제공하는 중간 부품.",
    example: "Multi-unit abutments placed to correct divergence for the screw-retained full-arch prosthesis.",
  },
  { ko: "Ti-base", en: "titanium base (Ti-base)", section: "O", category: "임플란트", topic: "부품·연결", order: 6,
    meaning: "임플란트 연결부는 티타늄이고 그 위에 세라믹 구조물을 접착하는 하이브리드 어버트먼트 부품.",
    example: "Zirconia abutment bonded to a Ti-base.",
  },
  { ko: "연결부 형태", en: "external hex / internal hex / conical connection", section: "O", category: "임플란트", topic: "부품·연결", order: 7,
    meaning: "픽스처와 어버트먼트의 결합 형태.",
    variants: "<dl><dt>external hex</dt><dd>외부 육각 — 초기 표준형</dd><dt>internal hex</dt><dd>내부 육각 — 안정성 향상</dd><dt>conical (morse taper)</dt><dd>원추형 — <b>미세간극·미세동요 감소</b>에 유리하다고 보고됨</dd></dl>",
    example: "Conical connection implant with platform switching.",
  },
  { ko: "미세간극", en: "microgap", section: "O", category: "임플란트", topic: "부품·연결", order: 8,
    meaning: "픽스처–어버트먼트 계면의 미세 틈. 세균 정착과 변연골 개조에 관여한다고 논의된다.",
    example: "Microgap positioned away from the crest by platform switching.",
  },
  { ko: "나사 유지형 / 시멘트 유지형", en: "screw-retained / cement-retained", section: "O", category: "임플란트", topic: "부품·연결", order: 9,
    meaning: "보철물 고정 방식.",
    variants: "<dl><dt>screw-retained</dt><dd><b>재접근 가능</b>, 잉여 시멘트 없음 — access hole 위치 제약</dd><dt>cement-retained</dt><dd>심미·교합면 자유도 — <b>잉여 시멘트 위험</b></dd><dt>SCRP</dt><dd>둘을 절충한 screw- and cement-retained 방식</dd></dl>",
    example: "Screw-retained crown selected; access hole located in the central fossa.",
  },
  { ko: "초기 안정성 / 식립 토크", en: "primary stability / insertion torque", section: "O", category: "임플란트", topic: "부품·연결", order: 10,
    meaning: "식립 직후의 기계적 안정성과 그 지표가 되는 토크값.",
    example: "Insertion torque 35 Ncm with good primary stability; immediate provisionalization planned.",
    caution: "**초기 안정성은 기계적 고정, 골유착은 생물학적 고정**이다 — 초기 토크가 높다고 골유착이 보장되지 않는다.",
  },
  { ko: "골수준 / 조직수준 임플란트", en: "bone-level / tissue-level implant", section: "O", category: "임플란트", topic: "부품·연결", order: 11,
    meaning: "연결부가 골정 높이에 있는 형태 / 연조직을 관통해 올라온 형태.",
    example: "Tissue-level implant placed in the posterior mandible.",
  },

  // ── 재료·기공 · 인상 ──
  { ko: "부가중합형 실리콘", en: "addition silicone (polyvinyl siloxane, PVS)", section: "O", category: "재료·기공", topic: "인상", order: 1,
    meaning: "정밀도와 치수 안정성이 우수한 탄성 인상재. 소수성이라 친수화 제품이 쓰인다.",
    example: "Final impression taken with heavy/light body PVS, one-step technique.",
    caution: "**라텍스 장갑의 황 성분이 중합을 저해**할 수 있다 — 퍼티 조작 시 비라텍스 장갑을 쓴다.",
  },
  { ko: "폴리이써", en: "polyether", section: "O", category: "재료·기공", topic: "인상", order: 2,
    meaning: "친수성이 우수해 습한 열구 재현에 유리하나 경화체가 단단해 제거가 어렵다.",
    example: "Polyether impression selected for the deep subgingival margin.",
    caution: "**수중 보관 시 흡수·팽윤**되므로 물에 담가 두지 않는다.",
  },
  { ko: "인상 결함", en: "impression defects: void / drag / pull / tear", section: "O", category: "재료·기공", topic: "인상", order: 3,
    meaning: "인상체의 대표적 결함.",
    variants: "<dl><dt>void</dt><dd>기포 — 주입 부족·공기 포획</dd><dt>drag</dt><dd>끌림 — 재료가 반경화 상태에서 움직임</dd><dt>pull</dt><dd>당김 — 언더컷에서 변형</dd><dt>tray show-through</dt><dd>트레이 노출 — 재료 두께 부족</dd></dl>",
    example: "Impression rejected due to voids at the distal margin; retaken.",
  },
  { ko: "개인 트레이", en: "custom tray", section: "O", category: "재료·기공", topic: "인상", order: 4,
    meaning: "개별 악궁에 맞춰 제작한 트레이. 균등한 재료 두께와 변연 조절이 가능.",
    example: "Custom tray fabricated with 2 mm spacer and three tissue stops.",
  },
  { ko: "조직 정지부", en: "tissue stop", section: "O", category: "재료·기공", topic: "인상", order: 5,
    meaning: "트레이가 조직에 눌리지 않고 균등한 간격을 유지하도록 두는 지지점.",
    example: "Three tissue stops placed to maintain uniform material thickness.",
  },

  // ── 재료·기공 · 세라믹·접착 ──
  { ko: "지르코니아 종류", en: "3Y-TZP / 4Y / 5Y zirconia", section: "O", category: "재료·기공", topic: "세라믹·접착", order: 1,
    meaning: "이트리아 함량에 따른 지르코니아 구분. 함량이 높을수록 투명도는 오르고 강도는 낮아진다.",
    variants: "<dl><dt>3Y-TZP</dt><dd>강도 최고, 투명도 낮음 — <b>구치부·장경간</b></dd><dt>4Y / 5Y</dt><dd>투명도 우수, 강도 감소 — <b>전치부 단관</b></dd></dl>",
    example: "Monolithic 3Y-TZP zirconia selected for the posterior long-span FDP.",
    caution: "“지르코니아는 다 강하다”는 오해를 피할 것 — **고투명 계열은 강도가 상당히 낮다.**",
  },
  { ko: "리튬디실리케이트", en: "lithium disilicate", section: "O", category: "재료·기공", topic: "세라믹·접착", order: 2,
    meaning: "심미와 강도의 균형이 좋은 유리세라믹. 산부식·실란 처리로 접착된다.",
    example: "Lithium disilicate crown etched with 5% HF for 20 s and silanated.",
  },
  { ko: "장석계 도재", en: "feldspathic porcelain", section: "O", category: "재료·기공", topic: "세라믹·접착", order: 3,
    meaning: "심미성이 가장 우수하나 강도가 낮아 **접착과 법랑질 지지**에 의존한다.",
    example: "Feldspathic veneers etched with 9.5% HF for 60 s.",
  },
  { ko: "모놀리식 / 축성", en: "monolithic / layered restoration", section: "O", category: "재료·기공", topic: "세라믹·접착", order: 4,
    meaning: "단일 재료로 만든 보철물 / 하부구조 위에 도재를 축성한 보철물.",
    example: "Monolithic zirconia chosen to avoid veneer chipping in a bruxer.",
    caution: "**축성형의 주된 실패는 도재 chipping**이다. 파라펑션 환자에서는 모놀리식이 유리하다.",
  },
  { ko: "실란 처리", en: "silanation", section: "O", category: "재료·기공", topic: "세라믹·접착", order: 5,
    meaning: "규소 함유 세라믹과 레진을 화학적으로 연결하는 커플링제 처리.",
    example: "Silane applied for 60 s and gently warm air dried.",
    caution: "**지르코니아에는 실란이 유효하지 않다** — MDP 함유 프라이머를 쓴다.",
  },
  { ko: "MDP 프라이머", en: "MDP-containing primer", section: "O", category: "재료·기공", topic: "세라믹·접착", order: 6,
    meaning: "인산 에스터 모노머로 지르코니아·금속 산화물과 화학 결합을 형성.",
    example: "MDP-containing primer applied to the airborne-particle-abraded zirconia surface.",
  },
  { ko: "알루미나 블라스팅", en: "airborne-particle abrasion", section: "O", category: "재료·기공", topic: "세라믹·접착", order: 7,
    meaning: "알루미나 입자를 분사해 표면을 거칠게 하고 오염을 제거하는 처리.",
    example: "Airborne-particle abrasion with 50 μm alumina at 0.1 MPa.",
    caution: "**압력이 과하면 지르코니아 표면에 상변태·미세균열**을 유발할 수 있어 저압·짧은 시간이 권장된다.",
  },
  { ko: "트라이보케미컬 처리", en: "tribochemical silica coating", section: "O", category: "재료·기공", topic: "세라믹·접착", order: 8,
    meaning: "실리카 피복 알루미나를 분사해 표면에 규소를 입힌 뒤 실란을 적용하는 방법.",
    example: "Tribochemical silica coating applied to the metal framework before silanation.",
  },
  { ko: "타액 오염 재세정", en: "decontamination after try-in", section: "O", category: "재료·기공", topic: "세라믹·접착", order: 9,
    meaning: "시적 중 타액에 오염된 접착면을 다시 세정하는 절차.",
    example: "Intaglio decontaminated with a zirconia cleaning agent after intraoral try-in.",
    caution: "**물세척만으로는 회복되지 않는다.** 타액 단백이 남아 접착 강도를 크게 떨어뜨린다.",
  },
  { ko: "응집 파괴 / 접착 파괴", en: "cohesive / adhesive failure", section: "O", category: "재료·기공", topic: "세라믹·접착", order: 10,
    meaning: "재료 내부에서 깨진 것 / 계면에서 떨어진 것.",
    example: "Adhesive failure at the cement–zirconia interface; cement fully retained on the tooth.",
    caution: "**파절면을 보면 원인이 갈린다** — 접착 파괴는 표면 처리 문제, 응집 파괴는 재료·두께·설계 문제를 시사.",
  },
  { ko: "중합 수축", en: "polymerization shrinkage", section: "O", category: "재료·기공", topic: "세라믹·접착", order: 11,
    meaning: "레진계 재료가 중합되며 부피가 줄어드는 현상.",
    example: "Processing discrepancy attributed to polymerization shrinkage; corrected by clinical remount.",
  },

  // ── 재료·기공 · 적합·가공 ──
  { ko: "변연 간극 / 내면 간극", en: "marginal gap / internal gap", section: "O", category: "재료·기공", topic: "적합·가공", order: 1,
    meaning: "보철물과 지대치 사이의 변연부 간격 / 내면 간격.",
    example: "Marginal gap within clinically acceptable limits; no detectable step on probing.",
    caution: "**cement space**(디자인 단계에서 지정하는 여유)와 구분한다. 시멘트 공간이 부족하면 완전 안착이 안 된다.",
  },
  { ko: "정확도 / 정밀도", en: "trueness / precision", section: "O", category: "재료·기공", topic: "적합·가공", order: 2,
    meaning: "참값에 얼마나 가까운가(trueness) / 반복 측정이 얼마나 일치하는가(precision).",
    example: "Full-arch scan showed acceptable precision but reduced trueness.",
    caution: "한국어로 둘 다 “정확도”로 뭉뚱그려지기 쉬우나 **디지털 인상 평가에서는 반드시 구분**한다.",
  },
  { ko: "소결", en: "sintering", section: "O", category: "재료·기공", topic: "적합·가공", order: 3,
    meaning: "분말·프리싱터 블록을 고온에서 치밀화하는 공정. 지르코니아는 소결 시 크게 수축한다.",
    example: "Framework milled oversized to compensate for sintering shrinkage.",
  },
  { ko: "주조 결함", en: "casting defects: porosity / node / incomplete casting", section: "O", category: "재료·기공", topic: "적합·가공", order: 4,
    meaning: "금속 주조체의 대표적 결함.",
    variants: "<dl><dt>porosity</dt><dd>기공 — 응고 수축·가스</dd><dt>node</dt><dd>돌기 — 매몰재 표면 결함</dd><dt>incomplete casting</dt><dd>미주조 — 주입 부족·통기 불량</dd></dl>",
    example: "RPD framework rejected due to porosity at the major connector.",
  },
  { ko: "납형 / 왁스업", en: "wax pattern / diagnostic wax-up", section: "O", category: "재료·기공", topic: "적합·가공", order: 5,
    meaning: "주조·복제를 위한 왁스 형태 / 최종 형태를 미리 설계한 진단용 왁스업.",
    example: "Diagnostic wax-up completed to determine the required increase in vertical dimension.",
  },
  { ko: "실리콘 인덱스", en: "silicone index (matrix)", section: "O", category: "재료·기공", topic: "적합·가공", order: 6,
    meaning: "왁스업·기존 형태를 복제해 삭제량 계측이나 임시보철 제작에 쓰는 실리콘 틀.",
    example: "Reduction verified against the silicone index cross-section.",
  },

  // ── 방사선 · 기본 기술 ──
  { ko: "투과상 / 불투과상", en: "radiolucency / radiopacity", section: "O", category: "방사선", topic: "기본 기술", order: 1,
    meaning: "방사선상 어두운 영역 / 밝은 영역.",
    example: "Marginal radiolucency at the distal of #46 crown.",
  },
  { ko: "경계 기술", en: "well-defined / ill-defined border", section: "O", category: "방사선", topic: "기본 기술", order: 2,
    meaning: "병소 경계의 명확성. 양성·악성 감별의 기본 기술 항목.",
    example: "Well-defined corticated border, unilocular radiolucency.",
    caution: "병소는 **위치·크기·경계·내부 구조·주변 반응**의 다섯 항목으로 기술하는 것이 표준이다.",
  },
  { ko: "단방성 / 다방성", en: "unilocular / multilocular", section: "O", category: "방사선", topic: "기본 기술", order: 3,
    meaning: "병소 내부가 단일 공간인지 격벽으로 나뉜 다방성인지.",
    example: "Multilocular radiolucency with a soap-bubble pattern.",
  },

  // ── 방사선 · 골 소견 ──
  { ko: "골소실 양상", en: "horizontal / vertical (angular) bone loss", section: "O", category: "방사선", topic: "골 소견", order: 1,
    meaning: "치조골 소실의 형태.",
    example: "Generalized horizontal bone loss of 20–30%; vertical defect at the mesial of #36.",
    caution: "**수직 결손은 부위를 특정**해 기재한다 — 재생 술식 적응 판단에 직결.",
  },
  { ko: "골 수준", en: "bone level", section: "O", category: "방사선", topic: "골 소견", order: 2,
    meaning: "치조골정의 위치. 임플란트에서는 플랫폼 기준.",
    example: "Marginal bone level at the implant platform, unchanged from baseline.",
  },
  { ko: "골 경화", en: "condensing osteitis / sclerotic bone", section: "A", category: "방사선", topic: "골 소견", order: 3,
    meaning: "만성 저강도 자극에 대한 반응성 골 경화.",
    example: "Condensing osteitis at the apex of #36.",
  },

  // ── 방사선 · 특징적 양상 ──
  { ko: "J형 투과상", en: "J-shaped (halo) radiolucency", section: "O", category: "방사선", topic: "특징적 양상", order: 1,
    meaning: "치근 측면을 따라 치근단까지 이어지는 투과상.",
    example: "J-shaped radiolucency along the distal root surface of #25.",
    caution: "**수직치근파절의 특징적 소견**이다.",
  },
  { ko: "치조백선 소실", en: "loss of lamina dura", section: "O", category: "방사선", topic: "특징적 양상", order: 2,
    meaning: "치근을 둘러싼 불투과성 선의 소실.",
    example: "Loss of lamina dura at the apex of #35.",
    caution: "치근단 병변의 초기 소견일 수 있으나 **촬영 각도로도 사라져 보인다** — 임상 소견과 함께 판단.",
  },
  { ko: "치주인대강 확대", en: "widened periodontal ligament space", section: "O", category: "방사선", topic: "특징적 양상", order: 3,
    meaning: "치근 주위 투과대의 폭 증가.",
    example: "Widened PDL space at #26 mesial root.",
    caution: "교합 외상이 흔한 원인이나, **비대칭적·진행성 확대는 악성 병변의 신호**일 수 있어 주의가 필요하다.",
  },
  { ko: "부유치 양상", en: "floating tooth appearance", section: "O", category: "방사선", topic: "특징적 양상", order: 4,
    meaning: "지지골이 광범위하게 소실되어 치아가 떠 있는 것처럼 보이는 상.",
    example: "Floating tooth appearance in the left mandibular molar region.",
    caution: "**침습적·전신 질환을 시사**할 수 있어 즉각적인 정밀 검사·의뢰가 필요하다.",
  },
  { ko: "간유리 양상", en: "ground-glass appearance", section: "O", category: "방사선", topic: "특징적 양상", order: 5,
    meaning: "미세 소주로 인해 젖빛 유리처럼 보이는 골 양상.",
    example: "Ground-glass appearance of the right maxilla with poorly defined borders.",
  },
  { ko: "벌레먹은 양상", en: "moth-eaten appearance", section: "O", category: "방사선", topic: "특징적 양상", order: 6,
    meaning: "불규칙한 다발성 투과상이 산재한 골 파괴 양상.",
    example: "Moth-eaten radiolucency of the mandibular body.",
  },
];
